// frontend/src/features/admin/RestartDialog.tsx
import { useEffect, useRef, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { describeApiError } from '../../lib/api/error-text'
import type { ApplyOutcome } from '../../lib/api/types'
import { useI18n } from '../../hooks/use-i18n'
import { adminRestartMutation, systemHealthQuery } from '../../lib/query/admin'
import { Button } from '../../ui/Button'
import { Dialog } from '../../ui/Dialog'
import { ProgressCircular } from '../../ui/ProgressCircular'
import { nextRestartWaitStep } from './logic/restart-wait'
import * as styles from './RestartDialog.css'

const POLL_INTERVAL_MS = 200
const WAIT_BUDGET_MS = 45_000
const WAIT_BUDGET_SECONDS = Math.round(WAIT_BUDGET_MS / 1000)
type Phase = 'confirm' | 'submitting' | 'waiting' | 'timeout' | 'success'
interface RestartDialogProps {
  open: boolean
  outcome: ApplyOutcome | null
  onClose: () => void
  onRestarted: () => void
}

export function RestartDialog({ open, outcome, onClose, onRestarted }: RestartDialogProps) {
  const { t } = useI18n()
  type RestartState = { phase: Phase; deadline: number | null; waitStartedAt: number | null; sawOutage: boolean }
  const [state, setState] = useState<RestartState>({
    phase: 'confirm',
    deadline: null,
    waitStartedAt: null,
    sawOutage: false
  })
  const { phase, deadline, waitStartedAt, sawOutage } = state
  const patchState = (patch: Partial<RestartState>): void => setState((current) => ({ ...current, ...patch }))
  const setPhase = (value: Phase): void => patchState({ phase: value })
  const setDeadline = (value: number | null): void => patchState({ deadline: value })
  const setWaitStartedAt = (value: number | null): void => patchState({ waitStartedAt: value })
  const setSawOutage = (value: boolean): void => patchState({ sawOutage: value })
  const wasOpen = useRef(false)
  const restart = useMutation(adminRestartMutation())
  const health = useQuery(systemHealthQuery(phase === 'waiting' ? POLL_INTERVAL_MS : false))
  useEffect(() => {
    if (open && !wasOpen.current) {
      setPhase('confirm')
      setDeadline(null)
      setWaitStartedAt(null)
      setSawOutage(false)
      restart.reset()
    }
    if (!open && phase === 'waiting') setPhase('confirm')
    wasOpen.current = open
  }, [open, phase, restart])
  useEffect(() => {
    if (!open || phase !== 'waiting' || waitStartedAt === null || deadline === null) return
    const step = nextRestartWaitStep(sawOutage, {
      isSuccess: health.isSuccess,
      succeededAt: health.dataUpdatedAt,
      isError: health.isError,
      erroredAt: health.errorUpdatedAt,
      waitStartedAt,
      now: Date.now(),
      deadline
    })
    setSawOutage(step.sawOutage)
    if (step.outcome === 'confirmed') {
      setPhase('success')
      onRestarted()
      const timer = window.setTimeout(onClose, 900)
      return () => window.clearTimeout(timer)
    }
    if (step.outcome === 'timed-out') setPhase('timeout')
  }, [
    open,
    phase,
    waitStartedAt,
    deadline,
    sawOutage,
    health.isSuccess,
    health.dataUpdatedAt,
    health.isError,
    health.errorUpdatedAt,
    onClose,
    onRestarted
  ])
  if (!open || !outcome?.restart_required) return null
  const activeUploads = outcome.active_uploads ?? 0
  const activeJobs = outcome.active_jobs ?? 0
  function beginWaiting(): void {
    const started = Date.now()
    setWaitStartedAt(started)
    setDeadline(started + WAIT_BUDGET_MS)
    setSawOutage(false)
    setPhase('waiting')
  }
  function confirmRestart(): void {
    restart.reset()
    setPhase('submitting')
    restart.mutate(undefined, {
      onSuccess: () => {
        if (open) beginWaiting()
      },
      onError: () => {
        if (open) setPhase('confirm')
      }
    })
  }
  const actions =
    phase === 'confirm' ? (
      <>
        <Button variant="text" onClick={onClose}>
          {t('common.cancel')}
        </Button>
        <Button danger onClick={confirmRestart}>
          {t('restart.restart_now')}
        </Button>
      </>
    ) : phase === 'submitting' ? (
      <>
        <Button variant="text" disabled>
          {t('common.cancel')}
        </Button>
        <Button loading>{t('restart.restart_now')}</Button>
      </>
    ) : phase === 'timeout' ? (
      <>
        <Button variant="text" onClick={onClose}>
          {t('common.close')}
        </Button>
        <Button onClick={beginWaiting}>{t('common.retry')}</Button>
      </>
    ) : (
      <Button variant="text" onClick={onClose}>
        {t('common.close')}
      </Button>
    )
  return (
    <Dialog open={open} title={t('restart.title')} onClose={onClose} actions={actions}>
      {phase === 'confirm' || phase === 'submitting' ? (
        <p>
          {activeUploads > 0 || activeJobs > 0
            ? t('restart.will_interrupt', { uploads: activeUploads, jobs: activeJobs })
            : t('restart.no_active_work')}
        </p>
      ) : null}
      {restart.error ? (
        <p className={styles.error} role="alert">
          {describeApiError(restart.error, t('restart.could_not_start'))}
        </p>
      ) : null}
      {phase === 'waiting' ? (
        <p className={styles.status} role="status" aria-live="polite">
          <ProgressCircular />
          {t('restart.waiting_for_server', { seconds: WAIT_BUDGET_SECONDS })}
        </p>
      ) : null}
      {phase === 'timeout' ? (
        <p className={styles.error} role="alert" aria-live="assertive">
          {t('restart.timed_out', { seconds: WAIT_BUDGET_SECONDS })}
        </p>
      ) : null}
      {phase === 'success' ? (
        <p className={styles.status} role="status" aria-live="polite">
          {t('restart.came_back')}
        </p>
      ) : null}
    </Dialog>
  )
}

// web/src/lib/ui/admin/RestartDialog.svelte
<script lang="ts">
  // The confirm-then-wait dialog for `POST /api/v1/admin/system/restart`
  // (`go/engine/http/server`'s `syscall.Exec` swap, same PID, container
  // survives). A restart interrupts in-flight uploads and running jobs, so
  // this never fires on its own: it always asks first, and the caller
  // decides when to show it by setting `open` from a save's own
  // `ApplyOutcome.restart_required`.
  //
  // After confirming, the socket is expected to drop while the process
  // re-execs itself, a failed `GET /api/v1/system/health` mid-wait is the
  // signal to keep polling, not a failure to report. Only the poll running
  // past its own bounded budget is worth surfacing.
  import { t } from '../../i18n'
  import { createMutation, createQuery } from '@tanstack/svelte-query'
  import { adminRestartMutation, systemHealthQuery } from '../../query/admin'
  import { describeApiError } from '../../api/error-text'
  import type { ApplyOutcome } from '../../api/types'
  import Button from '../Button.svelte'
  import Dialog from '../Dialog.svelte'
  import ProgressCircular from '../ProgressCircular.svelte'

  interface Props {
    open: boolean
    /** The save that triggered this. `null`, or an outcome that did not need
     *  a restart, both render nothing, the caller is not trusted to gate
     *  `open` correctly on its own. */
    outcome: ApplyOutcome | null
    /** Cancel, Escape, backdrop, or the dialog dismissing itself once the
     *  server is confirmed back. */
    onclose: () => void
    /** Fires once, the moment the health probe answers again after a
     *  confirmed restart. The caller reloads whatever it was showing; this
     *  component has no view of that state to refresh itself. */
    onrestarted: () => void
  }
  let { open, outcome, onclose, onrestarted }: Props = $props()

  type Phase = 'confirm' | 'submitting' | 'waiting' | 'timeout' | 'success'
  let phase = $state<Phase>('confirm')

  const POLL_INTERVAL_MS = 1_500
  const WAIT_BUDGET_MS = 45_000
  const WAIT_BUDGET_SECONDS = Math.round(WAIT_BUDGET_MS / 1000)

  const activeUploads = $derived(outcome?.active_uploads ?? 0)
  const activeJobs = $derived(outcome?.active_jobs ?? 0)

  const restartMutation = createMutation(() => adminRestartMutation())
  const submitError = $derived(
    restartMutation.error ? describeApiError(restartMutation.error, t('restart.could_not_start')) : null
  )

  // The wait budget this poll is bounded by. `pollMs` is what actually
  // drives the query's `refetchInterval`; it goes false the moment the
  // server answers or the budget runs out, which is what stops the polling.
  // `waitStartedAt` guards against a stale success: this query already ran
  // once on mount (before any restart was ever asked for), so a plain
  // `isSuccess` check would treat that leftover healthy answer as the
  // server having already come back, without ever actually re-checking it.
  let deadline = $state<number | null>(null)
  let waitStartedAt = $state<number | null>(null)
  let pollMs = $state<number | false>(false)
  const health = createQuery(() => systemHealthQuery(pollMs))

  function beginWaiting(): void {
    waitStartedAt = Date.now()
    deadline = Date.now() + WAIT_BUDGET_MS
    phase = 'waiting'
    pollMs = POLL_INTERVAL_MS
    void health.refetch()
  }

  $effect(() => {
    if (phase !== 'waiting' || !open) return
    // Both timestamps are read unconditionally so this effect re-runs on
    // every poll tick, success or failure, not only the first of either.
    const succeededAt = health.dataUpdatedAt
    void health.errorUpdatedAt
    if (health.isSuccess && waitStartedAt !== null && succeededAt >= waitStartedAt) {
      pollMs = false
      phase = 'success'
      onrestarted()
      const timer = setTimeout(() => {
        if (phase === 'success') onclose()
      }, 900)
      return () => clearTimeout(timer)
    }
    if (deadline !== null && Date.now() >= deadline) {
      pollMs = false
      phase = 'timeout'
      return
    }
    pollMs = POLL_INTERVAL_MS
  })

  // A fresh open resets to the confirm step; closing (by any route) stops
  // whatever polling is running rather than leaving it ticking in the
  // background for a dialog nobody is looking at.
  let wasOpen = $state(false)
  $effect(() => {
    if (open && !wasOpen) {
      phase = 'confirm'
      restartMutation.reset()
    }
    if (!open) pollMs = false
    wasOpen = open
  })

  function confirmRestart(): void {
    restartMutation.reset()
    phase = 'submitting'
    restartMutation.mutate(undefined, {
      onSuccess: () => {
        // The restart is already underway server-side by the time this
        // resolves: closing here cannot undo it. It only decides whether
        // this component keeps watching for it, which a dismissed dialog
        // should not.
        if (!open) return
        beginWaiting()
      },
      onError: () => {
        if (!open) return
        phase = 'confirm'
      }
    })
  }

  function retryWaiting(): void {
    beginWaiting()
  }
</script>

<Dialog open={open && !!outcome?.restart_required} title={t('restart.title')} {onclose}>
  {#if phase === 'confirm' || phase === 'submitting'}
    <p>
      {#if activeUploads > 0 || activeJobs > 0}
        {t('restart.will_interrupt', { uploads: activeUploads, jobs: activeJobs })}
      {:else}
        {t('restart.no_active_work')}
      {/if}
    </p>
    {#if submitError}
      <p class="sc-restart__error" role="alert">{submitError}</p>
    {/if}
  {:else if phase === 'waiting'}
    <p class="sc-restart__status" role="status" aria-live="polite">
      <ProgressCircular size={20} label={t('restart.waiting_for_server', { seconds: WAIT_BUDGET_SECONDS })} />
      {t('restart.waiting_for_server', { seconds: WAIT_BUDGET_SECONDS })}
    </p>
  {:else if phase === 'timeout'}
    <p class="sc-restart__error" role="alert" aria-live="assertive">
      {t('restart.timed_out', { seconds: WAIT_BUDGET_SECONDS })}
    </p>
  {:else if phase === 'success'}
    <p class="sc-restart__status" role="status" aria-live="polite">{t('restart.came_back')}</p>
  {/if}

  {#snippet actions()}
    {#if phase === 'confirm'}
      <Button variant="text" onclick={onclose}>{t('common.cancel')}</Button>
      <Button variant="filled" danger onclick={confirmRestart}>{t('restart.restart_now')}</Button>
    {:else if phase === 'submitting'}
      <Button variant="text" onclick={onclose} disabled>{t('common.cancel')}</Button>
      <Button variant="filled" danger loading>{t('restart.restart_now')}</Button>
    {:else if phase === 'waiting'}
      <Button variant="text" onclick={onclose}>{t('common.close')}</Button>
    {:else if phase === 'timeout'}
      <Button variant="text" onclick={onclose}>{t('common.close')}</Button>
      <Button variant="filled" onclick={retryWaiting}>{t('common.retry')}</Button>
    {:else if phase === 'success'}
      <Button variant="text" onclick={onclose}>{t('common.close')}</Button>
    {/if}
  {/snippet}
</Dialog>

<style>
  .sc-restart__status {
    display: inline-flex;
    align-items: center;
    gap: 12px;
  }
  .sc-restart__error {
    color: var(--m3c-error);
  }
</style>
