// web/src/lib/ui/admin/StorageIndexSection.svelte
<script lang="ts">
  // Storage usage and the optional file-name search index, admin-only,
  // rendered by `/admin` after it has checked `is_admin`.
  // GET /api/admin/storage, GET/POST /api/admin/index/estimate,
  // GET/PATCH /api/admin/index/settings.
  //
  // The index switch is a persisted runtime override, not a config-file edit:
  // it survives a restart on its own, the same way the upload chunk size does.
  // Its current value comes off the same settings snapshot
  // `ServerSettingsSection` reads (`adminSettingsQuery`), under the key the
  // server stores it by, since there is no endpoint for this one field alone
  // (`api.adminIndexSettings` used to parse the identical response); the two
  // screens share the one cache entry, so a build here or a save there
  // invalidate each other correctly.
  //
  // The cost figures are deliberately three numbers and one sentence. The
  // estimator can also derive them term by term, but that derivation is
  // written to the server log: on screen it read as noise to everyone who
  // had not written the estimator.
  import { createMutation, createQuery } from '@tanstack/svelte-query'
  import { formatDuration, formatNumber, t } from '../../i18n'
  import { describeApiError } from '../../api/error-text'
  import { formatBytes } from '../../format/bytes'
  import { adminBuildIndexMutation, adminIndexEstimateQuery, adminIndexSettingsMutation, adminIndexStatusQuery, adminSettingsQuery, adminStorageQuery } from '../../query/admin'
  import { queryClient } from '../../query/client'
  import { jobQuery } from '../../query/jobs'
  import { keys } from '../../query/keys'
  import { jobTray } from '../../store/jobs.store'
  import Button from '../Button.svelte'
  import ProgressCircular from '../ProgressCircular.svelte'
  import Switch from '../Switch.svelte'

  /** How much of the folder tree the estimate actually counted, in a sentence.
   *  The server sends a code so that this screen owns the wording; an unknown
   *  code means the server is newer than this build, and saying nothing is
   *  better than inventing a claim about accuracy.
   *
   *  `measured` is the posting term derived from sampled blocks, `modelled`
   *  the analytic fallback. These are the two the server has ever sent; the
   *  high/medium/low this once listed matched nothing, so the sentence never
   *  appeared. */
  const ACCURACY: Record<string, string> = {
    measured: /* i18n */ 'storage.accuracy_counted_everything',
    modelled: /* i18n */ 'storage.accuracy_counted_a_sample'
  }

  const storageQuery = createQuery(() => adminStorageQuery())
  const storage = $derived(storageQuery.data ?? null)
  const storageLoading = $derived(storageQuery.isPending)
  const storageError = $derived(storageQuery.error ? describeApiError(storageQuery.error, t('storage.could_not_load_storage_information')) : null)

  // The index's own state, shown unconditionally: whether it is on at all,
  // whether a completed build ever populated it, and whether it covers less
  // than the corpus. This is the answer to "is the index actually in use",
  // which used to be answerable only by starting a build and watching it.
  const indexStatusQuery = createQuery(() => adminIndexStatusQuery())
  const indexStatus = $derived(indexStatusQuery.data ?? null)
  const indexStatusLoading = $derived(indexStatusQuery.isPending)
  const indexStatusError = $derived(
    indexStatusQuery.error ? describeApiError(indexStatusQuery.error, t('storage.could_not_load_index_status')) : null
  )
  const indexStatusText = $derived.by(() => {
    if (!indexStatus) return null
    if (!indexStatus.enabled) return t('storage.index_off')
    if (indexStatus.entries === 0) return t('storage.index_empty')
    return t('storage.index_holding', { count: formatNumber(indexStatus.entries) })
  })

  // The estimate is deliberately not fetched until asked: it walks every
  // shared folder, so it stays a button rather than something this screen
  // does on load. `enabled` flips true on the first click; every click after
  // that is a plain refetch of the same query.
  let estimateRequested = $state(false)
  const estimateQuery = createQuery(() => ({ ...adminIndexEstimateQuery(), enabled: estimateRequested }))
  const estimate = $derived(estimateQuery.data ?? null)
  const estimateLoading = $derived(estimateQuery.isFetching)
  const estimateError = $derived(estimateQuery.error ? describeApiError(estimateQuery.error, t('storage.could_not_compute_estimate')) : null)

  function runEstimate(): void {
    if (!estimateRequested) estimateRequested = true
    else void estimateQuery.refetch()
  }

  const settingsQuery = createQuery(() => adminSettingsQuery())
  const nameEnabled = $derived(settingsQuery.data?.fields.find((f) => f.key === 'search.name_index_enabled')?.value === true)
  const settingsLoading = $derived(settingsQuery.isPending)

  const toggleMut = createMutation(() => adminIndexSettingsMutation())
  const settingsSaving = $derived(toggleMut.isPending)
  const settingsError = $derived.by(() => {
    if (toggleMut.error) return describeApiError(toggleMut.error, t('common.could_not_save_settings'))
    if (settingsQuery.error) return describeApiError(settingsQuery.error, t('storage.could_not_load_index_settings'))
    return null
  })

  function onToggleEnabled(checked: boolean): void {
    toggleMut.mutate(checked)
  }

  // Fire-and-forget through the shared job queue (`JobTray`, mounted once at
  // the app layout): same pattern as `downloadAsArchive`'s `jobTray.track`
  // call, not a second progress mechanism just for this button. This screen
  // additionally tracks the job it started itself, so this build's own
  // progress and terminal state show up here, not only in the global tray.
  const buildMut = createMutation(() => adminBuildIndexMutation())
  const buildStarting = $derived(buildMut.isPending)
  const buildError = $derived(buildMut.error ? describeApiError(buildMut.error, t('storage.could_not_start_index_build')) : null)

  let buildJobId = $state<string | null>(null)
  const buildJobQuery = createQuery(() => ({ ...jobQuery(buildJobId ?? ''), enabled: buildJobId !== null }))
  const buildJob = $derived(buildJobQuery.data ?? null)
  const buildJobRunning = $derived(buildJob !== null && buildJob.state === 'running')
  const buildStatusText = $derived.by(() => {
    if (!buildJob) return null
    switch (buildJob.state) {
      case 'running':
        return t('storage.build_running', { count: formatNumber(buildJob.done) })
      case 'done':
        return t('storage.build_done', { count: formatNumber(buildJob.done) })
      case 'cancelled':
      case 'interrupted':
        return t('storage.build_stopped', { count: formatNumber(buildJob.done) })
      case 'error':
        return t('storage.build_failed')
    }
  })

  // Once the tracked build reaches a terminal state its own job status can
  // no longer change, but the index's own entry count is now stale: refresh
  // it here rather than waiting on whatever else happens to invalidate it.
  // Runs once per terminal arrival, since `buildJob`'s identity only changes
  // when the query's data actually changes and a terminal job stops polling.
  $effect(() => {
    if (buildJob && buildJob.state !== 'running') {
      void queryClient.invalidateQueries({ queryKey: keys.adminIndexStatus() })
    }
  })

  function startBuild(): void {
    buildMut.mutate(undefined, {
      onSuccess: (job) => {
        jobTray.track(job.id)
        buildJobId = job.id
      }
    })
  }
</script>

<section class="sc-admin-section">
  <h3>{t('common.storage')}</h3>
  {#if storageLoading}
    <ProgressCircular />
  {:else if storageError}
    <p class="sc-admin-section__error">{storageError}</p>
  {:else if storage}
    <ul class="sc-admin-section__shares">
      <li>
        <span class="sc-admin-section__share-label">{t('storage.file_database')}</span>
        <span class="sc-admin-section__share-usage">{formatBytes(storage.db_bytes)}</span>
      </li>
      {#each storage.shares as s (s.label)}
        <li>
          <span class="sc-filename sc-admin-section__share-label">{s.label}</span>
          <span class="sc-admin-section__share-usage">
            {t('storage.free', { free: formatBytes(s.free_bytes), total: formatBytes(s.total_bytes) })}
          </span>
        </li>
      {/each}
    </ul>
  {/if}
</section>

<section class="sc-admin-section">
  <h3>{t('storage.search_index')}</h3>
  <p class="sc-admin-section__hint">{t('storage.what_the_index_is_for')}</p>

  <div class="sc-admin-section__row">
    <span class="sc-admin-section__index-status-label">{t('storage.index_status')}</span>
    {#if indexStatusLoading}
      <ProgressCircular size={20} />
    {:else if indexStatusText}
      <span>{indexStatusText}</span>
    {/if}
  </div>
  {#if indexStatusError}<p class="sc-admin-section__error">{indexStatusError}</p>{/if}
  {#if indexStatus?.incomplete}
    <p class="sc-admin-section__warning" role="alert">{t('storage.index_incomplete')}</p>
  {/if}

  {#if settingsLoading}
    <ProgressCircular />
  {:else}
    <div class="sc-admin-section__row">
      <Switch
        checked={nameEnabled}
        label={t('storage.enable_name_index')}
        onchange={onToggleEnabled}
      />
      {#if settingsSaving}<span class="sc-admin-section__saving">{t('common.saving')}</span>{/if}
    </div>
    {#if settingsError}<p class="sc-admin-section__error">{settingsError}</p>{/if}

    <!-- Cost before commitment: the estimate walks every shared folder, so it
         stays a button rather than something the admin screen does on load. -->
    <div class="sc-admin-section__cost">
      {#if estimate}
        <dl class="sc-admin-section__figures">
          <div>
            <dt>{t('storage.files_to_index')}</dt>
            <dd>{formatNumber(estimate.files)}</dd>
          </div>
          <div>
            <dt>{t('storage.disk_space_needed')}</dt>
            <dd>{formatBytes(estimate.index_bytes)}</dd>
          </div>
          <div>
            <dt>{t('storage.time_to_build')}</dt>
            <dd>{formatDuration(estimate.build_secs)}</dd>
          </div>
        </dl>
        <p class="sc-admin-section__note">
          {#if ACCURACY[estimate.confidence]}{t(ACCURACY[estimate.confidence])}{/if}
          {t('storage.build_only_runs_while_idle')}
        </p>
      {:else}
        <p class="sc-admin-section__note">{t('storage.measure_before_turning_on')}</p>
      {/if}
      <Button variant="outlined" loading={estimateLoading} onclick={runEstimate}>
        {estimate ? t('storage.measure_again') : t('storage.measure_the_cost')}
      </Button>
      {#if estimateError}<p class="sc-admin-section__error">{estimateError}</p>{/if}
    </div>

    <div class="sc-admin-section__row">
      <Button
        variant="outlined"
        loading={buildStarting}
        disabled={!nameEnabled || buildJobRunning}
        onclick={startBuild}
      >
        {t('storage.start_index_build')}
      </Button>
    </div>
    {#if buildStatusText}
      <p class="sc-admin-section__note" aria-live="polite">{buildStatusText}</p>
    {/if}
    <p class="sc-admin-section__note">
      {nameEnabled ? t('storage.first_build_is_manual') : t('storage.turn_it_on_before_building')}
    </p>
    {#if buildError}<p class="sc-admin-section__error">{buildError}</p>{/if}

    <p class="sc-admin-section__hint">
      {t('storage.turning_it_off_keeps_the_existing_index')}
      {t('storage.to_free_the_space_delete')} <code>.scindex</code>
      {t('storage.in_each_shared_folder')}
    </p>
  {/if}
</section>

<style>
  .sc-admin-section {
    margin-block: 24px;
  }
  .sc-admin-section h3 {
    margin: 0 0 8px;
    @apply --m3-title-medium;
  }
  .sc-admin-section__error {
    margin: 8px 0 0;
    color: var(--m3c-error);
    @apply --m3-body-small;
  }
  .sc-admin-section__row {
    display: flex;
    align-items: center;
    gap: 12px;
    margin-bottom: 12px;
  }
  .sc-admin-section__saving {
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
  .sc-admin-section__hint {
    max-width: 640px;
    margin: 0 0 16px;
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
  .sc-admin-section__note {
    max-width: 640px;
    margin: 0 0 12px;
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
  .sc-admin-section__shares {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .sc-admin-section__shares li {
    display: flex;
    justify-content: space-between;
    gap: 16px;
    max-width: 480px;
    padding-block: 4px;
  }
  .sc-admin-section__share-label {
    /* Without `min-width: 0` this flex item cannot shrink below its text's
       min-content size, so the fixed-width usage column squeezes it and a long
       label wraps one syllable per line instead of ellipsizing. */
    min-width: 0;
    flex: 1 1 auto;
  }
  .sc-admin-section__share-usage {
    flex-shrink: 0;
    color: var(--m3c-on-surface-variant);
  }
  .sc-admin-section__cost {
    max-width: 640px;
    margin-bottom: 16px;
    padding: 16px;
    border: 1px solid var(--m3c-outline-variant);
    border-radius: var(--m3-shape-medium);
  }
  .sc-admin-section__figures {
    display: grid;
    /* Three figures side by side where there is room, stacked where there is
       not: a fixed three-column grid put "about 42 seconds" on two lines on a
       phone. */
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 16px;
    margin: 0 0 12px;
  }
  .sc-admin-section__figures div {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .sc-admin-section__figures dt {
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
  .sc-admin-section__figures dd {
    margin: 0;
    color: var(--m3c-on-surface);
    @apply --m3-title-medium;
  }
  .sc-admin-section__index-status-label {
    color: var(--m3c-on-surface-variant);
  }
  /* Same colours as `ServerSettingsSection.svelte`'s `.sc-admin-section__warning`:
     a scoped style block, so the class has to be repeated here rather than
     shared, but the two screens should still read as one visual language. */
  .sc-admin-section__warning {
    padding: 12px 16px;
    border-radius: var(--m3-shape-extra-small);
    background: var(--m3c-error-container);
    color: var(--m3c-on-error-container);
    @apply --m3-body-medium;
    margin: 0 0 12px;
  }
</style>

// web/src/lib/ui/admin/StorageIndexSection.tsx
import { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { formatBytes } from '../../../lib/format/bytes'
import { formatDuration, formatNumber } from '../../../lib/i18n'
import { useI18n } from '../../../lib/i18n/use-i18n'
import { describeApiError } from '../../../lib/api/error-text'
import { adminBuildIndexMutation, adminIndexEstimateQuery, adminIndexSettingsMutation, adminIndexStatusQuery, adminSettingsQuery, adminStorageQuery } from '../../../lib/query/admin'
import { jobQuery } from '../../../lib/query/jobs'
import { jobTray } from '../../../lib/store/jobs.store'
import { Button } from '../Button'
import { Icon } from '../Icon'
import { Switch } from '../Switch'
import { ProgressCircular } from '../ProgressCircular'
import { VirtualList } from '../VirtualList'
import './admin-sections.css'

const ACCURACY: Record<string, string> = { measured: 'storage.accuracy_counted_everything', modelled: 'storage.accuracy_counted_a_sample' }
/* i18n */ 'storage.accuracy_counted_everything'
/* i18n */ 'storage.accuracy_counted_a_sample'

export function StorageIndexSection() {
  const { t } = useI18n()
  const qc = useQueryClient()
  const storage = useQuery(adminStorageQuery())
  const storageItems = useMemo(() => storage.data ? [storage.data, ...storage.data.shares] : [], [storage.data])
  const status = useQuery(adminIndexStatusQuery())
  const settings = useQuery(adminSettingsQuery())
  const [estimateRequested, setEstimateRequested] = useState(false)
  const estimate = useQuery({ ...adminIndexEstimateQuery(), enabled: estimateRequested })
  const toggle = useMutation(adminIndexSettingsMutation())
  const build = useMutation(adminBuildIndexMutation())
  const [jobId, setJobId] = useState<string | null>(null)
  const job = useQuery({ ...jobQuery(jobId ?? ''), enabled: jobId !== null })
  const nameEnabled = settings.data?.fields.find((field) => field.key === 'search.name_index_enabled')?.value === true
  useEffect(() => { if (job.data && job.data.state !== 'running') void qc.invalidateQueries({ queryKey: ['admin', 'index-status'] }) }, [job.data, qc])
  function estimateCost(): void { if (!estimateRequested) setEstimateRequested(true); else void estimate.refetch() }
  function startBuild(): void { build.mutate(undefined, { onSuccess: (result) => { jobTray.track(result.id); setJobId(result.id) } }) }
  let jobText: string | null = null
  if (job.data?.state === 'running') jobText = t('storage.build_running', { count: formatNumber(job.data.done) })
  else if (job.data?.state === 'done') jobText = t('storage.build_done', { count: formatNumber(job.data.done) })
  else if (job.data?.state === 'cancelled' || job.data?.state === 'interrupted') jobText = t('storage.build_stopped', { count: formatNumber(job.data.done) })
  else if (job.data?.state === 'error') jobText = t('storage.build_failed')
  const statusText = status.data ? !status.data.enabled ? t('storage.index_off') : status.data.entries === 0 ? t('storage.index_empty') : t('storage.index_holding', { count: formatNumber(status.data.entries) }) : null
  return (
    <>
      <article className="sc-admin-card">
        <div className="sc-admin-card-head">
          <div className="sc-admin-card-icon"><Icon name="storage" /></div>
          <div className="sc-admin-card-meta">
            <h3 className="sc-admin-card-title">{t('common.storage')}</h3>
            <p className="sc-admin-card-subtitle">{t('admin.server_storage_paths')}</p>
          </div>
        </div>
        {storage.isPending ? (
          <ProgressCircular />
        ) : storage.error ? (
          <p className="sc-admin-error">{describeApiError(storage.error, t('storage.could_not_load_storage_information'))}</p>
        ) : storage.data ? (
          <VirtualList
            className="sc-storage-list"
            items={storageItems}
            itemKey={(item) => 'db_bytes' in item ? 'database' : `share:${item.label}`}
            estimateSize={48}
            renderItem={(item) => 'db_bytes' in item ? (
              <>
                <div className="sc-storage__item-label">
                  <Icon name="database" size={18} />
                  <span>{t('storage.file_database')}</span>
                </div>
                <strong>{formatBytes(item.db_bytes)}</strong>
              </>
            ) : (
              <>
                <div className="sc-storage__item-label">
                  <Icon name="folder" size={18} />
                  <span className="sc-filename">{item.label}</span>
                </div>
                <strong>{t('storage.free', { free: formatBytes(item.free_bytes), total: formatBytes(item.total_bytes) })}</strong>
              </>
            )}
          />
        ) : null}
      </article>

      <article className="sc-admin-card">
        <div className="sc-admin-card-head">
          <div className="sc-admin-card-icon"><Icon name="search" /></div>
          <div className="sc-admin-card-meta">
            <h3 className="sc-admin-card-title">{t('storage.search_index')}</h3>
            <p className="sc-admin-card-subtitle">{t('storage.what_the_index_is_for')}</p>
          </div>
        </div>

        <div className="sc-storage__status-row">
          <span className="sc-storage__status-label">{t('storage.index_status')}</span>
          <span className={`sc-storage__status-badge ${status.data?.enabled ? 'sc-storage__status-badge--on' : ''}`}>
            {status.isPending ? <ProgressCircular size={16} /> : statusText}
          </span>
        </div>

        {status.error ? <p className="sc-admin-error">{describeApiError(status.error, t('storage.could_not_load_index_status'))}</p> : null}
        {settings.error ? <p className="sc-admin-error">{describeApiError(settings.error, t('storage.could_not_load_index_settings'))}</p> : null}
        {status.data?.incomplete ? <p className="sc-admin-warning" role="alert">{t('storage.index_incomplete')}</p> : null}

        {settings.isPending ? (
          <ProgressCircular />
        ) : (
          <>
            <div className="sc-storage__toggle-row">
              <Switch checked={nameEnabled} label={t('storage.enable_name_index')} onChange={(checked) => toggle.mutate(checked)} />
              {toggle.isPending ? <span className="sc-admin-note">{t('common.saving')}</span> : null}
            </div>
            {toggle.error ? <p className="sc-admin-error">{describeApiError(toggle.error, t('common.could_not_save_settings'))}</p> : null}

            <div className="sc-index-cost">
              {estimate.data ? (
                <>
                  <dl>
                    <div>
                      <dt>{t('storage.files_to_index')}</dt>
                      <dd>{formatNumber(estimate.data.files)}</dd>
                    </div>
                    <div>
                      <dt>{t('storage.disk_space_needed')}</dt>
                      <dd>{formatBytes(estimate.data.index_bytes)}</dd>
                    </div>
                    <div>
                      <dt>{t('storage.time_to_build')}</dt>
                      <dd>{formatDuration(estimate.data.build_secs)}</dd>
                    </div>
                  </dl>
                  <p className="sc-admin-note">{ACCURACY[estimate.data.confidence] ? t(ACCURACY[estimate.data.confidence]) : null} {t('storage.build_only_runs_while_idle')}</p>
                </>
              ) : (
                <p className="sc-admin-note">{t('storage.measure_before_turning_on')}</p>
              )}
              <div className="sc-admin-row">
                <Button variant="outlined" loading={estimate.isFetching} onClick={estimateCost}>
                  {estimate.data ? t('storage.measure_again') : t('storage.measure_the_cost')}
                </Button>
              </div>
              {estimate.error ? <p className="sc-admin-error">{describeApiError(estimate.error, t('storage.could_not_compute_estimate'))}</p> : null}
            </div>

            <div className="sc-admin-row">
              <Button variant="filled" loading={build.isPending} disabled={!nameEnabled || job.data?.state === 'running'} onClick={startBuild}>
                {t('storage.start_index_build')}
              </Button>
            </div>
            {jobText ? <p className="sc-admin-note" aria-live="polite">{jobText}</p> : null}
            <p className="sc-admin-note">{nameEnabled ? t('storage.first_build_is_manual') : t('storage.turn_it_on_before_building')}</p>
            {build.error ? <p className="sc-admin-error">{describeApiError(build.error, t('storage.could_not_start_index_build'))}</p> : null}
            <p className="sc-admin-hint">{t('storage.turning_it_off_keeps_the_existing_index')} {t('storage.to_free_the_space_delete')} <code>.scindex</code> {t('storage.in_each_shared_folder')}</p>
          </>
        )}
      </article>
    </>
  )
}
