// web/src/lib/ui/admin/UserManagementSection.svelte
<script lang="ts">
  // User management: admin-only screen built on top of's
  // role model (§8, `user.role`). GET/POST /api/admin/users, PATCH/DELETE
  // /api/admin/users/{id}.
  //
  // Last-admin protection: the server (`go/internal/auth/admin.go`)
  // has final say and rejects with 409 `admin.last_admin`. This screen does
  // two things, neither of which replaces the server-side defense: shows
  // that failure clearly, and pre-disables the toggle/delete buttons when
  // only one active admin remains, to cut down on accidental clicks.
  import { createMutation, createQuery } from '@tanstack/svelte-query'
  import { t } from '../../i18n'
  import { ApiError, type AdminUser } from '../../api/client'
  import { describeApiError } from '../../api/error-text'
  import { adminUserMutation, adminUsersQuery } from '../../query/admin'
  import { BYTES_PER_MB, bytesToMb, formatBytes } from '../../format/bytes'
  import { scorePasswordStrength } from '../../format/password-strength'
  import Button from '../Button.svelte'
  import Dialog from '../Dialog.svelte'
  import ListItem from '../ListItem.svelte'
  import IconButton from '../IconButton.svelte'
  import { Icon } from 'm3-svelte'
  import { icons } from '../../icons'
  import Switch from '../Switch.svelte'
  import TextField from '../TextField.svelte'
  import Chip from '../Chip.svelte'
  import ProgressCircular from '../ProgressCircular.svelte'
  import ProgressLinear from '../ProgressLinear.svelte'
  import GrantManagementSection from './GrantManagementSection.svelte'
  import UserOidcDialog from './UserOidcDialog.svelte'

  const MIN_PASSWORD_LEN = 10

  const usersQuery = createQuery(() => adminUsersQuery())
  const users = $derived(usersQuery.data ?? [])
  const loading = $derived(usersQuery.isPending)
  const loadError = $derived(usersQuery.error ? describeApiError(usersQuery.error, t('user.could_not_load_user_list')) : null)

  const activeAdminCount = $derived(users.filter((u) => u.is_admin && !u.disabled).length)

  /** Would disabling/deleting this account leave zero active admins? The
   *  server has final say, but there's no reason to let anyone press a
   *  button that's guaranteed to be rejected. */
  function isLastActiveAdmin(u: AdminUser): boolean {
    return u.is_admin && !u.disabled && activeAdminCount <= 1
  }

  // Dialog that sets which folders a just-created (or picked-from-the-list)
  // user can see. "Create a user" has to lead straight into "and decide what
  // they see": an account with zero grants just shows a blank screen on
  // login, which reads as a broken server, not a state anyone chose on
  // purpose.
  let grantsTarget = $state<AdminUser | null>(null)

  function openGrants(u: AdminUser): void {
    grantsTarget = u
  }

  function closeGrants(): void {
    grantsTarget = null
  }

  // Single sign-on, per account (`docs/proposals/stowcloud-0-oidc-login.md`
  // §5-1). Its own dialog: reading, attaching and detaching an identity is
  // three routes and a two-step confirmation, and none of it belongs in this
  // list's row.
  let oidcTarget = $state<AdminUser | null>(null)

  function openOidc(u: AdminUser): void {
    oidcTarget = u
  }

  function closeOidc(): void {
    oidcTarget = null
  }

  // ── create ──

  let createOpen = $state(false)
  let newName = $state('')
  let newPassword = $state('')
  let createValidation = $state<string | null>(null)
  const newPasswordStrength = $derived(scorePasswordStrength(newPassword))

  const createMut = createMutation(() => adminUserMutation())
  const creating = $derived(createMut.isPending)
  const createError = $derived.by(() => {
    if (createValidation) return createValidation
    const err = createMut.error
    if (!err) return null
    if (err instanceof ApiError && err.code === 'fs.conflict') return t('common.name_already_taken')
    if (err instanceof ApiError && err.code === 'auth.weak_password') {
      const min = err.reasonNumber('min_length') ?? MIN_PASSWORD_LEN
      return t('user.password_must_at_least_characters', { min })
    }
    return describeApiError(err, t('user.could_not_create_user'))
  })

  function openCreate(): void {
    newName = ''
    newPassword = ''
    createValidation = null
    createMut.reset()
    createOpen = true
  }

  function closeCreate(): void {
    if (creating) return
    createOpen = false
  }

  async function submitCreate(e?: SubmitEvent): Promise<void> {
    e?.preventDefault()
    createValidation = null
    if (newPassword.length < MIN_PASSWORD_LEN) {
      createValidation = t('user.password_must_at_least_characters', { min: MIN_PASSWORD_LEN })
      return
    }
    try {
      const created = (await createMut.mutateAsync({ kind: 'create', name: newName, password: newPassword })) as AdminUser
      createOpen = false
      openGrants(created)
    } catch {
      // createError above reads the failure straight off createMut.error
    }
  }

  // ── enable/disable ──

  const toggleMut = createMutation(() => adminUserMutation())
  const togglingId = $derived(toggleMut.isPending && toggleMut.variables?.kind === 'disable' ? toggleMut.variables.id : null)
  const toggleError = $derived.by(() => {
    const err = toggleMut.error
    if (!err) return null
    if (err instanceof ApiError && err.code === 'admin.last_admin') return t('user.last_administrator_cannot_deactivated')
    return describeApiError(err, t('common.could_not_save_change'))
  })

  function toggleDisabled(u: AdminUser, disabled: boolean): void {
    toggleMut.mutate({ kind: 'disable', id: u.id, disabled })
  }

  // ── delete ──

  const deleteMut = createMutation(() => adminUserMutation())
  const deleting = $derived(deleteMut.isPending)
  const deleteError = $derived.by(() => {
    const err = deleteMut.error
    if (!err) return null
    if (err instanceof ApiError && err.code === 'admin.last_admin') return t('user.last_administrator_cannot_deleted')
    return describeApiError(err, t('common.could_not_delete'))
  })

  let deleteTarget = $state<AdminUser | null>(null)

  function askDelete(u: AdminUser): void {
    deleteMut.reset()
    deleteTarget = u
  }

  function closeDelete(): void {
    if (deleting) return
    deleteTarget = null
  }

  async function confirmDelete(): Promise<void> {
    if (!deleteTarget) return
    try {
      await deleteMut.mutateAsync({ kind: 'delete', id: deleteTarget.id })
      deleteTarget = null
    } catch {
      // deleteError above reads the failure straight off deleteMut.error
    }
  }

  // ── quota ──
  //
  // `quota_bytes` is the cap, enforced on upload/copy/write against the
  // running `usage_bytes` ledger (`go/internal/core/quota.go`). A write
  // that would exceed it is refused with `507 quota.exceeded`, not just
  // reported to NC clients.
  const quotaMut = createMutation(() => adminUserMutation())
  const quotaSaving = $derived(quotaMut.isPending)
  let quotaTarget = $state<AdminUser | null>(null)
  let quotaInput = $state('')
  let quotaValidation = $state<string | null>(null)
  const quotaError = $derived.by(() => {
    if (quotaValidation) return quotaValidation
    const err = quotaMut.error
    if (!err) return null
    if (err instanceof ApiError && err.code === 'admin.invalid_quota') return t('user.enter_number_greater_than_0')
    return describeApiError(err, t('common.could_not_save'))
  })

  /** Chip text: "1.2 GB / 5 GB" when capped, "1.2 GB used" (unlimited) otherwise. */
  function quotaLabel(u: AdminUser): string {
    const used = formatBytes(Number(BigInt(u.usage_bytes)))
    if (!u.quota_bytes) return t('user.used', { used })
    return `${used} / ${formatBytes(Number(BigInt(u.quota_bytes)))}`
  }

  function openQuota(u: AdminUser): void {
    quotaValidation = null
    quotaMut.reset()
    quotaInput = u.quota_bytes ? String(bytesToMb(Number(BigInt(u.quota_bytes)))) : ''
    quotaTarget = u
  }

  function closeQuota(): void {
    if (quotaSaving) return
    quotaTarget = null
  }

  async function submitQuota(e?: SubmitEvent): Promise<void> {
    e?.preventDefault()
    if (!quotaTarget) return
    quotaValidation = null
    const trimmed = quotaInput.trim()
    let bytes: number | null = null
    if (trimmed) {
      const mb = Number(trimmed)
      if (!Number.isFinite(mb) || mb <= 0) {
        quotaValidation = t('user.enter_number_greater_than_0')
        return
      }
      bytes = Math.round(mb * BYTES_PER_MB)
    }
    try {
      await quotaMut.mutateAsync({ kind: 'quota', id: quotaTarget.id, quotaBytes: bytes })
      quotaTarget = null
    } catch {
      // quotaError above reads the failure straight off quotaMut.error
    }
  }
</script>

<section class="sc-user-mgmt">
  <div class="sc-user-mgmt__header">
    <p class="sc-user-mgmt__hint">
      {t('user.create_accounts_suspend_or_re')}
    </p>
    <Button variant="filled" onclick={openCreate}>
      {#snippet icon()}<Icon icon={icons.add} size={18} />{/snippet}
      {t('user.add_user')}
    </Button>
  </div>

  {#if toggleError}<p class="sc-user-mgmt__error" role="alert">{toggleError}</p>{/if}

  {#if loading}
    <ProgressCircular />
  {:else if loadError}
    <p class="sc-user-mgmt__error">{loadError}</p>
  {:else}
    <ul class="sc-user-mgmt__list">
      {#each users as u (u.id)}
        <li>
          <ListItem>
            {#snippet headline()}
              <span class="sc-user-mgmt__name">{u.display_name || u.name}</span>
            {/snippet}
            {#snippet supporting()}
              {u.name}
            {/snippet}
            {#snippet trailing()}
              <!-- Role and state read as chips, same as the quota beside them,
                   so they belong on the row's own line. On the headline they
                   sat 8px above every other control in the row, because a
                   two-line list item centres its controls on the row and its
                   headline on the first line. -->
              <!-- Both chip columns are reserved rather than shrink-wrapped.
                   The trailing group is right-aligned, so a chip that changes
                   width or disappears moves everything after it: with a mixed
                   list the switch landed on four different columns and the
                   four icon buttons on four more. -->
              <span class="sc-user-mgmt__state">
                {#if u.is_admin}<Chip variant="filter" selected>{t('common.administrator')}</Chip>{/if}
                {#if u.disabled}<Chip variant="assist">{t('user.inactive')}</Chip>{/if}
              </span>
              <span
                class="sc-user-mgmt__switch"
                class:sc-user-mgmt__switch--locked={isLastActiveAdmin(u)}
                title={isLastActiveAdmin(u) ? t('user.last_active_administrator_cannot_deactivated') : undefined}
              >
                <Switch
                  checked={!u.disabled}
                  disabled={isLastActiveAdmin(u)}
                  label={t('user.enable_account', { name: u.name })}
                  showLabel={false}
                  onchange={(checked) => toggleDisabled(u, !checked)}
                />
              </span>
              <button type="button" class="sc-user-mgmt__quota" onclick={() => openQuota(u)}>
                <Chip variant="assist">{quotaLabel(u)}</Chip>
              </button>
              <IconButton label={t('common.manage_folders_visible', { name: u.name })} onclick={() => openGrants(u)}>
                <Icon icon={icons['folder-tree']} size={18} />
              </IconButton>
              <IconButton label={t('oidc.manage_single_sign_connection', { name: u.name })} onclick={() => openOidc(u)}>
                <Icon icon={icons.link} size={18} />
              </IconButton>
              <IconButton
                label={t('common.delete_2', { name: u.name })}
                disabled={togglingId === u.id || isLastActiveAdmin(u)}
                onclick={() => askDelete(u)}
              >
                <Icon icon={icons.delete} size={18} />
              </IconButton>
            {/snippet}
          </ListItem>
        </li>
      {/each}
    </ul>
  {/if}
</section>

<Dialog open={createOpen} title={t('user.add_user')} onclose={closeCreate}>
  <form class="sc-user-mgmt__form" onsubmit={submitCreate}>
    <TextField label={t('user.username')} bind:value={newName} autocomplete="off" autofocus />
    <TextField type="password" label={t('common.password')} bind:value={newPassword} autocomplete="new-password" />
    {#if newPassword}
      <div class="sc-user-mgmt__strength">
        <ProgressLinear
          value={newPasswordStrength.ratio}
          tone={newPasswordStrength.tier}
          label={t('common.password_strength', { level: newPasswordStrength.label })}
        />
        <span class="sc-user-mgmt__strength-label">{newPasswordStrength.label}</span>
      </div>
    {/if}
    <p class="sc-user-mgmt__form-hint">
      {t('user.at_least_characters_turning_smb', { min: MIN_PASSWORD_LEN })}
    </p>
    {#if createError}<p class="sc-user-mgmt__error" role="alert">{createError}</p>{/if}
  </form>
  {#snippet actions()}
    <Button variant="text" onclick={closeCreate} disabled={creating}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={() => submitCreate()} disabled={!newName || !newPassword} loading={creating}>
      {t('common.add')}
    </Button>
  {/snippet}
</Dialog>

<Dialog open={!!deleteTarget} title={t('user.delete_user')} onclose={closeDelete}>
  <p>
    {t('user.permanently_deletes_account_including_its', {
      name: deleteTarget?.name ?? ''
    })}
  </p>
  {#if deleteError}<p class="sc-user-mgmt__error" role="alert">{deleteError}</p>{/if}
  {#snippet actions()}
    <Button variant="text" onclick={closeDelete} disabled={deleting}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={confirmDelete} loading={deleting}>{t('common.delete')}</Button>
  {/snippet}
</Dialog>

<Dialog
  open={!!grantsTarget}
  title={grantsTarget ? t('user.folders_visible', { name: grantsTarget.display_name || grantsTarget.name }) : t('common.folder_permissions')}
  onclose={closeGrants}
>
  {#if grantsTarget}
    <GrantManagementSection
      principal={{ kind: 'user', id: grantsTarget.id }}
      label={grantsTarget.display_name || grantsTarget.name}
    />
  {/if}
  {#snippet actions()}
    <Button variant="text" onclick={closeGrants}>{t('common.close')}</Button>
  {/snippet}
</Dialog>

<UserOidcDialog user={oidcTarget} onclose={closeOidc} />

<Dialog
  open={!!quotaTarget}
  title={quotaTarget ? t('user.storage_quota', { name: quotaTarget.display_name || quotaTarget.name }) : t('user.storage_quota_2')}
  onclose={closeQuota}
>
  <form class="sc-user-mgmt__form" onsubmit={submitQuota}>
    <TextField label={t('user.storage_quota_mb')} bind:value={quotaInput} placeholder={t('user.empty_means_unlimited')} autofocus />
    <p class="sc-user-mgmt__form-hint">
      {#if quotaTarget}{t('user.currently_using', { used: formatBytes(Number(BigInt(quotaTarget.usage_bytes))) })}{/if}
      {t('user.empty_means_unlimited_uploads_copies')}
    </p>
    {#if quotaError}<p class="sc-user-mgmt__error" role="alert">{quotaError}</p>{/if}
  </form>
  {#snippet actions()}
    <Button variant="text" onclick={closeQuota} disabled={quotaSaving}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={() => submitQuota()} loading={quotaSaving}>{t('common.save')}</Button>
  {/snippet}
</Dialog>

<style>
  /* Named container so the header can respond to the space it actually has
   * (this section's own width) rather than the viewport, consistent with
   * how FileTable/FileTree already do compact-width layout switches
   * ( window-size classes via container queries). */
  .sc-user-mgmt {
    container-name: sc-user-mgmt;
    container-type: inline-size;
  }
  .sc-user-mgmt__header {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 24px;
    margin-bottom: 16px;
  }
  /* Compact (<600px): a row that fits the button
   * beside 3-4 lines of body text at 1280px does not have to survive at
   * 390px: stack instead of squeezing the hint into a 6-line, half-width
   * column next to the button. */
  @container sc-user-mgmt (max-width: 599.98px) {
    .sc-user-mgmt__header {
      flex-direction: column;
      align-items: flex-start;
    }
    .sc-user-mgmt__quota {
      inline-size: auto;
    }
    .sc-user-mgmt__list :global(.sc-list-item__trailing) {
      justify-content: flex-start;
      margin-left: 0;
      width: 100%;
    }
  }
  .sc-user-mgmt__hint {
    max-width: 560px;
    margin: 0;
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
  .sc-user-mgmt__list {
    list-style: none;
    margin: 0;
    padding: 0;
    border: 1px solid var(--m3c-outline-variant);
    border-radius: var(--m3-shape-medium);
    overflow: hidden;
  }
  .sc-user-mgmt__list li + li {
    border-top: 1px solid var(--m3c-outline-variant);
  }
  /* The name is the one flex child that should give up space: Korean text
   * has a line-break opportunity after every syllable, so without an
   * explicit min-width:0 + nowrap it doesn't overflow, it *wraps*
   * character-by-character inside whatever sliver of width it's squeezed
   * to (the same defect, worked around here as well as at its root in
   * Chip.svelte, which no longer yields width to a sibling at all). */
  .sc-user-mgmt__name {
    overflow: hidden;
    min-width: 0;
    flex: 1 1 auto;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .sc-user-mgmt__list :global(.sc-list-item__trailing) {
    gap: 8px;
  }
  .sc-user-mgmt__error {
    color: var(--m3c-error);
    @apply --m3-body-small;
  }
  /* Flex, not the default block. The switch inside is inline-level, so a block
     wrapper builds a line box around it and inherits the font's descender
     space: the wrapper came out 39px tall around a 32px control and the switch
     rode 3.5px above every button beside it. */
  .sc-user-mgmt__switch {
    display: flex;
    align-items: center;
  }
  .sc-user-mgmt__switch--locked {
    opacity: 0.5;
    pointer-events: none;
  }
  /* One column each, wide enough for the longest label either can carry:
     "관리자"/"비활성" and a two-sided quota like "45 GB / 50 GB". Both are
     end-aligned so the chip stays against the control that follows it and the
     slack falls on the name's side, where there is room for it. */
  .sc-user-mgmt__state {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    gap: 8px;
    inline-size: 72px;
  }
  .sc-user-mgmt__quota {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    inline-size: 132px;
    border: none;
    background: none;
    padding: 0;
    cursor: pointer;
  }
  .sc-user-mgmt__form {
    display: flex;
    flex-direction: column;
    gap: 16px;
    min-width: min(320px, 80vw);
  }
  .sc-user-mgmt__form-hint {
    margin: 0;
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
  .sc-user-mgmt__strength {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: calc(-1 * 8px);
  }
  .sc-user-mgmt__strength-label {
    flex: 0 0 auto;
    min-width: 48px;
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
</style>

// web/src/lib/ui/admin/UserManagementSection.tsx
import { useMutation, useQuery } from '@tanstack/react-query'
import { useEffect, useMemo, useRef, useState } from 'react'
import { formatBytes, bytesToMb, BYTES_PER_MB } from '../../format/bytes'
import { scorePasswordStrength } from '../../format/password-strength'
import { t } from '../../i18n'
import { ApiError, type AdminUser } from '../../api/client'
import { describeApiError } from '../../api/error-text'
import { adminUserMutation, adminUsersQuery } from '../../query/admin'
import { Button } from '../Button'
import { TextField } from '../TextField'
import { VirtualList } from '../VirtualList'
import { GrantManagementSection } from './GrantManagementSection'
import { UserOidcDialog } from './UserOidcDialog'
import { Icon } from '../Icon'
import './admin.css'

const MIN_PASSWORD_LEN = 10

export function UserManagementSection() {
  const usersQuery = useQuery(adminUsersQuery())
  const users = usersQuery.data ?? []
  const activeAdminCount = useMemo(() => users.filter((user) => user.is_admin && !user.disabled).length, [users])
  const lastActiveAdmin = (user: AdminUser) => user.is_admin && !user.disabled && activeAdminCount <= 1
  const [createOpen, setCreateOpen] = useState(false)
  const [newName, setNewName] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [createValidation, setCreateValidation] = useState<string | null>(null)
  const create = useMutation(adminUserMutation())
  const [deleteTarget, setDeleteTarget] = useState<AdminUser | null>(null)
  const remove = useMutation(adminUserMutation())
  const [quotaTarget, setQuotaTarget] = useState<AdminUser | null>(null)
  const [quotaInput, setQuotaInput] = useState('')
  const [quotaValidation, setQuotaValidation] = useState<string | null>(null)
  const quota = useMutation(adminUserMutation())
  const [passwordTarget, setPasswordTarget] = useState<AdminUser | null>(null)
  const [passwordInput, setPasswordInput] = useState('')
  const [passwordConfirm, setPasswordConfirm] = useState('')
  const [passwordValidation, setPasswordValidation] = useState<string | null>(null)
  const password = useMutation(adminUserMutation())
  const toggle = useMutation(adminUserMutation())
  const [grantsTarget, setGrantsTarget] = useState<AdminUser | null>(null)
  const [oidcTarget, setOidcTarget] = useState<AdminUser | null>(null)
  const togglingId = toggle.isPending && toggle.variables?.kind === 'disable' ? toggle.variables.id : null
  const deleteDialogRef = useRef<HTMLElement | null>(null)
  const grantsDialogRef = useRef<HTMLElement | null>(null)
  const quotaDialogRef = useRef<HTMLElement | null>(null)
  const passwordDialogRef = useRef<HTMLElement | null>(null)
  const createDialogRef = useRef<HTMLElement | null>(null)
  useEffect(() => {
    const element = createDialogRef.current
    if (!element) return
    const close = () => { if (!create.isPending) setCreateOpen(false) }
    element.addEventListener('close', close)
    return () => element.removeEventListener('close', close)
  }, [create.isPending])
  useEffect(() => {
    const element = deleteDialogRef.current
    if (!element) return
    const close = () => { if (!remove.isPending) setDeleteTarget(null) }
    element.addEventListener('close', close)
    return () => element.removeEventListener('close', close)
  }, [remove.isPending])
  useEffect(() => {
    const element = grantsDialogRef.current
    if (!element) return
    const close = () => setGrantsTarget(null)
    element.addEventListener('close', close)
    return () => element.removeEventListener('close', close)
  }, [])
  useEffect(() => {
    const element = quotaDialogRef.current
    if (!element) return
    const close = () => { if (!quota.isPending) setQuotaTarget(null) }
    element.addEventListener('close', close)
    return () => element.removeEventListener('close', close)
  }, [quota.isPending])
  useEffect(() => {
    const element = passwordDialogRef.current
    if (!element) return
    const close = () => { if (!password.isPending) setPasswordTarget(null) }
    element.addEventListener('close', close)
    return () => element.removeEventListener('close', close)
  }, [password.isPending])

  const createError = createValidation ?? (create.error ? createErrorText(create.error) : null)
  const deleteError = remove.error ? userDeleteError(remove.error) : null
  const toggleError = toggle.error ? userToggleError(toggle.error) : null
  const quotaError = quotaValidation ?? (quota.error ? describeApiError(quota.error, t('common.could_not_save')) : null)
  const passwordError = passwordValidation ?? (password.error ? describeApiError(password.error, t('password.could_not_change_password_try')) : null)

  function submitCreate(): void {
    setCreateValidation(null)
    if (newPassword.length < MIN_PASSWORD_LEN) { setCreateValidation(t('user.password_must_at_least_characters', { min: MIN_PASSWORD_LEN })); return }
    if (!newName.trim()) return
    create.mutate({ kind: 'create', name: newName.trim(), password: newPassword }, { onSuccess: (created) => { setCreateOpen(false); setGrantsTarget(created as AdminUser) } })
  }
  function submitDelete(): void {
    if (!deleteTarget) return
    remove.mutate({ kind: 'delete', id: deleteTarget.id }, { onSuccess: () => setDeleteTarget(null) })
  }
  function submitQuota(): void {
    if (!quotaTarget) return
    setQuotaValidation(null)
    const value = quotaInput.trim()
    if (!value) { quota.mutate({ kind: 'quota', id: quotaTarget.id, quotaBytes: null }, { onSuccess: () => setQuotaTarget(null) }); return }
    const mb = Number(value)
    if (!Number.isFinite(mb) || mb <= 0) { setQuotaValidation(t('user.enter_number_greater_than_0')); return }
    quota.mutate({ kind: 'quota', id: quotaTarget.id, quotaBytes: Math.round(mb * BYTES_PER_MB) }, { onSuccess: () => setQuotaTarget(null) })
  }
  function submitPassword(): void {
    if (!passwordTarget) return
    setPasswordValidation(null)
    if (passwordInput.length < MIN_PASSWORD_LEN) { setPasswordValidation(t('user.password_must_at_least_characters', { min: MIN_PASSWORD_LEN })); return }
    if (passwordInput !== passwordConfirm) { setPasswordValidation(t('password.new_passwords_do_not_match')); return }
    password.mutate({ kind: 'password', id: passwordTarget.id, password: passwordInput }, { onSuccess: () => setPasswordTarget(null) })
  }
  return (
    <section className="sc-admin-section sc-user-mgmt">
      <div className="sc-admin-section__header"><p className="sc-admin-section__hint">{t('user.create_accounts_suspend_or_re')}</p><Button icon={<Icon name="add" />} onClick={() => { create.reset(); setCreateValidation(null); setNewName(''); setNewPassword(''); setCreateOpen(true) }}>{t('user.add_user')}</Button></div>
      {toggleError ? <p className="sc-admin-section__error" role="alert">{toggleError}</p> : null}
      {usersQuery.isPending ? <mdui-circular-progress /> : usersQuery.error ? <p className="sc-admin-section__error" role="alert">{describeApiError(usersQuery.error, t('user.could_not_load_user_list'))}</p> : (
        <VirtualList
          className="sc-admin-list"
          items={users}
          itemKey={(user) => user.id}
          estimateSize={80}
          pinnedKeys={[deleteTarget?.id, quotaTarget?.id, passwordTarget?.id, grantsTarget?.id, oidcTarget?.id, togglingId].filter((id): id is number => id != null)}
          renderItem={(user) => {
            const locked = lastActiveAdmin(user)
            return <div className="sc-admin-row"><div className="sc-admin-row__body"><div className="sc-admin-row__title"><span className="sc-admin-row__name">{user.display_name || user.name}</span>{user.is_admin ? <span className="sc-admin-chip">{t('common.administrator')}</span> : null}{user.disabled ? <span className="sc-admin-chip sc-admin-chip--muted">{t('user.inactive')}</span> : null}</div><div className="sc-admin-row__supporting">{user.name}</div></div><mdui-switch checked={!user.disabled} disabled={locked} title={locked ? t('user.last_active_administrator_cannot_deactivated') : undefined} aria-label={t('user.enable_account', { name: user.name })} onChange={() => toggle.mutate({ kind: 'disable', id: user.id, disabled: !user.disabled })} /><button className="sc-admin-chip sc-admin-chip--muted" type="button" onClick={() => { quota.reset(); setQuotaValidation(null); setQuotaInput(user.quota_bytes ? String(bytesToMb(Number(BigInt(user.quota_bytes)))) : ''); setQuotaTarget(user) }}>{quotaLabel(user)}</button><div className="sc-admin-row__actions"><Button variant="text" square ariaLabel={t('common.manage_folders_visible', { name: user.name })} onClick={() => setGrantsTarget(user)}><Icon name="account_tree" /></Button><Button variant="text" square ariaLabel={t('oidc.manage_single_sign_connection', { name: user.name })} onClick={() => setOidcTarget(user)}><Icon name="link" /></Button><Button variant="text" square ariaLabel={t('password.change_password')} onClick={() => { password.reset(); setPasswordValidation(null); setPasswordInput(''); setPasswordConfirm(''); setPasswordTarget(user) }}><Icon name="lock" /></Button><Button variant="text" danger square ariaLabel={t('common.delete_2', { name: user.name })} disabled={locked || togglingId === user.id} onClick={() => { remove.reset(); setDeleteTarget(user) }}><Icon name="delete" /></Button></div></div>
          }}
        />
      )}
      <mdui-dialog ref={createDialogRef} open={createOpen} headline={t('user.add_user')} close-on-esc close-on-overlay-click><form className="sc-admin-form" onSubmit={(event) => { event.preventDefault(); submitCreate() }}><TextField label={t('user.username')} value={newName} autoComplete="off" autoFocus onValueChange={setNewName} /><TextField type="password" label={t('common.password')} value={newPassword} autoComplete="new-password" onValueChange={setNewPassword} />{newPassword ? <div><mdui-linear-progress value={scorePasswordStrength(newPassword).ratio} aria-label={t('common.password_strength', { level: scorePasswordStrength(newPassword).label })} /><span className="sc-admin-section__field-hint">{scorePasswordStrength(newPassword).label}</span></div> : null}<p className="sc-admin-section__field-hint">{t('user.at_least_characters_turning_smb', { min: MIN_PASSWORD_LEN })}</p>{createError ? <p className="sc-admin-section__error" role="alert">{createError}</p> : null}</form><mdui-button slot="action" variant="text" disabled={create.isPending} onClick={() => setCreateOpen(false)}>{t('common.cancel')}</mdui-button><mdui-button slot="action" variant="filled" loading={create.isPending} onClick={submitCreate}>{t('common.add')}</mdui-button></mdui-dialog>
      <mdui-dialog ref={deleteDialogRef} open={!!deleteTarget} headline={t('user.delete_user')} close-on-esc close-on-overlay-click><p>{t('user.permanently_deletes_account_including_its', { name: deleteTarget?.name ?? '' })}</p>{deleteError ? <p className="sc-admin-section__error" role="alert">{deleteError}</p> : null}<mdui-button slot="action" variant="text" disabled={remove.isPending} onClick={() => setDeleteTarget(null)}>{t('common.cancel')}</mdui-button><span slot="action" className="sc-danger"><mdui-button variant="filled" loading={remove.isPending} onClick={submitDelete}>{t('common.delete')}</mdui-button></span></mdui-dialog>
      <mdui-dialog ref={grantsDialogRef} open={!!grantsTarget} headline={grantsTarget ? t('user.folders_visible', { name: grantsTarget.display_name || grantsTarget.name }) : t('common.folder_permissions')} close-on-esc close-on-overlay-click><>{grantsTarget ? <GrantManagementSection principal={{ kind: 'user', id: grantsTarget.id }} label={grantsTarget.display_name || grantsTarget.name} /> : null}</><mdui-button slot="action" variant="text" onClick={() => setGrantsTarget(null)}>{t('common.close')}</mdui-button></mdui-dialog>
      <UserOidcDialog user={oidcTarget} onClose={() => setOidcTarget(null)} />
      <mdui-dialog ref={quotaDialogRef} open={!!quotaTarget} headline={quotaTarget ? t('user.storage_quota', { name: quotaTarget.display_name || quotaTarget.name }) : t('user.storage_quota_2')} close-on-esc close-on-overlay-click><form className="sc-admin-form" onSubmit={(event) => { event.preventDefault(); submitQuota() }}><TextField label={t('user.storage_quota_mb')} placeholder={t('user.empty_means_unlimited')} value={quotaInput} autoFocus onValueChange={setQuotaInput} /><p className="sc-admin-section__field-hint">{quotaTarget ? t('user.currently_using', { used: formatBytes(Number(BigInt(quotaTarget.usage_bytes))) }) : ''}{t('user.empty_means_unlimited_uploads_copies')}</p>{quotaError ? <p className="sc-admin-section__error" role="alert">{quotaError}</p> : null}</form><mdui-button slot="action" variant="text" disabled={quota.isPending} onClick={() => setQuotaTarget(null)}>{t('common.cancel')}</mdui-button><mdui-button slot="action" variant="filled" loading={quota.isPending} onClick={submitQuota}>{t('common.save')}</mdui-button></mdui-dialog>
      <mdui-dialog ref={passwordDialogRef} open={!!passwordTarget} headline={t('password.change_password')} close-on-esc close-on-overlay-click><form className="sc-admin-form" onSubmit={(event) => { event.preventDefault(); submitPassword() }}><TextField type="password" label={t('password.new_password')} value={passwordInput} autoComplete="new-password" autoFocus onValueChange={setPasswordInput} /><TextField type="password" label={t('password.confirm_new_password')} value={passwordConfirm} autoComplete="new-password" onValueChange={setPasswordConfirm} />{passwordInput ? <div><mdui-linear-progress value={scorePasswordStrength(passwordInput).ratio} aria-label={t('password.new_password_strength', { level: scorePasswordStrength(passwordInput).label })} /><span className="sc-admin-section__field-hint">{scorePasswordStrength(passwordInput).label}</span></div> : null}<p className="sc-admin-section__field-hint">{t('password.must_at_least_characters', { min: MIN_PASSWORD_LEN })}</p>{passwordError ? <p className="sc-admin-section__error" role="alert">{passwordError}</p> : null}</form><mdui-button slot="action" variant="text" disabled={password.isPending} onClick={() => setPasswordTarget(null)}>{t('common.cancel')}</mdui-button><mdui-button slot="action" variant="filled" loading={password.isPending} disabled={!passwordInput || passwordInput !== passwordConfirm} onClick={submitPassword}>{t('common.save')}</mdui-button></mdui-dialog>
    </section>
  )
}

function quotaLabel(user: AdminUser): string {
  const used = formatBytes(Number(BigInt(user.usage_bytes)))
  return user.quota_bytes ? `${used} / ${formatBytes(Number(BigInt(user.quota_bytes)))}` : t('user.used', { used })
}
function createErrorText(error: unknown): string {
  if (error instanceof ApiError && error.code === 'fs.conflict') return t('common.name_already_taken')
  if (error instanceof ApiError && error.code === 'auth.weak_password') return t('user.password_must_at_least_characters', { min: error.reasonNumber('min_length') ?? MIN_PASSWORD_LEN })
  return describeApiError(error, t('user.could_not_create_user'))
}
function userToggleError(error: unknown): string { return error instanceof ApiError && error.code === 'admin.last_admin' ? t('user.last_administrator_cannot_deactivated') : describeApiError(error, t('common.could_not_save_change')) }
function userDeleteError(error: unknown): string { return error instanceof ApiError && error.code === 'admin.last_admin' ? t('user.last_administrator_cannot_deleted') : describeApiError(error, t('common.could_not_delete')) }
