// web/src/lib/ui/ConflictDialog.svelte
<script lang="ts">
  // ConflictDialog — If-Match mismatch on move/copy/rename.
  import { t } from '../i18n'
  import Button from './Button.svelte'
  import Dialog from './Dialog.svelte'

  interface Props {
    open: boolean
    name: string
    onclose: () => void
    onkeepboth: () => void
    onoverwrite: () => void
    onskip: () => void
  }
  let { open, name, onclose, onkeepboth, onoverwrite, onskip }: Props = $props()
</script>

<Dialog {open} title={t('conflict.name_already_exists')} onclose={onclose}>
  <p>{t('conflict.already_destination_folder_what_would', { name })}</p>
  {#snippet actions()}
    <Button variant="text" onclick={onskip}>{t('conflict.skip')}</Button>
    <Button variant="outlined" onclick={onkeepboth}>{t('conflict.keep_both')}</Button>
    <Button variant="filled" onclick={onoverwrite}>{t('conflict.overwrite')}</Button>
  {/snippet}
</Dialog>

// frontend/src/features/files/ConflictDialog.tsx
import { Button } from '../../ui/Button'
import { BrowseDialog } from './browse-dialog'
import { useI18n } from '../../hooks/use-i18n'
export function ConflictDialog({
  open,
  name,
  onClose,
  onKeepBoth,
  onOverwrite,
  onSkip
}: {
  open: boolean
  name: string
  onClose: () => void
  onKeepBoth: () => void
  onOverwrite: () => void
  onSkip: () => void
}) {
  const { t } = useI18n()
  return (
    <BrowseDialog
      open={open}
      title={t('conflict.name_already_exists')}
      onClose={onClose}
      actions={
        <>
          <Button variant="text" onClick={onSkip}>
            {t('conflict.skip')}
          </Button>
          <Button variant="outlined" onClick={onKeepBoth}>
            {t('conflict.keep_both')}
          </Button>
          <Button onClick={onOverwrite}>{t('conflict.overwrite')}</Button>
        </>
      }
    >
      <p>{t('conflict.already_destination_folder_what_would', { name })}</p>
    </BrowseDialog>
  )
}
