// web/src/lib/ui/settings/AppPasswordsSection.svelte
<script lang="ts">
  // App passwords: List, issue, and revoke.
  // GET/POST/DELETE /api/auth/app-passwords[/:id].
  import { createMutation, createQuery } from '@tanstack/svelte-query'
  import { ApiError, type AppPasswordInfo } from '../../api/client'
  import { describeApiError } from '../../api/error-text'
  import { formatDateNs, t } from '../../i18n'
  import Button from '../Button.svelte'
  import TextField from '../TextField.svelte'
  import Checkbox from '../Checkbox.svelte'
  import Dialog from '../Dialog.svelte'
  import ListItem from '../ListItem.svelte'
  import IconButton from '../IconButton.svelte'
  import { Icon } from 'm3-svelte'
  import { icons } from '../../icons'
  import Chip from '../Chip.svelte'
  import ProgressCircular from '../ProgressCircular.svelte'
  import { appPasswordsQuery, createAppPasswordMutation, revokeAppPasswordMutation } from '../../query/account'

  const list = createQuery(() => appPasswordsQuery())
  const passwords = $derived(list.data ?? [])

  let createOpen = $state(false)
  let newName = $state('')
  let newReadOnly = $state(false)
  let newCurrent = $state('')
  let issuedToken = $state<string | null>(null)
  let issuedOpen = $state(false)
  let issuedAcknowledged = $state(false)
  let tokenCopyState = $state<'idle' | 'copied' | 'failed'>('idle')
  const create = createMutation(() => createAppPasswordMutation())
  const createError = $derived(
    create.error ? describeApiError(create.error, t('app_password.could_not_create_app_password')) : null
  )

  let revokeTarget = $state<AppPasswordInfo | null>(null)
  const revoke = createMutation(() => revokeAppPasswordMutation())

  let wipeTarget = $state<AppPasswordInfo | null>(null)
  const wipe = createMutation(() => revokeAppPasswordMutation())

  let actionError = $state<string | null>(null)

  /** Whether a credential's expiry has passed. The server writes epoch zero
   *  when a wipe is requested, which is how a wiped device reads as revoked
   *  rather than merely asked. Nanoseconds on the wire, milliseconds here. */
  function isExpired(p: AppPasswordInfo): boolean {
    if (!p.expires_ns) return false
    return Number(p.expires_ns) / 1e6 <= Date.now()
  }

  function openCreate(): void {
    newName = ''
    newReadOnly = false
    newCurrent = ''
    create.reset()
    createOpen = true
  }

  function closeCreate(): void {
    createOpen = false
  }

  function confirmCreate(): void {
    if (!newName.trim() || !newCurrent) return
    create.mutate(
      { name: newName.trim(), currentPassword: newCurrent, scope: newReadOnly ? { readOnly: true } : undefined },
      {
        onSuccess: (res) => {
          issuedToken = res.token
          issuedOpen = true
          issuedAcknowledged = false
          tokenCopyState = 'idle'
          createOpen = false
        }
      }
    )
  }

  function closeIssued(): void {
    if (issuedToken && !issuedAcknowledged) {
      // Keep the one-time value open after Escape/backdrop dismissal attempts.
      issuedOpen = true
      return
    }
    issuedOpen = false
    issuedToken = null
  }

  function acknowledgeIssued(): void {
    issuedAcknowledged = true
    issuedOpen = false
    issuedToken = null
  }

  async function copyToken(): Promise<void> {
    if (!issuedToken) return
    try {
      await navigator.clipboard.writeText(issuedToken)
      tokenCopyState = 'copied'
    } catch {
      tokenCopyState = 'failed'
    }
  }


  function askRevoke(p: AppPasswordInfo): void {
    actionError = null
    revokeTarget = p
  }

  function closeRevoke(): void {
    revokeTarget = null
    actionError = null
  }

  function confirmRevoke(): void {
    if (!revokeTarget) return
    actionError = null
    revoke.mutate(
      { id: revokeTarget.id, wipe: false },
      {
        onSuccess: () => {
          revokeTarget = null
        },
        onError: (err) => {
          // 404 just means it's already gone (e.g. revoked from another
          // tab): refresh the list silently instead of leaving a stale row.
          if (err instanceof ApiError && err.status === 404) {
            revokeTarget = null
            void list.refetch()
          } else {
            actionError = describeApiError(err, t('common.could_not_save_change'))
          }
        }
      }
    )
  }

  function askWipe(p: AppPasswordInfo): void {
    actionError = null
    wipeTarget = p
  }

  function closeWipe(): void {
    wipeTarget = null
    actionError = null
  }

  function confirmWipe(): void {
    if (!wipeTarget) return
    actionError = null
    wipe.mutate(
      { id: wipeTarget.id, wipe: true },
      {
        onSuccess: () => {
          wipeTarget = null
        },
        onError: (err) => {
          // Already gone (revoked from another tab): the device can no
          // longer reach us at all, so there is nothing left to ask it to do.
          if (err instanceof ApiError && err.status === 404) {
            wipeTarget = null
            void list.refetch()
          } else {
            actionError = describeApiError(err, t('common.could_not_save_change'))
          }
        }
      }
    )
  }
</script>

<div class="sc-app-passwords">
  {#if list.isPending}
    <ProgressCircular />
  {:else if list.isError}
    <p class="sc-app-passwords__error">{t('common.could_not_load_list')}</p>
  {:else if passwords.length === 0}
    <p class="sc-app-passwords__empty">{t('app_password.no_app_passwords_issued_yet')}</p>
  {:else}
    <ul class="sc-app-passwords__list">
      {#each passwords as p (p.id)}
        <li>
          <ListItem>
            {#snippet headline()}
              <span class="sc-app-passwords__name">{p.name}</span>
              {#if p.read_only}<Chip variant="filter" selected>{t('common.read_only')}</Chip>{/if}
            {/snippet}
            {#snippet supporting()}
              {t('app_password.issued', { date: formatDateNs(p.created_ns) })}
              {#if p.last_used_ns}- {t('app_password.last_used', { date: formatDateNs(p.last_used_ns) })}{:else}- {t('app_password.never_used')}{/if}
              <!-- A requested wipe revokes the credential in the same
                   statement (the server moves its expiry to the epoch), so a
                   row that said nothing about expiry read as live after the
                   device had already been cut off. -->
              {#if isExpired(p)}- {t('app_password.expired')}{:else if p.expires_ns}- {t('app_password.expires', { date: formatDateNs(p.expires_ns) })}{/if}
            {/snippet}
            {#snippet trailing()}
              <!-- Nothing to ask of a credential that can no longer connect,
                   so the wipe request goes; revoking still clears the row. -->
              {#if !isExpired(p)}
                <IconButton label={t('app_password.wipe', { name: p.name })} onclick={() => askWipe(p)}><Icon icon={icons.warning} size={18} /></IconButton>
              {/if}
              <IconButton label={t('app_password.revoke', { name: p.name })} onclick={() => askRevoke(p)}><Icon icon={icons.delete} size={18} /></IconButton>
            {/snippet}
          </ListItem>
        </li>
      {/each}
    </ul>
  {/if}

  <div class="sc-app-passwords__actions">
    <Button variant="outlined" onclick={openCreate}>
      {#snippet icon()}<Icon icon={icons.add} size={18} />{/snippet}
      {t('app_password.new_app_password')}
    </Button>
  </div>
</div>
<Dialog open={createOpen} title={t('app_password.new_app_password')} onclose={closeCreate}>
  {#if createError}
    <p class="sc-app-passwords__error">{createError}</p>
  {/if}
  <p>{t('app_password.use_one_where_your_account')}</p>
  <TextField
    label={t('common.name')}
    bind:value={newName}
    placeholder={t('app_password.e_g_rclone_backup')}
  />
  <TextField
    type="password"
    label={t('common.current_password')}
    bind:value={newCurrent}
    autocomplete="current-password"
  />
  <Checkbox
    label={t('app_password.read_only_download_only_no')}
    bind:checked={newReadOnly}
  />
  <p class="sc-app-passwords__scope-hint">
    {t('app_password.read_only_recommended_anywhere_only')}
  </p>
  {#snippet actions()}
    <Button variant="text" onclick={closeCreate}>{t('common.cancel')}</Button>
    <Button
      variant="filled"
      disabled={!newName.trim() || !newCurrent}
      loading={create.isPending}
      onclick={confirmCreate}
    >
      {t('common.create')}
    </Button>
  {/snippet}
</Dialog>

<Dialog open={issuedOpen && !!issuedToken} title={t('app_password.app_password_issued')} onclose={closeIssued}>
  <p>
    <Icon icon={icons.warning} size={16} />
    {t('app_password.once_you_close_cannot_shown')}
  </p>
  <div class="sc-app-passwords__token-row">
    <input class="sc-app-passwords__token" readonly value={issuedToken ?? ''} aria-label={t('app_password.app_password_issued')} />
    <Button variant="text" onclick={copyToken}>
      {tokenCopyState === 'copied' ? t('common.copied') : t('common.copy')}
    </Button>
  </div>
  {#if tokenCopyState === 'failed'}
    <p class="sc-app-passwords__copy-feedback" role="alert">{t('app_password.copy_failed')}</p>
  {/if}
  {#snippet actions()}
    <Button variant="filled" onclick={acknowledgeIssued}>{t('app_password.acknowledge_saved')}</Button>
  {/snippet}
</Dialog>

<Dialog open={!!revokeTarget} title={t('app_password.revoke_app_password')} onclose={closeRevoke}>
  <p>
    {t('app_password.everything_using_disconnected_at_once', { name: revokeTarget?.name ?? '' })}
  </p>
  {#if actionError}
    <p class="sc-app-passwords__error" role="alert">{actionError}</p>
  {/if}
  {#snippet actions()}
    <Button variant="text" onclick={closeRevoke}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={confirmRevoke} loading={revoke.isPending}>{t('app_password.revoke_2')}</Button>
  {/snippet}
</Dialog>

<Dialog open={!!wipeTarget} title={t('app_password.wipe_device')} onclose={closeWipe}>
  <p>
    {t('app_password.next_time_that_device_erase', { name: wipeTarget?.name ?? '' })}
  </p>
  {#snippet actions()}
  {#if actionError}
    <p class="sc-app-passwords__error" role="alert">{actionError}</p>
  {/if}
    <Button variant="text" onclick={closeWipe}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={confirmWipe} loading={wipe.isPending}>{t('app_password.wipe_2')}</Button>
  {/snippet}
</Dialog>

<style>
  .sc-app-passwords__list {
    list-style: none;
    margin: 0;
    padding: 0;
    border: 1px solid var(--m3c-outline-variant);
    border-radius: var(--m3-shape-medium);
    overflow: hidden;
  }
  .sc-app-passwords__list li + li {
    border-top: 1px solid var(--m3c-outline-variant);
  }
  /* Same defect as the admin user list: without this, the "Read-only" chip
   * is the one that gets squeezed and wraps syllable-by-syllable instead of
   * the name (which can't shrink below its own content, since it has no
   * CJK break opportunities of its own to give up). Chip.svelte now refuses
   * to shrink at all; this makes the name the side that ellipsizes. */
  .sc-app-passwords__name {
    overflow: hidden;
    min-width: 0;
    flex: 1 1 auto;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .sc-app-passwords__empty,
  .sc-app-passwords__error {
    color: var(--m3c-on-surface-variant);
  }
  .sc-app-passwords__copy-feedback {
    margin: 8px 0 0;
    color: var(--m3c-error);
    @apply --m3-body-small;
  }
  .sc-app-passwords__actions {
    margin-top: 16px;
  }
  .sc-app-passwords__scope-hint {
    margin: 0;
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
  .sc-app-passwords__token-row {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-block: 8px;
  }
  .sc-app-passwords__token {
    flex: 1;
    min-width: 0;
    box-sizing: border-box;
    border: 0;
    padding: 8px 12px;
    border-radius: var(--m3-shape-extra-small);
    background: var(--m3c-surface-container-highest);
    color: var(--m3c-on-surface);
    font: inherit;
    @apply --m3-body-medium;
    overflow-wrap: anywhere;
    user-select: all;
  }
</style>

// web/src/features/settings/AppPasswordsSection.tsx
import { useMutation, useQuery } from '@tanstack/react-query'
import { useComponentState } from '../../lib/store/use-component-state'
import { ApiError, type AppPasswordInfo } from '../../lib/api/client'
import { describeApiError } from '../../lib/api/error-text'
import { formatDateNs } from '../../lib/i18n'
import { useI18n } from '../../lib/i18n/use-i18n'
import { appPasswordsQuery, createAppPasswordMutation, revokeAppPasswordMutation } from '../../lib/query/account'
import { Button } from '../../lib/ui/Button'
import { Switch } from '../../lib/ui/Switch'
import { TextField } from '../../lib/ui/TextField'
import { VirtualList } from '../../lib/ui/VirtualList'
import { SettingsDialog } from './SettingsDialog'

export function AppPasswordsSection() {
  const { t } = useI18n()
  const list = useQuery(appPasswordsQuery())
  const create = useMutation(createAppPasswordMutation())
  const revoke = useMutation(revokeAppPasswordMutation())
  const wipe = useMutation(revokeAppPasswordMutation())
  type AppPasswordState = { createOpen: boolean; newName: string; newCurrent: string; newReadOnly: boolean; issuedToken: string | null; issuedAcknowledged: boolean; tokenCopyState: 'idle' | 'copied' | 'failed'; revokeTarget: AppPasswordInfo | null; wipeTarget: AppPasswordInfo | null; actionError: string | null }
  const [state, setState] = useComponentState<AppPasswordState>({ createOpen: false, newName: '', newCurrent: '', newReadOnly: false, issuedToken: null, issuedAcknowledged: false, tokenCopyState: 'idle', revokeTarget: null, wipeTarget: null, actionError: null })
  const { createOpen, newName, newCurrent, newReadOnly, issuedToken, issuedAcknowledged, tokenCopyState, revokeTarget, wipeTarget, actionError } = state
  const patchState = (patch: Partial<AppPasswordState>): void => setState((current) => ({ ...current, ...patch }))
  const setCreateOpen = (value: boolean): void => patchState({ createOpen: value })
  const setNewName = (value: string): void => patchState({ newName: value })
  const setNewCurrent = (value: string): void => patchState({ newCurrent: value })
  const setNewReadOnly = (value: boolean): void => patchState({ newReadOnly: value })
  const setIssuedToken = (value: string | null): void => patchState({ issuedToken: value })
  const setIssuedAcknowledged = (value: boolean): void => patchState({ issuedAcknowledged: value })
  const setTokenCopyState = (value: AppPasswordState['tokenCopyState']): void => patchState({ tokenCopyState: value })
  const setRevokeTarget = (value: AppPasswordInfo | null): void => patchState({ revokeTarget: value })
  const setWipeTarget = (value: AppPasswordInfo | null): void => patchState({ wipeTarget: value })
  const setActionError = (value: string | null): void => patchState({ actionError: value })

  function isExpired(item: AppPasswordInfo): boolean {
    return item.expires_ns ? Number(item.expires_ns) / 1e6 <= Date.now() : false
  }
  function openCreate(): void {
    setNewName(''); setNewCurrent(''); setNewReadOnly(false); create.reset(); setActionError(null); setCreateOpen(true)
  }
  function confirmCreate(): void {
    if (!newName.trim() || !newCurrent) return
    create.mutate({ name: newName.trim(), currentPassword: newCurrent, scope: newReadOnly ? { readOnly: true } : undefined }, {
      onSuccess: (result) => { setCreateOpen(false); setIssuedToken(result.token); setIssuedAcknowledged(false); setTokenCopyState('idle'); void list.refetch() },
      onError: (error) => setActionError(describeApiError(error, t('app_password.could_not_create_app_password')))
    })
  }
  function closeIssued(): void {
    if (issuedToken && !issuedAcknowledged) return
    setIssuedToken(null)
  }
  function acknowledgeIssued(): void {
    setIssuedAcknowledged(true)
    setIssuedToken(null)
  }
  async function copyToken(): Promise<void> {
    if (!issuedToken) return
    try { await navigator.clipboard.writeText(issuedToken); setTokenCopyState('copied') } catch { setTokenCopyState('failed') }
  }
  function confirmRevoke(): void {
    if (!revokeTarget) return
    setActionError(null)
    revoke.mutate({ id: revokeTarget.id, wipe: false }, { onSuccess: () => setRevokeTarget(null), onError: (error) => { if (error instanceof ApiError && error.status === 404) { setRevokeTarget(null); void list.refetch() } else setActionError(describeApiError(error, t('common.could_not_save_change'))) } })
  }
  function confirmWipe(): void {
    if (!wipeTarget) return
    setActionError(null)
    wipe.mutate({ id: wipeTarget.id, wipe: true }, { onSuccess: () => setWipeTarget(null), onError: (error) => { if (error instanceof ApiError && error.status === 404) { setWipeTarget(null); void list.refetch() } else setActionError(describeApiError(error, t('common.could_not_save_change'))) } })
  }

  return (
    <div className="sc-app-passwords">
      {list.isPending ? <p>{t('common.loading')}</p> : list.isError ? <p className="sc-app-passwords__error">{t('common.could_not_load_list')}</p> : (list.data ?? []).length === 0 ? <p className="sc-app-passwords__empty">{t('app_password.no_app_passwords_issued_yet')}</p> : (
        <VirtualList
          className="sc-app-passwords__list"
          items={list.data ?? []}
          itemKey={(item) => item.id}
          estimateSize={96}
          renderItem={(item) => (
            <>
              <div>
                <strong className="sc-app-passwords__name">{item.name}</strong>
                {item.read_only ? <span className="sc-settings-badge">{t('common.read_only')}</span> : null}
                <p>{t('app_password.issued', { date: formatDateNs(item.created_ns) })} - {item.last_used_ns ? t('app_password.last_used', { date: formatDateNs(item.last_used_ns) }) : t('app_password.never_used')}{isExpired(item) ? ` - ${t('app_password.expired')}` : item.expires_ns ? ` - ${t('app_password.expires', { date: formatDateNs(item.expires_ns) })}` : ''}</p>
              </div>
              <div className="sc-settings-card__buttons">
                {!isExpired(item) ? <Button variant="text" ariaLabel={t('app_password.wipe', { name: item.name })} onClick={() => { setActionError(null); setWipeTarget(item) }}>{t('app_password.wipe_2')}</Button> : null}
                <Button variant="text" ariaLabel={t('app_password.revoke', { name: item.name })} onClick={() => { setActionError(null); setRevokeTarget(item) }}>{t('app_password.revoke_2')}</Button>
              </div>
            </>
          )}
        />
      )}
      <div className="sc-app-passwords__actions"><Button variant="outlined" onClick={openCreate}>{t('app_password.new_app_password')}</Button></div>
      <SettingsDialog open={createOpen} title={t('app_password.new_app_password')} onClose={() => setCreateOpen(false)} actions={<><Button variant="text" onClick={() => setCreateOpen(false)}>{t('common.cancel')}</Button><Button onClick={confirmCreate} disabled={!newName.trim() || !newCurrent} loading={create.isPending}>{t('common.create')}</Button></>}>
        {actionError ? <p className="sc-app-passwords__error" role="alert">{actionError}</p> : null}<p>{t('app_password.use_one_where_your_account')}</p><TextField label={t('common.name')} placeholder={t('app_password.e_g_rclone_backup')} value={newName} onValueChange={setNewName} /><TextField type="password" label={t('common.current_password')} autoComplete="current-password" value={newCurrent} onValueChange={setNewCurrent} /><Switch checked={newReadOnly} label={t('app_password.read_only_download_only_no')} onChange={setNewReadOnly} /><p>{t('app_password.read_only_recommended_anywhere_only')}</p>
      </SettingsDialog>
      <SettingsDialog open={!!issuedToken} title={t('app_password.app_password_issued')} onClose={closeIssued} dismissible={false} actions={<Button onClick={acknowledgeIssued}>{t('app_password.acknowledge_saved')}</Button>}>
        <p>{t('app_password.once_you_close_cannot_shown')}</p><div className="sc-token-row"><input readOnly value={issuedToken ?? ''} aria-label={t('app_password.app_password_issued')} /><Button variant="text" onClick={() => void copyToken()}>{tokenCopyState === 'copied' ? t('common.copied') : t('common.copy')}</Button></div>{tokenCopyState === 'failed' ? <p className="sc-app-passwords__copy-feedback" role="alert">{t('app_password.copy_failed')}</p> : null}
      </SettingsDialog>
      <SettingsDialog open={!!revokeTarget} title={t('app_password.revoke_app_password')} onClose={() => setRevokeTarget(null)} actions={<><Button variant="text" onClick={() => setRevokeTarget(null)}>{t('common.cancel')}</Button><Button onClick={confirmRevoke} loading={revoke.isPending}>{t('app_password.revoke_2')}</Button></>}>
        <p>{t('app_password.everything_using_disconnected_at_once', { name: revokeTarget?.name ?? '' })}</p>{actionError ? <p className="sc-app-passwords__error" role="alert">{actionError}</p> : null}
      </SettingsDialog>
      <SettingsDialog open={!!wipeTarget} title={t('app_password.wipe_device')} onClose={() => setWipeTarget(null)} actions={<><Button variant="text" onClick={() => setWipeTarget(null)}>{t('common.cancel')}</Button><Button onClick={confirmWipe} loading={wipe.isPending}>{t('app_password.wipe_2')}</Button></>}>
        <p>{t('app_password.next_time_that_device_erase', { name: wipeTarget?.name ?? '' })}</p>{actionError ? <p className="sc-app-passwords__error" role="alert">{actionError}</p> : null}
      </SettingsDialog>
    </div>
  )
}
