// web/src/lib/ui/admin/GrantManagementSection.svelte
<script lang="ts">
  // Folder permission management: the only screen that actually operates the
  // product's first requirement (deny by default: users see no folders
  // except the ones an admin explicitly granted). Reachable
  // by picking a user in `UserManagementSection` or a group in
  // `GroupManagementSection` and opening this component: the `principal`
  // prop pins which one, so there's no principal-selection UI inside this
  // screen itself.
  //
  // GET /api/admin/shares, GET/POST /api/admin/grants,
  // PATCH/DELETE /api/admin/grants/{id}.
  //
  // Virtual root: what this creates is an independent
  // rule, not a checkbox in a folder tree. Grant permissions on `Photos/a`
  // and `Photos/b` separately and the user sees two top-level items, `a` and
  // `b`. They never learn `Photos` exists; the hint text beside the subpath
  // input below says so. Showing a folder tree with checkboxes would give
  // the opposite impression: that a real tree exists underneath.
  //
  // Deny beats allow (DENY wins at equal depth):
  // checking the same permission in both allow and deny within one rule
  // still saves as-is: the server doesn't normalize it (see the
  // `admin_grants` test `a_bit_present_in_both_allow_and_deny_round_trips_unmodified`
  // in `go/internal/httpapi/handler`), but deny wins at evaluation time.
  // The table below shows that state plainly, with a warning, rather than
  // hiding it.
  import { createMutation, createQuery } from '@tanstack/svelte-query'
  import { t } from '../../i18n'
  import { ApiError, type AdminGrant, type GrantPermName, type GrantPrincipal } from '../../api/client'
  import { ALL_GRANT_PERMS } from '../../api/client'
  import { describeApiError } from '../../api/error-text'
  import { adminGrantMutation, adminGrantsQuery, adminSharesQuery } from '../../query/admin'
  import Button from '../Button.svelte'
  import Checkbox from '../Checkbox.svelte'
  import Chip from '../Chip.svelte'
  import Dialog from '../Dialog.svelte'
  import { Icon, SelectOutlined } from 'm3-svelte'
  import { icons } from '../../icons'
  import IconButton from '../IconButton.svelte'
  import ListItem from '../ListItem.svelte'
  import ProgressCircular from '../ProgressCircular.svelte'
  import TextField from '../TextField.svelte'

  interface Props {
    /** Who these grants belong to: a user id or a group id, never both. */
    principal: GrantPrincipal
    /** Display name for the hint/dialog copy below: the caller already has
     *  it (`AdminUser.display_name`/`AdminGroup.name`), so this screen
     *  doesn't need its own user-vs-group lookup just to render a label. */
    label: string
  }
  const { principal, label }: Props = $props()

  const PERM_LABEL: Record<GrantPermName, string> = {
    read: t('common.read'),
    write: t('grant.write'),
    create: t('grant.create'),
    delete: t('common.delete'),
    rename: t('grant.rename'),
    move: t('common.move'),
    share: t('common.share_links'),
    download: t('common.download')
  }

  const scope = $derived(principal.kind === 'user' ? { userId: principal.id } : { groupId: principal.id })
  const sharesQuery = createQuery(() => adminSharesQuery())
  const grantsQuery = createQuery(() => adminGrantsQuery(scope))
  const shares = $derived(sharesQuery.data ?? [])
  const grants = $derived(grantsQuery.data ?? [])
  const loading = $derived(sharesQuery.isPending || grantsQuery.isPending)
  const loadError = $derived(
    sharesQuery.error || grantsQuery.error
      ? describeApiError(sharesQuery.error ?? grantsQuery.error, t('grant.could_not_load_permission_list'))
      : null
  )

  function shareName(id: number): string {
    return shares.find((s) => s.id === id)?.name ?? t('grant.share', { id })
  }

  // Permission detail (8 chips × allow/deny) is collapsed by default. At just
  // 12 grants that's 96 chips, doubling the screen's scroll length, and a
  // one-line summary already answers most of the question ("what can this
  // person do in this folder?"): expand only when the exact bit combination
  // matters.
  let expandedIds = $state<Set<number>>(new Set())

  function toggleExpanded(id: number): void {
    const next = new Set(expandedIds)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    expandedIds = next
  }

  /** One-line summary: e.g. "Read - Download", or "Full permissions" when
   *  all 8 bits are on. */
  function allowSummary(g: AdminGrant): string {
    if (g.allow.length === 0) return t('grant.no_permissions_granted')
    if (g.allow.length === ALL_GRANT_PERMS.length) return t('grant.full_permissions')
    return g.allow.map((p) => PERM_LABEL[p]).join(' - ')
  }

  // add folder

  let addOpen = $state(false)
  // m3-svelte's Select is a real `<select>`, so its value is a string; the
  // API takes the numeric share id. '' means "nothing picked yet".
  let addShareId = $state('')
  const shareOptions = $derived(shares.map((s) => ({ value: String(s.id), text: s.name })))
  let addSubpath = $state('')
  let addAllow = $state<Set<GrantPermName>>(new Set(['read', 'download']))
  let addDeny = $state<Set<GrantPermName>>(new Set())
  let addInherit = $state(true)
  let addLabel = $state('')
  let addValidation = $state<string | null>(null)

  const addMut = createMutation(() => adminGrantMutation())
  const adding = $derived(addMut.isPending)
  const addError = $derived.by(() => {
    if (addValidation) return addValidation
    const err = addMut.error
    if (!err) return null
    if (err instanceof ApiError && err.code === 'fs.invalid_name') return t('grant.select_at_least_one_permission')
    if (err instanceof ApiError && err.code === 'fs.not_found') return t('common.share_no_longer_exists')
    return describeApiError(err, t('common.could_not_add_folder'))
  })

  function openAdd(): void {
    addShareId = shares[0] ? String(shares[0].id) : ''
    addSubpath = ''
    addAllow = new Set(['read', 'download'])
    addDeny = new Set()
    addInherit = true
    addLabel = ''
    addValidation = null
    addMut.reset()
    addOpen = true
  }

  function closeAdd(): void {
    if (adding) return
    addOpen = false
  }

  async function submitAdd(): Promise<void> {
    addValidation = null
    if (addShareId === '') {
      addValidation = t('grant.select_share')
      return
    }
    if (addAllow.size === 0 && addDeny.size === 0) {
      addValidation = t('grant.select_at_least_one_permission')
      return
    }
    try {
      await addMut.mutateAsync({
        kind: 'create',
        req: {
          principal,
          share: Number(addShareId),
          subpath: addSubpath.trim(),
          allow: [...addAllow],
          deny: [...addDeny],
          inherit: addInherit,
          label: addLabel.trim() || undefined
        }
      })
      addOpen = false
    } catch {
      // addError above reads the failure straight off addMut.error
    }
  }

  // ── edit folder ──

  let editTarget = $state<AdminGrant | null>(null)
  let editAllow = $state<Set<GrantPermName>>(new Set())
  let editDeny = $state<Set<GrantPermName>>(new Set())
  let editInherit = $state(true)
  let editLabel = $state('')
  let editValidation = $state<string | null>(null)

  const editMut = createMutation(() => adminGrantMutation())
  const editing = $derived(editMut.isPending)
  const editError = $derived.by(() => {
    if (editValidation) return editValidation
    const err = editMut.error
    if (!err) return null
    if (err instanceof ApiError && err.code === 'fs.invalid_name') return t('grant.select_at_least_one_permission')
    return describeApiError(err, t('common.could_not_save_change'))
  })

  function openEdit(g: AdminGrant): void {
    editTarget = g
    editAllow = new Set(g.allow)
    editDeny = new Set(g.deny)
    editInherit = g.inherit
    editLabel = g.label ?? ''
    editValidation = null
    editMut.reset()
  }

  function closeEdit(): void {
    if (editing) return
    editTarget = null
  }

  async function submitEdit(): Promise<void> {
    if (!editTarget) return
    editValidation = null
    if (editAllow.size === 0 && editDeny.size === 0) {
      editValidation = t('grant.select_at_least_one_permission')
      return
    }
    try {
      await editMut.mutateAsync({
        kind: 'update',
        id: editTarget.id,
        patch: {
          allow: [...editAllow],
          deny: [...editDeny],
          inherit: editInherit,
          label: editLabel.trim() || null
        }
      })
      editTarget = null
    } catch {
      // editError above reads the failure straight off editMut.error
    }
  }

  // ── remove folder ──

  let deleteTarget = $state<AdminGrant | null>(null)

  const deleteMut = createMutation(() => adminGrantMutation())
  const deleting = $derived(deleteMut.isPending)
  const deleteError = $derived(deleteMut.error ? describeApiError(deleteMut.error, t('common.could_not_remove')) : null)

  function askDelete(g: AdminGrant): void {
    deleteMut.reset()
    deleteTarget = g
  }

  function closeDelete(): void {
    if (deleting) return
    deleteTarget = null
  }

  async function confirmDelete(): Promise<void> {
    if (!deleteTarget) return
    try {
      await deleteMut.mutateAsync({ kind: 'delete', id: deleteTarget.id })
      deleteTarget = null
    } catch {
      // deleteError above reads the failure straight off deleteMut.error
    }
  }

  function togglePerm(set: Set<GrantPermName>, name: GrantPermName): Set<GrantPermName> {
    const next = new Set(set)
    if (next.has(name)) next.delete(name)
    else next.add(name)
    return next
  }
</script>

<section class="sc-grants">
  <p class="sc-grants__hint">
    <strong>{label}</strong>{t('grant.sees_only_folders_granted_here')}
  </p>

  {#if loading}
    <ProgressCircular />
  {:else if loadError}
    <p class="sc-grants__error">{loadError}</p>
  {:else}
    {#if grants.length === 0}
      <div class="sc-grants__empty">
        <Icon icon={icons['folder-tree']} size={28} />
        <p>{t('grant.no_folders_granted_yet_signing')}</p>
      </div>
    {:else}
      <ul class="sc-grants__list">
        {#each grants as g (g.id)}
          {@const overlap = g.allow.filter((p) => g.deny.includes(p))}
          {@const expanded = expandedIds.has(g.id)}
          <li>
            <ListItem>
              {#snippet headline()}
                <span class="sc-grants__name">{g.label || shareName(g.share)}</span>
                {#if !g.inherit}<Chip variant="assist">{t('grant.path_only')}</Chip>{/if}
              {/snippet}
              {#snippet supporting()}
                <span class="sc-grants__path">{shareName(g.share)}{g.subpath ? ` / ${g.subpath}` : t('grant.root')}</span>
                <span class="sc-grants__summary">
                  {allowSummary(g)}
                  {#if g.deny.length > 0}<span class="sc-grants__summary-deny">
                      - {t('grant.denied', { perms: g.deny.map((p) => PERM_LABEL[p]).join(', ') })}</span>{/if}
                </span>
                {#if overlap.length > 0}
                  <span class="sc-grants__warning">
                    <Icon icon={icons.warning} size={14} />
                    {t('grant.appears_both_allow_deny_so', {
                      perms: overlap.map((p) => PERM_LABEL[p]).join(', ')
                    })}
                  </span>
                {/if}
                {#if expanded}
                  <span class="sc-grants__perms">
                    {#each g.allow as p (p)}<Chip variant="filter" selected>{PERM_LABEL[p]}</Chip>{/each}
                    {#each g.deny as p (p)}<Chip variant="input">{t('grant.denied', { perms: PERM_LABEL[p] })}</Chip>{/each}
                  </span>
                {/if}
              {/snippet}
              {#snippet trailing()}
                <IconButton label={expanded ? t('grant.collapse_permission_details') : t('grant.expand_permission_details')} onclick={() => toggleExpanded(g.id)}>
                  <span class="sc-grants__chevron" class:sc-grants__chevron--open={expanded}>
                    <Icon icon={icons['chevron-right']} size={18} />
                  </span>
                </IconButton>
                <IconButton label={t('common.edit', { name: g.label || shareName(g.share) })} onclick={() => openEdit(g)}>
                  <Icon icon={icons.settings} size={18} />
                </IconButton>
                <IconButton label={t('common.remove', { name: g.label || shareName(g.share) })} onclick={() => askDelete(g)}>
                  <Icon icon={icons.delete} size={18} />
                </IconButton>
              {/snippet}
            </ListItem>
          </li>
        {/each}
      </ul>
    {/if}

    <Button variant="tonal" onclick={openAdd}>
      {#snippet icon()}<Icon icon={icons.add} size={18} />{/snippet}
      {t('common.add_folder')}
    </Button>
  {/if}
</section>

<Dialog open={addOpen} title={t('common.add_folder')} onclose={closeAdd}>
  <form class="sc-grants__form" onsubmit={(e) => (e.preventDefault(), submitAdd())}>
    <SelectOutlined label={t('common.share')} width="100%" options={shareOptions} bind:value={addShareId} />

    <TextField label={t('grant.subpath_leave_empty_whole_share')} bind:value={addSubpath} placeholder={t('grant.e_g_vacation')} autocomplete="off" />
    <p class="sc-grants__field-hint">
      {t('grant.left_empty_whole_share_appears')}
    </p>

    <div class="sc-grants__permgrid">
      <div class="sc-grants__permgrid-header">
        <span></span>
        <span>{t('grant.allow')}</span>
        <span>{t('grant.deny')}</span>
      </div>
      {#each ALL_GRANT_PERMS as p (p)}
        <div class="sc-grants__permgrid-row">
          <span>{PERM_LABEL[p]}</span>
          <Checkbox hideLabel checked={addAllow.has(p)} label={t('grant.allow_2', { perm: PERM_LABEL[p] })} onchange={() => (addAllow = togglePerm(addAllow, p))} />
          <Checkbox hideLabel checked={addDeny.has(p)} label={t('grant.deny_2', { perm: PERM_LABEL[p] })} onchange={() => (addDeny = togglePerm(addDeny, p))} />
        </div>
      {/each}
    </div>

    <Checkbox checked={addInherit} label={t('grant.apply_subfolders')} onchange={(v) => (addInherit = v)} />
    <TextField label={t('grant.display_name_optional')} bind:value={addLabel} placeholder={t('grant.defaults_folder_name')} autocomplete="off" />

    {#if addError}<p class="sc-grants__error" role="alert">{addError}</p>{/if}
  </form>
  {#snippet actions()}
    <Button variant="text" onclick={closeAdd} disabled={adding}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={submitAdd} loading={adding}>{t('common.add')}</Button>
  {/snippet}
</Dialog>

<Dialog open={!!editTarget} title={t('grant.edit_folder_permission')} onclose={closeEdit}>
  {#if editTarget}
    <form class="sc-grants__form" onsubmit={(e) => (e.preventDefault(), submitEdit())}>
      <p class="sc-grants__field-hint">
        {shareName(editTarget.share)}{editTarget.subpath ? ` / ${editTarget.subpath}` : t('grant.root')}
        {t('grant.share_path_cannot_changed_grant')}
      </p>

      <div class="sc-grants__permgrid">
        <div class="sc-grants__permgrid-header">
          <span></span>
          <span>{t('grant.allow')}</span>
          <span>{t('grant.deny')}</span>
        </div>
        {#each ALL_GRANT_PERMS as p (p)}
          <div class="sc-grants__permgrid-row">
            <span>{PERM_LABEL[p]}</span>
            <Checkbox hideLabel checked={editAllow.has(p)} label={t('grant.allow_2', { perm: PERM_LABEL[p] })} onchange={() => (editAllow = togglePerm(editAllow, p))} />
            <Checkbox hideLabel checked={editDeny.has(p)} label={t('grant.deny_2', { perm: PERM_LABEL[p] })} onchange={() => (editDeny = togglePerm(editDeny, p))} />
          </div>
        {/each}
      </div>
      {#if [...editAllow].some((p) => editDeny.has(p))}
        <p class="sc-grants__warning">
          <Icon icon={icons.warning} size={14} />
          {t('grant.permission_listed_both_allow_deny')}
        </p>
      {/if}

      <Checkbox checked={editInherit} label={t('grant.apply_subfolders')} onchange={(v) => (editInherit = v)} />
      <TextField label={t('grant.display_name_optional')} bind:value={editLabel} placeholder={t('grant.defaults_folder_name')} autocomplete="off" />

      {#if editError}<p class="sc-grants__error" role="alert">{editError}</p>{/if}
    </form>
  {/if}
  {#snippet actions()}
    <Button variant="text" onclick={closeEdit} disabled={editing}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={submitEdit} loading={editing}>{t('common.save')}</Button>
  {/snippet}
</Dialog>

<Dialog open={!!deleteTarget} title={t('grant.remove_folder_permission')} onclose={closeDelete}>
  <p>
    {t('grant.access_removed_immediately', {
      name: deleteTarget?.label || (deleteTarget ? shareName(deleteTarget.share) : '')
    })}
    {t('grant.will_not_see_folder_from', { principal: label })}
  </p>
  {#if deleteError}<p class="sc-grants__error" role="alert">{deleteError}</p>{/if}
  {#snippet actions()}
    <Button variant="text" onclick={closeDelete} disabled={deleting}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={confirmDelete} loading={deleting}>{t('common.remove_2')}</Button>
  {/snippet}
</Dialog>

<style>
  .sc-grants {
    display: flex;
    flex-direction: column;
    gap: 16px;
  }
  .sc-grants__hint {
    margin: 0;
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
  .sc-grants__empty {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    padding: 32px 16px;
    color: var(--m3c-on-surface-variant);
    text-align: center;
    border: 1px dashed var(--m3c-outline-variant);
    border-radius: var(--m3-shape-medium);
  }
  .sc-grants__empty p {
    margin: 0;
    @apply --m3-body-medium;
  }
  .sc-grants__list {
    list-style: none;
    margin: 0;
    padding: 0;
    border: 1px solid var(--m3c-outline-variant);
    border-radius: var(--m3-shape-medium);
    overflow: hidden;
  }
  .sc-grants__list li + li {
    border-top: 1px solid var(--m3c-outline-variant);
  }
  .sc-grants__list :global(.sc-list-item) {
    align-items: flex-start;
    padding-block: 8px;
  }
  .sc-grants__list :global(.sc-list-item__supporting) {
    display: flex;
    flex-direction: column;
    gap: 4px;
    margin-top: 4px;
  }
  .sc-grants__name {
    font-weight: 500;
    color: var(--m3c-on-surface);
  }
  .sc-grants__path {
    color: var(--m3c-on-surface-variant);
  }
  .sc-grants__summary {
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
  .sc-grants__summary-deny {
    color: var(--m3c-error);
  }
  .sc-grants__perms {
    display: flex;
    flex-wrap: wrap;
    gap: 4px;
    margin-top: 4px;
  }
  .sc-grants__chevron {
    display: inline-flex;
    transition: transform var(--m3-easing-fast);
  }
  .sc-grants__chevron--open {
    transform: rotate(90deg);
  }
  .sc-grants__warning {
    display: flex;
    align-items: center;
    gap: 4px;
    color: var(--m3c-error);
    @apply --m3-body-small;
  }
  .sc-grants__error {
    margin: 0;
    color: var(--m3c-error);
    @apply --m3-body-small;
  }
  .sc-grants__form {
    display: flex;
    flex-direction: column;
    gap: 16px;
    min-width: min(360px, 80vw);
  }
  .sc-grants__field-hint {
    margin: calc(-1 * 8px) 0 0;
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
  }
  .sc-grants__permgrid {
    display: flex;
    flex-direction: column;
    border: 1px solid var(--m3c-outline-variant);
    border-radius: var(--m3-shape-medium);
    overflow: hidden;
  }
  .sc-grants__permgrid-header,
  .sc-grants__permgrid-row {
    display: grid;
    grid-template-columns: 1fr 64px 64px;
    align-items: center;
    gap: 8px;
    padding: 8px 12px;
  }
  .sc-grants__permgrid-header {
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-small;
    background: var(--m3c-surface-container-highest);
  }
  .sc-grants__permgrid-row :global(.row) {
    justify-content: center;
    width: 100%;
  }
  .sc-grants__permgrid-row + .sc-grants__permgrid-row {
    border-top: 1px solid var(--m3c-outline-variant);
  }
</style>

// frontend/src/features/admin/GrantManagementSection.tsx
import { useMutation, useQuery } from '@tanstack/react-query'
import { useGrantManagementState } from './grant-management-state'
import { ALL_GRANT_PERMS, ApiError, type AdminGrant, type GrantPermName, type GrantPrincipal } from '../../lib/api/client'
import { describeApiError } from '../../lib/api/error-text'
import { adminGrantMutation, adminGrantsQuery, adminSharesQuery } from '../../lib/query/admin'
import { useI18n } from '../../lib/i18n/use-i18n'
import { Button } from '../../lib/ui/Button'
import { Checkbox } from '../../lib/ui/Checkbox'
import { GrantPermissionGrid } from './GrantPermissionGrid'
import { Chip } from '../../lib/ui/Chip'
import { Dialog } from '../../lib/ui/Dialog'
import { Switch } from '../../lib/ui/Switch'
import { Icon } from '../../lib/ui/Icon'
import { IconButton } from '../../lib/ui/IconButton'
import { ListItem } from '../../lib/ui/ListItem'
import { ProgressCircular } from '../../lib/ui/ProgressCircular'
import { Select, type SelectOption } from '../../lib/ui/Select'
import { TextField } from '../../lib/ui/TextField'
import { VirtualList } from '../../lib/ui/VirtualList'
import '../../styles/features/admin/admin.css.ts'

interface GrantManagementSectionProps {
  /** Who these grants belong to: a user id or a group id, never both. */
  principal: GrantPrincipal
  /** Display name used in the hint and delete confirmation copy. */
  label: string
}

type Translate = (key: string, params?: Record<string, string | number>) => string

type PermissionSets = {
  allow: Set<GrantPermName>
  deny: Set<GrantPermName>
}

export function GrantManagementSection({ principal, label }: GrantManagementSectionProps) {
  const { t } = useI18n()
  const permLabel: Record<GrantPermName, string> = {
    read: t('common.read'),
    write: t('grant.write'),
    create: t('grant.create'),
    delete: t('common.delete'),
    rename: t('grant.rename'),
    move: t('common.move'),
    share: t('common.share_links'),
    download: t('common.download')
  }
  const scope = principal.kind === 'user' ? { userId: principal.id } : { groupId: principal.id }
  const sharesQuery = useQuery(adminSharesQuery())
  const grantsQuery = useQuery(adminGrantsQuery(scope))
  const shares = sharesQuery.data ?? []
  const grants = grantsQuery.data ?? []
  const loading = sharesQuery.isPending || grantsQuery.isPending
  const loadError = sharesQuery.error || grantsQuery.error
    ? describeApiError(sharesQuery.error ?? grantsQuery.error, t('grant.could_not_load_permission_list'))
    : null

  const [state, patchState] = useGrantManagementState()
  const { expandedIds, addOpen, addShareId, addSubpath, addAllow, addDeny, addInherit, addLabel, addValidation, editTarget, editAllow, editDeny, editInherit, editLabel, editValidation, deleteTarget } = state
  const setExpandedIds = (value: Set<number> | ((current: Set<number>) => Set<number>)): void => patchState((current) => ({ expandedIds: typeof value === 'function' ? value(current.expandedIds) : value }))
  const setAddOpen = (value: boolean): void => patchState({ addOpen: value })
  const setAddShareId = (value: string): void => patchState({ addShareId: value })
  const setAddSubpath = (value: string): void => patchState({ addSubpath: value })
  const setAddAllow = (value: Set<GrantPermName>): void => patchState({ addAllow: value })
  const setAddDeny = (value: Set<GrantPermName>): void => patchState({ addDeny: value })
  const setAddInherit = (value: boolean): void => patchState({ addInherit: value })
  const setAddLabel = (value: string): void => patchState({ addLabel: value })
  const setAddValidation = (value: string | null): void => patchState({ addValidation: value })
  const setEditTarget = (value: AdminGrant | null): void => patchState({ editTarget: value })
  const setEditAllow = (value: Set<GrantPermName>): void => patchState({ editAllow: value })
  const setEditDeny = (value: Set<GrantPermName>): void => patchState({ editDeny: value })
  const setEditInherit = (value: boolean): void => patchState({ editInherit: value })
  const setEditLabel = (value: string): void => patchState({ editLabel: value })
  const setEditValidation = (value: string | null): void => patchState({ editValidation: value })
  const setDeleteTarget = (value: AdminGrant | null): void => patchState({ deleteTarget: value })
  const addMut = useMutation(adminGrantMutation())
  const editMut = useMutation(adminGrantMutation())
  const deleteMut = useMutation(adminGrantMutation())

  const shareName = (id: number): string => shares.find((share) => share.id === id)?.name ?? t('grant.share', { id })
  const addError = addValidation ?? (addMut.error ? grantError(addMut.error, t('common.could_not_add_folder'), t) : null)
  const editError = editValidation ?? (editMut.error ? grantError(editMut.error, t('common.could_not_save_change'), t) : null)
  const deleteError = deleteMut.error ? describeApiError(deleteMut.error, t('common.could_not_remove')) : null
  const shareOptions: SelectOption[] = [
    { value: '', text: t('grant.select_share'), disabled: true },
    ...shares.map((share) => ({ value: String(share.id), text: share.name }))
  ]

  function toggleExpanded(id: number): void {
    setExpandedIds((current) => {
      const next = new Set(current)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  function allowSummary(grant: AdminGrant): string {
    if (grant.allow.length === 0) return t('grant.no_permissions_granted')
    if (grant.allow.length === ALL_GRANT_PERMS.length) return t('grant.full_permissions')
    return grant.allow.map((permission) => permLabel[permission]).join(' - ')
  }

  function openAdd(): void {
    addMut.reset()
    setAddValidation(null)
    setAddShareId(shares[0] ? String(shares[0].id) : '')
    setAddSubpath('')
    setAddAllow(new Set(['read', 'download']))
    setAddDeny(new Set())
    setAddInherit(true)
    setAddLabel('')
    setAddOpen(true)
  }

  function closeAdd(): void {
    if (!addMut.isPending) setAddOpen(false)
  }

  function submitAdd(): void {
    setAddValidation(null)
    if (!addShareId) {
      setAddValidation(t('grant.select_share'))
      return
    }
    if (addAllow.size === 0 && addDeny.size === 0) {
      setAddValidation(t('grant.select_at_least_one_permission'))
      return
    }
    addMut.mutate(
      {
        kind: 'create',
        req: {
          principal,
          share: Number(addShareId),
          subpath: addSubpath.trim(),
          allow: [...addAllow],
          deny: [...addDeny],
          inherit: addInherit,
          label: addLabel.trim() || undefined
        }
      },
      { onSuccess: () => setAddOpen(false) }
    )
  }

  function openEdit(grant: AdminGrant): void {
    editMut.reset()
    setEditValidation(null)
    setEditTarget(grant)
    setEditAllow(new Set(grant.allow))
    setEditDeny(new Set(grant.deny))
    setEditInherit(grant.inherit)
    setEditLabel(grant.label ?? '')
  }

  function closeEdit(): void {
    if (!editMut.isPending) setEditTarget(null)
  }

  function submitEdit(): void {
    if (!editTarget) return
    setEditValidation(null)
    if (editAllow.size === 0 && editDeny.size === 0) {
      setEditValidation(t('grant.select_at_least_one_permission'))
      return
    }
    editMut.mutate(
      {
        kind: 'update',
        id: editTarget.id,
        patch: {
          allow: [...editAllow],
          deny: [...editDeny],
          inherit: editInherit,
          label: editLabel.trim() || null
        }
      },
      { onSuccess: () => setEditTarget(null) }
    )
  }

  function askDelete(grant: AdminGrant): void {
    deleteMut.reset()
    setDeleteTarget(grant)
  }

  function closeDelete(): void {
    if (!deleteMut.isPending) setDeleteTarget(null)
  }

  function submitDelete(): void {
    if (!deleteTarget) return
    deleteMut.mutate({ kind: 'delete', id: deleteTarget.id }, { onSuccess: () => setDeleteTarget(null) })
  }

  return (
    <>
      <section className="sc-admin-section sc-grants">
        <p className="sc-admin-section-hint">
          <strong>{label}</strong>{t('grant.sees_only_folders_granted_here')}
        </p>
        {loading ? <ProgressCircular /> : loadError ? <p className="sc-admin-section-error" role="alert">{loadError}</p> : (
          <>
            {grants.length === 0 ? (
              <div className="sc-admin-empty">
                <Icon name="account_tree" />
                <p>{t('grant.no_folders_granted_yet_signing')}</p>
              </div>
            ) : (
              <VirtualList
                className="sc-admin-list"
                items={grants}
                itemKey={(grant) => grant.id}
                estimateSize={96}
                pinnedKeys={[editTarget?.id, deleteTarget?.id].filter((id): id is number => id != null)}
                renderItem={(grant) => {
                  const expanded = expandedIds.has(grant.id)
                  const overlap = grant.allow.filter((permission) => grant.deny.includes(permission))
                  const grantName = grant.label || shareName(grant.share)
                  return (
                      <ListItem
                        headline={
                          <>
                            <span className="sc-admin-row-name">{grantName}</span>
                            {!grant.inherit ? <Chip variant="assist">{t('grant.path_only')}</Chip> : null}
                          </>
                        }
                        supporting={
                          <span className="sc-admin-grant-supporting">
                            <span>{shareName(grant.share)}{grant.subpath ? ` / ${grant.subpath}` : t('grant.root')}</span>
                            <span>
                              {allowSummary(grant)}
                              {grant.deny.length > 0 ? <span className="sc-admin-grant-summary-deny"> - {t('grant.denied', { perms: grant.deny.map((permission) => permLabel[permission]).join(', ') })}</span> : null}
                            </span>
                            {overlap.length > 0 ? (
                              <span className="sc-admin-grant-warning">
                                <Icon name="warning" size={14} />
                                {t('grant.appears_both_allow_deny_so', { perms: overlap.map((permission) => permLabel[permission]).join(', ') })}
                              </span>
                            ) : null}
                            {expanded ? (
                              <span className="sc-admin-grant-perms">
                                {grant.allow.map((permission) => <Chip key={`allow-${permission}`} variant="filter" selected>{permLabel[permission]}</Chip>)}
                                {grant.deny.map((permission) => <Chip key={`deny-${permission}`} variant="input">{t('grant.denied', { perms: permLabel[permission] })}</Chip>)}
                              </span>
                            ) : null}
                          </span>
                        }
                        trailing={
                          <span className="sc-admin-row-actions">
                            <IconButton
                              label={expanded ? t('grant.collapse_permission_details') : t('grant.expand_permission_details')}
                              expanded={expanded}
                              onClick={() => toggleExpanded(grant.id)}
                            >
                              <span className={`sc-admin-grant-chevron${expanded ? ' sc-admin-grant-chevron--open' : ''}`}>
                                <Icon name="chevron-right" size={18} />
                              </span>
                            </IconButton>
                            <IconButton label={t('common.edit', { name: grantName })} onClick={() => openEdit(grant)}>
                              <Icon name="settings" size={18} />
                            </IconButton>
                            <span className="sc-danger">
                              <IconButton label={t('common.remove', { name: grantName })} onClick={() => askDelete(grant)}>
                                <Icon name="delete" size={18} />
                              </IconButton>
                            </span>
                          </span>
                        }
                      />
                  )
                }}
              />
            )}
            <Button variant="tonal" icon={<Icon name="add" />} onClick={openAdd}>{t('common.add_folder')}</Button>
          </>
        )}
      </section>

      <Dialog
        open={addOpen}
        title={t('common.add_folder')}
        onClose={closeAdd}
        actions={
          <>
            <Button variant="text" disabled={addMut.isPending} onClick={closeAdd}>{t('common.cancel')}</Button>
            <Button loading={addMut.isPending} onClick={submitAdd}>{t('common.add')}</Button>
          </>
        }
      >
        <form className="sc-admin-form" onSubmit={(event) => { event.preventDefault(); submitAdd() }}>
          <Select label={t('common.share')} options={shareOptions} value={addShareId} required onValueChange={setAddShareId} />
          <TextField label={t('grant.subpath_leave_empty_whole_share')} placeholder={t('grant.e_g_vacation')} value={addSubpath} autoComplete="off" onValueChange={setAddSubpath} />
          <p className="sc-admin-section-field-hint">{t('grant.left_empty_whole_share_appears')}</p>
          <PermissionGrid allow={addAllow} deny={addDeny} setAllow={setAddAllow} setDeny={setAddDeny} permLabel={permLabel} t={t} />
          <Switch checked={addInherit} label={t('grant.apply_subfolders')} onChange={setAddInherit} />
          <TextField label={t('grant.display_name_optional')} placeholder={t('grant.defaults_folder_name')} value={addLabel} autoComplete="off" onValueChange={setAddLabel} />
          {addError ? <p className="sc-admin-section-error" role="alert">{addError}</p> : null}
        </form>
      </Dialog>

      <Dialog
        open={editTarget !== null}
        title={t('grant.edit_folder_permission')}
        onClose={closeEdit}
        actions={
          <>
            <Button variant="text" disabled={editMut.isPending} onClick={closeEdit}>{t('common.cancel')}</Button>
            <Button loading={editMut.isPending} onClick={submitEdit}>{t('common.save')}</Button>
          </>
        }
      >
        {editTarget ? (
          <form className="sc-admin-form" onSubmit={(event) => { event.preventDefault(); submitEdit() }}>
            <p className="sc-admin-section-field-hint">
              {shareName(editTarget.share)}{editTarget.subpath ? ` / ${editTarget.subpath}` : t('grant.root')}{t('grant.share_path_cannot_changed_grant')}
            </p>
            <PermissionGrid allow={editAllow} deny={editDeny} setAllow={setEditAllow} setDeny={setEditDeny} permLabel={permLabel} t={t} />
            {editAllow.size > 0 && [...editAllow].some((permission) => editDeny.has(permission)) ? (
              <p className="sc-admin-grant-warning">
                <Icon name="warning" size={14} />
                {t('grant.permission_listed_both_allow_deny')}
              </p>
            ) : null}
            <Switch checked={editInherit} label={t('grant.apply_subfolders')} onChange={setEditInherit} />
            <TextField label={t('grant.display_name_optional')} placeholder={t('grant.defaults_folder_name')} value={editLabel} autoComplete="off" onValueChange={setEditLabel} />
            {editError ? <p className="sc-admin-section-error" role="alert">{editError}</p> : null}
          </form>
        ) : null}
      </Dialog>

      <Dialog
        open={deleteTarget !== null}
        title={t('grant.remove_folder_permission')}
        onClose={closeDelete}
        actions={
          <>
            <Button variant="text" disabled={deleteMut.isPending} onClick={closeDelete}>{t('common.cancel')}</Button>
            <Button danger loading={deleteMut.isPending} onClick={submitDelete}>{t('common.remove_2')}</Button>
          </>
        }
      >
        <p>
          {t('grant.access_removed_immediately', { name: deleteTarget?.label || (deleteTarget ? shareName(deleteTarget.share) : '') })}{' '}
          {t('grant.will_not_see_folder_from', { principal: label })}
        </p>
        {deleteError ? <p className="sc-admin-section-error" role="alert">{deleteError}</p> : null}
      </Dialog>
    </>
  )
}

function PermissionGrid({ allow, deny, setAllow, setDeny, permLabel, t }: PermissionSets & {
  setAllow: (next: Set<GrantPermName>) => void
  setDeny: (next: Set<GrantPermName>) => void
  permLabel: Record<GrantPermName, string>
  t: Translate
}) {
  return <GrantPermissionGrid allow={allow} deny={deny} setAllow={setAllow} setDeny={setDeny} permLabel={permLabel} t={t} />
}

function togglePermission(set: Set<GrantPermName>, permission: GrantPermName, checked: boolean): Set<GrantPermName> {
  const next = new Set(set)
  if (checked) next.add(permission)
  else next.delete(permission)
  return next
}

function grantError(error: unknown, fallback: string, t: Translate, mapNotFound = true): string {
  if (error instanceof ApiError && error.code === 'fs.invalid_name') return t('grant.select_at_least_one_permission')
  if (mapNotFound && error instanceof ApiError && error.code === 'fs.not_found') return t('common.share_no_longer_exists')
  return describeApiError(error, fallback)
}
