// web/src/lib/ui/settings/TotpSection.svelte
<script lang="ts">
  // Two-factor auth (TOTP): both enabling and
  // disabling require password re-confirmation. Disabling does not require
  // re-login or a password reset: the session stays alive and the modal
  // only asks for one password field.
  import { createMutation, createQuery } from '@tanstack/svelte-query'
  import { t, tp } from '../../i18n'
  import { ApiError } from '../../api/client'
  import { describeApiError } from '../../api/error-text'
  import Button from '../Button.svelte'
  import TextField from '../TextField.svelte'
  import Dialog from '../Dialog.svelte'
  import { Icon } from 'm3-svelte'
  import { icons } from '../../icons'
  import { createSession } from '../../query/session'
  import {
    recoveryCodesQuery,
    reissueRecoveryCodesMutation,
    totpDisableMutation,
    totpEnrollMutation,
    totpSetupMutation
  } from '../../query/account'

  const session = createSession()
  const enabled = $derived(session.data?.user.totp_enabled ?? false)
  /** Whether this account holds a separate SMB-only password. Turning TOTP
   *  off is the exact undo of what made one necessary, so it replaces it,
   *  and a credential the user set is never removed in silence. */
  const smbDedicated = $derived(session.data?.user.smb_credential === 'dedicated')

  // The remaining count reloads itself whenever `enabled` flips: on mount,
  // right after `confirmEnroll`, and again after a reissue, because each of
  // those invalidates this query. Not gated behind a re-confirmation: the
  // count itself isn't a secret from the account's own owner, only the codes
  // are.
  const recovery = createQuery(() => recoveryCodesQuery(enabled))

  // ── enroll flow ──
  let enrollOpen = $state(false)
  let setupSecret = $state('')
  let setupUrl = $state('')
  let enrollPassword = $state('')
  let enrollCode = $state('')
  let secretCopyState = $state<'idle' | 'copied' | 'failed'>('idle')
  let recoveryCodes = $state<string[] | null>(null)
  let recoveryDialogOpen = $state(false)
  let recoveryAcknowledged = $state(false)
  let recoveryCopyState = $state<'idle' | 'copied' | 'failed'>('idle')
  const setup = createMutation(() => totpSetupMutation())
  const enroll = createMutation(() => totpEnrollMutation())
  const enrollError = $derived.by(() => {
    const err = setupSecret ? enroll.error : setup.error
    if (!err) return null
    if (err instanceof ApiError && err.code === 'auth.invalid_credentials') {
      return setupSecret ? t('totp.password_or_verification_code_incorrect') : t('common.incorrect_password')
    }
    return describeApiError(err, setupSecret ? t('totp.could_not_enable_try_again') : t('totp.could_not_start_setup_try'))
  })

  // ── disable flow ──
  let disableOpen = $state(false)
  let disablePassword = $state('')
  const disable = createMutation(() => totpDisableMutation())
  const disableError = $derived.by(() => {
    const err = disable.error
    if (!err) return null
    return err instanceof ApiError && err.code === 'auth.invalid_credentials'
      ? t('common.incorrect_password')
      : describeApiError(err, t('totp.could_not_turn_off_try'))
  })

  // ── recovery codes: reissue ──
  let reissueOpen = $state(false)
  let reissuePassword = $state('')
  const reissue = createMutation(() => reissueRecoveryCodesMutation())
  const reissueError = $derived.by(() => {
    const err = reissue.error
    if (!err) return null
    return err instanceof ApiError && err.code === 'auth.invalid_credentials'
      ? t('common.incorrect_password')
      : describeApiError(err, t('totp.could_not_reissue_them_try'))
  })

  function openReissue(): void {
    reissuePassword = ''
    reissue.reset()
    reissueOpen = true
  }

  function closeReissue(): void {
    reissueOpen = false
    reissuePassword = ''
  }

  function confirmReissue(): void {
    reissue.mutate(reissuePassword, {
      onSuccess: (res) => {
        recoveryCodes = res.recovery_codes
        recoveryDialogOpen = true
        recoveryAcknowledged = false
        recoveryCopyState = 'idle'
        reissueOpen = false
      }
    })
  }

  /** Opens the dialog without a secret in it.
   *
   *  The secret is minted by `POST /account/totp/setup`, which re-confirms the
   *  password: enrolling a second factor is a credential change, and the
   *  server will not hand one out on a session cookie alone. Asking for it
   *  before the field existed answered 400 every time, so the dialog opened on
   *  "could not start setup" and the factor could never be turned on. */
  function startEnroll(): void {
    enrollPassword = ''
    enrollCode = ''
    setupSecret = ''
    setupUrl = ''
    secretCopyState = 'idle'
    setup.reset()
    enroll.reset()
    enrollOpen = true
  }

  /** Mints the secret against the password just typed. */
  function revealSecret(): void {
    if (!enrollPassword || setupSecret) return
    setup.mutate(enrollPassword, {
      onSuccess: (res) => {
        setupSecret = res.secret
        setupUrl = res.uri
      }
    })
  }

  function closeEnroll(): void {
    enrollOpen = false
    setupSecret = ''
    setupUrl = ''
    enrollPassword = ''
    enrollCode = ''
  }

  function confirmEnroll(): void {
    enroll.mutate(
      { password: enrollPassword, secret: setupSecret, code: enrollCode },
      {
        onSuccess: (res) => {
          recoveryCodes = res.recovery_codes
          recoveryDialogOpen = true
          recoveryAcknowledged = false
          recoveryCopyState = 'idle'
          // The setup response is a one-time secret too. Once enrollment has
          // succeeded, the authenticator has it and this component must not
          // retain another plaintext copy.
          setupSecret = ''
          setupUrl = ''
          enrollPassword = ''
          enrollCode = ''
          enrollOpen = false
        }
      }
    )
  }

  function closeRecoveryCodes(): void {
    if (recoveryCodes && !recoveryAcknowledged) {
      // Escape and backdrop dismissal must not discard the only copy of these
      // one-use values. Keep the dialog open until the explicit acknowledgment.
      recoveryDialogOpen = true
      return
    }
    recoveryDialogOpen = false
    recoveryCodes = null
  }

  function acknowledgeRecoveryCodes(): void {
    recoveryAcknowledged = true
    recoveryDialogOpen = false
    recoveryCodes = null
  }
  function openDisable(): void {
    disablePassword = ''
    disable.reset()
    disableOpen = true
  }

  function closeDisable(): void {
    disableOpen = false
    disablePassword = ''
  }

  function confirmDisable(): void {
    disable.mutate(disablePassword, {
      onSuccess: () => {
        disableOpen = false
        // No announcement about the file-sharing password: the server does
        // not report one, and it could not. Enrolling or disconnecting
        // changes what is published, never what is stored, and a single
        // row holds the hash whether it came from the account password or
        // a separate one, so the two are indistinguishable afterwards. The
        // sharing section below reads the real state.
      }
    })
  }

  async function copySecret(): Promise<void> {
    try {
      await navigator.clipboard.writeText(setupSecret)
      secretCopyState = 'copied'
    } catch {
      secretCopyState = 'failed'
    }
  }

  async function copyRecoveryCodes(): Promise<void> {
    if (!recoveryCodes) return
    try {
      await navigator.clipboard.writeText(recoveryCodes.join('\n'))
      recoveryCopyState = 'copied'
    } catch {
      recoveryCopyState = 'failed'
    }
  }
</script>

<div class="sc-totp">
  <div class="sc-totp__status">
    <span class="sc-totp__badge" class:sc-totp__badge--on={enabled}>
      {enabled ? t('totp.on') : t('totp.off')}
    </span>
    {#if enabled}
      <Button variant="outlined" onclick={openDisable}>{t('totp.turn_off_two_factor_authentication')}</Button>
    {:else}
      <Button variant="filled" onclick={startEnroll}>{t('totp.set_up_two_factor_authentication')}</Button>
    {/if}
  </div>

  {#if enabled}
    <div class="sc-totp__recovery">
      {#if recovery.data}
        <p class="sc-totp__recovery-count" class:sc-totp__recovery-count--low={recovery.data.remaining <= 3}>
          {#if recovery.data.remaining <= 3}<Icon icon={icons.warning} size={16} />{/if}
          {tp('totp.recovery_codes_left', recovery.data.remaining)}
          {#if recovery.data.remaining <= 3}
            {t('totp.running_low_reissue_them_now')}
          {/if}
        </p>
      {/if}
      <Button variant="outlined" onclick={openReissue}>{t('totp.reissue_recovery_codes')}</Button>
    </div>
  {/if}
</div>

<Dialog open={enrollOpen} title={t('totp.set_up_two_factor_authentication')} onclose={closeEnroll}>
  <!-- The password comes first because the server mints the secret against
       it: enrolling a factor is a credential change, not a read. -->
  <TextField
    type="password"
    label={t('common.current_password')}
    bind:value={enrollPassword}
    autocomplete="current-password"
  />
  {#if setup.isPending}
    <p>{t('totp.loading_setup_details')}</p>
  {:else if setupSecret}
    <p>{t('totp.add_key_below_authenticator_app')}</p>
    <div class="sc-totp__secret-row">
      <input
        class="sc-totp__secret"
        readonly
        value={setupSecret}
        aria-label={t('totp.add_key_below_authenticator_app')}
      />
      <Button variant="text" onclick={copySecret}>
        {secretCopyState === 'copied' ? t('common.copied') : t('common.copy')}
      </Button>
    </div>
    {#if secretCopyState === 'failed'}
      <p class="sc-totp__copy-feedback" role="alert">{t('totp.copy_secret_failed')}</p>
    {/if}
    <p class="sc-totp__url">{setupUrl}</p>
    <TextField label={t('totp.6_digit_code')} bind:value={enrollCode} error={enrollError} />
  {:else if enrollError}
    <p class="sc-totp__smb-warning">{enrollError}</p>
  {/if}
  {#snippet actions()}
    <Button variant="text" onclick={closeEnroll}>{t('common.cancel')}</Button>
    {#if setupSecret}
      <Button
        variant="filled"
        disabled={enrollCode.length !== 6}
        loading={enroll.isPending}
        onclick={confirmEnroll}
      >
        {t('totp.enable')}
      </Button>
    {:else}
      <Button variant="filled" disabled={!enrollPassword} loading={setup.isPending} onclick={revealSecret}>
        {t('common.continue')}
      </Button>
    {/if}
  {/snippet}
</Dialog>

<Dialog open={disableOpen} title={t('totp.turn_off_two_factor_authentication_2')} onclose={closeDisable}>
  <p>{t('totp.enter_your_current_password_continue')}</p>
  {#if smbDedicated}
    <p class="sc-totp__smb-warning">{t('smb.dedicated_will_be_replaced')}</p>
  {:else}
    <p class="sc-totp__smb-warning">{t('smb.remove_reverts_to_account')}</p>
  {/if}
  <TextField
    type="password"
    label={t('common.current_password')}
    bind:value={disablePassword}
    error={disableError}
    autocomplete="current-password"
  />
  {#snippet actions()}
    <Button variant="text" onclick={closeDisable}>{t('common.cancel')}</Button>
    <Button variant="filled" disabled={!disablePassword} loading={disable.isPending} onclick={confirmDisable}>
      {t('totp.turn_off')}
    </Button>
  {/snippet}
</Dialog>

<Dialog open={reissueOpen} title={t('totp.reissue_recovery_codes_2')} onclose={closeReissue}>
  <p class="sc-totp__reissue-warning">
    <Icon icon={icons.warning} size={16} />
    {t('totp.reissuing_invalidates_all_10_recovery')} <strong>{t('totp.at_once')}</strong>{t('totp.cannot_undone_new_codes_shown')}
  </p>
  <TextField
    type="password"
    label={t('common.current_password')}
    bind:value={reissuePassword}
    error={reissueError}
    autocomplete="current-password"
  />
  {#snippet actions()}
    <Button variant="text" onclick={closeReissue}>{t('common.cancel')}</Button>
    <Button variant="filled" disabled={!reissuePassword} loading={reissue.isPending} onclick={confirmReissue}>
      {t('totp.reissue')}
    </Button>
  {/snippet}
</Dialog>

<Dialog open={recoveryDialogOpen && !!recoveryCodes} title={t('totp.recovery_codes')} onclose={closeRecoveryCodes}>
  <p>
    <Icon icon={icons.warning} size={16} />
    {t('totp.each_code_works_once_save')}
  </p>
  <ul class="sc-totp__codes">
    {#each recoveryCodes ?? [] as code (code)}
      <li>
        <input class="sc-totp__code" readonly value={code} aria-label={t('totp.recovery_codes')} />
      </li>
    {/each}
  </ul>
  <Button variant="outlined" onclick={copyRecoveryCodes}>
    {recoveryCopyState === 'copied' ? t('common.copied') : t('totp.copy_codes')}
  </Button>
  {#if recoveryCopyState === 'failed'}
    <p class="sc-totp__copy-feedback" role="alert">{t('totp.copy_codes_failed')}</p>
  {/if}
  {#snippet actions()}
    <Button variant="filled" onclick={acknowledgeRecoveryCodes}>{t('totp.acknowledge_codes_saved')}</Button>
  {/snippet}
</Dialog>

<style>
  .sc-totp__status {
    display: flex;
    align-items: center;
    gap: 16px;
  }
  .sc-totp__badge {
    display: inline-flex;
    align-items: center;
    height: 32px;
    padding-inline: 12px;
    border-radius: var(--m3-shape-full);
    background: var(--m3c-surface-container-highest);
    color: var(--m3c-on-surface-variant);
    @apply --m3-label-large;
  }
  .sc-totp__badge--on {
    background: var(--m3c-primary-container);
    color: var(--m3c-on-primary-container);
  }
  .sc-totp__recovery {
    display: flex;
    align-items: center;
    gap: 16px;
    margin-top: 16px;
  }
  .sc-totp__recovery-count {
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 0;
    color: var(--m3c-on-surface-variant);
    @apply --m3-body-medium;
  }
  .sc-totp__recovery-count--low {
    color: var(--m3c-error);
    font-weight: 500;
  }
  .sc-totp__smb-warning {
    padding: 12px;
    border-radius: var(--m3-shape-extra-small);
    background: var(--m3c-surface-container-highest);
    color: var(--m3c-on-surface);
    @apply --m3-body-medium;
  }
  .sc-totp__reissue-warning {
    display: flex;
    align-items: flex-start;
    gap: 8px;
    padding: 12px;
    border-radius: var(--m3-shape-extra-small);
    background: var(--m3c-error-container);
    color: var(--m3c-on-error-container);
    @apply --m3-body-medium;
  }
  .sc-totp__secret-row {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-block: 8px;
  }
  .sc-totp__secret {
    flex: 1;
    min-width: 0;
    box-sizing: border-box;
    border: 0;
    padding: 8px 12px;
    border-radius: var(--m3-shape-extra-small);
    background: var(--m3c-surface-container-highest);
    color: var(--m3c-on-surface);
    font: inherit;
    @apply --m3-body-medium;
    letter-spacing: 0.05em;
    user-select: all;
  }
  .sc-totp__copy-feedback {
    margin: 8px 0 0;
    color: var(--m3c-error);
    @apply --m3-body-small;
  }
  .sc-totp__url {
    overflow-wrap: anywhere;
    @apply --m3-body-small;
    color: var(--m3c-on-surface-variant);
  }
  .sc-totp__codes {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
    padding: 0;
    margin: 16px 0;
    list-style: none;
  }
  .sc-totp__code {
    display: block;
    width: 100%;
    box-sizing: border-box;
    border: 0;
    padding: 8px 12px;
    border-radius: var(--m3-shape-extra-small);
    background: var(--m3c-surface-container-highest);
    color: var(--m3c-on-surface);
    font: inherit;
    text-align: center;
    user-select: all;
  }
</style>

// frontend/src/features/settings/TotpSection.tsx
import { useMutation, useQuery } from '@tanstack/react-query'
import { useComponentState } from '../../lib/store/use-component-state'
import { ApiError } from '../../lib/api/client'
import { describeApiError } from '../../lib/api/error-text'
import { tp } from '../../lib/i18n'
import { useI18n } from '../../lib/i18n/use-i18n'
import { recoveryCodesQuery, reissueRecoveryCodesMutation, totpDisableMutation, totpEnrollMutation, totpSetupMutation } from '../../lib/query/account'
import { sessionQuery } from '../../lib/query/session'
import { Button } from '../../lib/ui/Button'
import { TextField } from '../../lib/ui/TextField'
import { SettingsDialog } from './SettingsDialog'

export function TotpSection() {
  const { t } = useI18n()
  const session = useQuery(sessionQuery())
  const enabled = session.data?.user.totp_enabled ?? false
  const smbDedicated = session.data?.user.smb_credential === 'dedicated'
  const recovery = useQuery(recoveryCodesQuery(enabled))
  const setup = useMutation(totpSetupMutation())
  const enroll = useMutation(totpEnrollMutation())
  const disable = useMutation(totpDisableMutation())
  const reissue = useMutation(reissueRecoveryCodesMutation())
  type TotpState = {
    enrollOpen: boolean
    enrollPassword: string
    setupSecret: string
    setupUrl: string
    enrollCode: string
    secretCopyState: 'idle' | 'copied' | 'failed'
    recoveryCodes: string[] | null
    recoveryAcknowledged: boolean
    recoveryCopyState: 'idle' | 'copied' | 'failed'
    disableOpen: boolean
    disablePassword: string
    reissueOpen: boolean
    reissuePassword: string
  }
  const [state, setState] = useComponentState<TotpState>({ enrollOpen: false, enrollPassword: '', setupSecret: '', setupUrl: '', enrollCode: '', secretCopyState: 'idle', recoveryCodes: null, recoveryAcknowledged: false, recoveryCopyState: 'idle', disableOpen: false, disablePassword: '', reissueOpen: false, reissuePassword: '' })
  const { enrollOpen, enrollPassword, setupSecret, setupUrl, enrollCode, secretCopyState, recoveryCodes, recoveryAcknowledged, recoveryCopyState, disableOpen, disablePassword, reissueOpen, reissuePassword } = state
  const update = <K extends keyof TotpState>(key: K, value: TotpState[K]): void => setState((current) => ({ ...current, [key]: value }))
  const setEnrollOpen = (value: boolean): void => update('enrollOpen', value)
  const setEnrollPassword = (value: string): void => update('enrollPassword', value)
  const setSetupSecret = (value: string): void => update('setupSecret', value)
  const setSetupUrl = (value: string): void => update('setupUrl', value)
  const setEnrollCode = (value: string): void => update('enrollCode', value)
  const setSecretCopyState = (value: TotpState['secretCopyState']): void => update('secretCopyState', value)
  const setRecoveryCodes = (value: string[] | null): void => update('recoveryCodes', value)
  const setRecoveryAcknowledged = (value: boolean): void => update('recoveryAcknowledged', value)
  const setRecoveryCopyState = (value: TotpState['recoveryCopyState']): void => update('recoveryCopyState', value)
  const setDisableOpen = (value: boolean): void => update('disableOpen', value)
  const setDisablePassword = (value: string): void => update('disablePassword', value)
  const setReissueOpen = (value: boolean): void => update('reissueOpen', value)
  const setReissuePassword = (value: string): void => update('reissuePassword', value)

  const enrollError = setup.error || enroll.error
  const enrollErrorText = enrollError ? (enrollError instanceof ApiError && enrollError.code === 'auth.invalid_credentials' ? (setupSecret ? t('totp.password_or_verification_code_incorrect') : t('common.incorrect_password')) : describeApiError(enrollError, setupSecret ? t('totp.could_not_enable_try_again') : t('totp.could_not_start_setup_try'))) : null
  const disableError = disable.error ? (disable.error instanceof ApiError && disable.error.code === 'auth.invalid_credentials' ? t('common.incorrect_password') : describeApiError(disable.error, t('totp.could_not_turn_off_try'))) : null
  const reissueError = reissue.error ? (reissue.error instanceof ApiError && reissue.error.code === 'auth.invalid_credentials' ? t('common.incorrect_password') : describeApiError(reissue.error, t('totp.could_not_reissue_them_try'))) : null

  function openEnroll(): void {
    setEnrollPassword(''); setSetupSecret(''); setSetupUrl(''); setEnrollCode(''); setSecretCopyState('idle'); setup.reset(); enroll.reset(); setEnrollOpen(true)
  }
  function revealSecret(): void {
    if (!enrollPassword || setupSecret) return
    setup.mutate(enrollPassword, { onSuccess: (result) => { setSetupSecret(result.secret); setSetupUrl(result.uri) } })
  }
  function confirmEnroll(): void {
    enroll.mutate({ password: enrollPassword, secret: setupSecret, code: enrollCode }, { onSuccess: (result) => { setRecoveryCodes(result.recovery_codes); setRecoveryAcknowledged(false); setRecoveryCopyState('idle'); setEnrollOpen(false); setSetupSecret(''); setSetupUrl(''); setEnrollPassword(''); setEnrollCode(''); void session.refetch() } })
  }
  function closeEnroll(): void {
    if (setup.isPending || enroll.isPending) return
    setEnrollOpen(false); setSetupSecret(''); setSetupUrl(''); setEnrollPassword(''); setEnrollCode('')
  }
  async function copySecret(): Promise<void> {
    try { await navigator.clipboard.writeText(setupSecret); setSecretCopyState('copied') } catch { setSecretCopyState('failed') }
  }
  async function copyRecoveryCodes(): Promise<void> {
    if (!recoveryCodes) return
    try { await navigator.clipboard.writeText(recoveryCodes.join('\n')); setRecoveryCopyState('copied') } catch { setRecoveryCopyState('failed') }
  }
  function closeRecoveryCodes(): void {
    if (recoveryCodes && !recoveryAcknowledged) return
    setRecoveryCodes(null)
  }
  function acknowledgeRecoveryCodes(): void {
    setRecoveryAcknowledged(true); setRecoveryCodes(null)
  }
  function openDisable(): void { setDisablePassword(''); disable.reset(); setDisableOpen(true) }
  function confirmDisable(): void { disable.mutate(disablePassword, { onSuccess: () => { setDisableOpen(false); setDisablePassword(''); void session.refetch() } }) }
  function openReissue(): void { setReissuePassword(''); reissue.reset(); setReissueOpen(true) }
  function confirmReissue(): void { reissue.mutate(reissuePassword, { onSuccess: (result) => { setRecoveryCodes(result.recovery_codes); setRecoveryAcknowledged(false); setRecoveryCopyState('idle'); setReissueOpen(false); setReissuePassword('') } }) }

  return (
    <div className="sc-totp">
      <div className="sc-totp__status"><span className={enabled ? 'sc-totp__badge sc-totp__badge--on' : 'sc-totp__badge'}>{enabled ? t('totp.on') : t('totp.off')}</span>{enabled ? <Button variant="outlined" onClick={openDisable}>{t('totp.turn_off_two_factor_authentication')}</Button> : <Button onClick={openEnroll}>{t('totp.set_up_two_factor_authentication')}</Button>}</div>
      {enabled ? <div className="sc-totp__recovery">{recovery.data ? <p className={recovery.data.remaining <= 3 ? 'sc-totp__recovery-count sc-totp__recovery-count--low' : 'sc-totp__recovery-count'}>{tp('totp.recovery_codes_left', recovery.data.remaining)}{recovery.data.remaining <= 3 ? ` ${t('totp.running_low_reissue_them_now')}` : ''}</p> : null}<Button variant="outlined" onClick={openReissue}>{t('totp.reissue_recovery_codes')}</Button></div> : null}
      <SettingsDialog open={enrollOpen} title={t('totp.set_up_two_factor_authentication')} onClose={closeEnroll} actions={<><Button variant="text" onClick={closeEnroll} disabled={setup.isPending || enroll.isPending}>{t('common.cancel')}</Button><Button onClick={setupSecret ? confirmEnroll : revealSecret} disabled={setupSecret ? enrollCode.length !== 6 : !enrollPassword} loading={setup.isPending || enroll.isPending}>{setupSecret ? t('totp.enable') : t('common.continue')}</Button></>}>
        <TextField type="password" label={t('common.current_password')} value={enrollPassword} autoComplete="current-password" onValueChange={setEnrollPassword} />
        {setup.isPending ? <p>{t('totp.loading_setup_details')}</p> : null}
        {setupSecret ? <><p>{t('totp.add_key_below_authenticator_app')}</p><div className="sc-totp__secret-row"><input className="sc-totp__secret" readOnly value={setupSecret} aria-label={t('totp.add_key_below_authenticator_app')} /><Button variant="text" onClick={() => void copySecret()}>{secretCopyState === 'copied' ? t('common.copied') : t('common.copy')}</Button></div>{secretCopyState === 'failed' ? <p className="sc-totp__copy-feedback" role="alert">{t('totp.copy_secret_failed')}</p> : null}<p className="sc-totp__url">{setupUrl}</p><TextField label={t('totp.6_digit_code')} value={enrollCode} error={enrollErrorText} onValueChange={setEnrollCode} /></> : enrollErrorText ? <p className="sc-totp__smb-warning" role="alert">{enrollErrorText}</p> : null}
      </SettingsDialog>
      <SettingsDialog open={disableOpen} title={t('totp.turn_off_two_factor_authentication_2')} onClose={() => { if (!disable.isPending) setDisableOpen(false) }} actions={<><Button variant="text" onClick={() => setDisableOpen(false)} disabled={disable.isPending}>{t('common.cancel')}</Button><Button onClick={confirmDisable} disabled={!disablePassword} loading={disable.isPending}>{t('totp.turn_off')}</Button></>}>
        <p>{t('totp.enter_your_current_password_continue')}</p>{smbDedicated ? <p className="sc-totp__smb-warning">{t('smb.dedicated_will_be_replaced')}</p> : <p className="sc-totp__smb-warning">{t('smb.remove_reverts_to_account')}</p>}<TextField type="password" label={t('common.current_password')} value={disablePassword} error={disableError} onValueChange={setDisablePassword} />
      </SettingsDialog>
      <SettingsDialog open={reissueOpen} title={t('totp.reissue_recovery_codes_2')} onClose={() => { if (!reissue.isPending) setReissueOpen(false) }} actions={<><Button variant="text" onClick={() => setReissueOpen(false)} disabled={reissue.isPending}>{t('common.cancel')}</Button><Button onClick={confirmReissue} disabled={!reissuePassword} loading={reissue.isPending}>{t('totp.reissue')}</Button></>}>
        <p>{t('totp.reissuing_invalidates_all_10_recovery')} <strong>{t('totp.at_once')}</strong>{t('totp.cannot_undone_new_codes_shown')}</p><TextField type="password" label={t('common.current_password')} value={reissuePassword} error={reissueError} onValueChange={setReissuePassword} />
      </SettingsDialog>
      <SettingsDialog open={!!recoveryCodes} title={t('totp.recovery_codes')} onClose={closeRecoveryCodes} dismissible={false} actions={<Button onClick={acknowledgeRecoveryCodes}>{t('totp.acknowledge_codes_saved')}</Button>}>
        <p>{t('totp.each_code_works_once_save')}</p><ul className="sc-totp__codes">{(recoveryCodes ?? []).map((code) => <li key={code}><input className="sc-totp__code" readOnly value={code} aria-label={t('totp.recovery_codes')} /></li>)}</ul><Button variant="outlined" onClick={() => void copyRecoveryCodes()}>{recoveryCopyState === 'copied' ? t('common.copied') : t('totp.copy_codes')}</Button>{recoveryCopyState === 'failed' ? <p className="sc-totp__copy-feedback" role="alert">{t('totp.copy_codes_failed')}</p> : null}
      </SettingsDialog>
    </div>
  )
}
