// web/src/lib/ui/FileGrid.tsx
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react'
import type { KeyboardEvent, MouseEvent as ReactMouseEvent, PointerEvent } from 'react'
import type { Entry, Perms } from '../api/types'
import { formatEntrySize } from '../format/entry-size'
import { useI18n } from '../i18n/use-i18n'
import { useStore } from '../store/use-store'
import { selection } from '../store/selection.store'
import { ui } from '../store/ui.store'
import { view } from '../store/view.store'
import { computeScaleMapping, computeWindow, rowIndexToScrollTop } from '../virtual/windowing'
import { cellPos, sectionRows, verticalTarget } from '../virtual/grid-sections'
import { indicesInRect, type Rect } from './marquee'
import { isVideoFile } from './media-utils'
import { Thumbnail } from './Thumbnail'
import { useFileActivation } from './FileRow'
import { Icon } from './Icon'
import './browse-ui.css'

export interface FileGridProps {
  entries: readonly Entry[]
  total: number
  dirs: number
  loading: boolean
  loadingMore: boolean
  requestMore: () => void
  perms: Perms
  onOpen: (entry: Entry) => void
  onContextMenu: (entry: Entry, event: ReactMouseEvent) => void
  menuFor?: string | null
  onRename?: () => void
  onDelete?: () => void
  onSearchFocus?: () => void
  encrypted?: boolean
}
export interface FileGridHandle { focusEntry: (name: string) => boolean; entriesInRect: (rect: Rect) => Entry[] }

export const FileGrid = forwardRef<FileGridHandle, FileGridProps>(function FileGrid({ entries, total, dirs, loading, loadingMore, requestMore, onOpen, onContextMenu, menuFor, onRename, onDelete, onSearchFocus, encrypted = false }, ref) {
  const { t } = useI18n()
  const compact = useStore(ui, (state) => state.compact)
  const density = useStore(view, (state) => state.density)
  const names = useStore(selection, (state) => state.names)
  const focused = useStore(selection, (state) => state.focused)
  const viewport = useRef<HTMLDivElement>(null)
  const folderEl = useRef<HTMLDivElement>(null)
  const fileEl = useRef<HTMLDivElement>(null)
  const [metrics, setMetrics] = useState({ width: 0, scroll: 0, height: 0, foldersTop: 0, filesTop: 0 })
  const resizeObserverRef = useRef<ResizeObserver | null>(null)
  const card = density === 'compact' ? { w: 192, folderH: 44, fileH: 176, gap: 8 } : density === 'spacious' ? { w: 256, folderH: 60, fileH: 244, gap: 16 } : { w: 224, folderH: 52, fileH: 208, gap: 12 }
  const availableW = Math.max(card.w, metrics.width - 32)
  const columns = Math.max(1, Math.floor((availableW + card.gap) / (card.w + card.gap)))
  const cardW = Math.max(120, Math.floor((availableW - (columns - 1) * card.gap) / columns))
  const folderCount = Math.min(dirs, total)
  const fileCount = Math.max(0, total - folderCount)
  const folderRows = sectionRows(folderCount, columns)
  const fileRows = sectionRows(fileCount, columns)
  const folderRowH = card.folderH + card.gap
  const fileRowH = card.fileH + card.gap
  const folderWin = computeWindow({ scrollTop: Math.max(0, metrics.scroll - metrics.foldersTop), viewportHeight: metrics.height, rowHeight: folderRowH, itemCount: folderRows, overscan: 3 })
  const fileWin = computeWindow({ scrollTop: Math.max(0, metrics.scroll - metrics.filesTop), viewportHeight: metrics.height, rowHeight: fileRowH, itemCount: fileRows, overscan: 3 })

  const update = () => {
    if (!viewport.current) return
    const scroll = window.scrollY
    setMetrics({
      width: viewport.current.clientWidth,
      scroll,
      height: window.visualViewport?.height ?? window.innerHeight,
      foldersTop: folderEl.current ? folderEl.current.getBoundingClientRect().top + scroll : 0,
      filesTop: fileEl.current ? fileEl.current.getBoundingClientRect().top + scroll : 0
    })
  }
  useEffect(() => {
    update()
    window.addEventListener('scroll', update, { passive: true })
    window.addEventListener('resize', update)
    window.visualViewport?.addEventListener('resize', update)
    const element = viewport.current
    if (element && typeof ResizeObserver !== 'undefined') {
      const observer = new ResizeObserver(update)
      resizeObserverRef.current = observer
      observer.observe(element)
    }
    return () => {
      window.removeEventListener('scroll', update)
      window.removeEventListener('resize', update)
      window.visualViewport?.removeEventListener('resize', update)
      resizeObserverRef.current?.disconnect()
      resizeObserverRef.current = null
    }
  }, [entries, density, total])

  useEffect(() => {
    if (!loadingMore && Math.max(folderWin.end * columns, folderCount + fileWin.end * columns) > entries.length) requestMore()
  }, [folderWin.end, fileWin.end, columns, folderCount, entries.length, loadingMore, requestMore])

  const loadedNames = useMemo(() => entries.map((entry) => entry.name), [entries])
  const focusSnapshot = useRef<{ names: string[]; focusedName: string | null }>({ names: [], focusedName: null })
  const focusedName = focused === null ? null : entries[focused]?.name ?? null
  useEffect(() => {
    const namesNow = entries.map((entry) => entry.name)
    const previous = focusSnapshot.current
    const overlap = Math.min(previous.names.length, namesNow.length)
    const reordered = overlap > 0 && previous.names.slice(0, overlap).some((name, index) => namesNow[index] !== name)
    if (reordered && previous.focusedName) {
      const next = namesNow.indexOf(previous.focusedName)
      if (next >= 0 && next !== focused) selection.focus(next)
    }
    focusSnapshot.current = { names: namesNow, focusedName: reordered && previous.focusedName && namesNow.includes(previous.focusedName) ? previous.focusedName : focusedName }
  }, [entries, focused, focusedName])

  const domId = (name: string) => `sc-grid-cell-${encodeURIComponent(name).replace(/%/g, '_')}`
  const scrollIntoView = (index: number) => {
    const p = cellPos(index, folderCount, columns)
    const rowH = p.section === 0 ? folderRowH : fileRowH
    const rowCount = p.section === 0 ? folderRows : fileRows
    const top = (p.section === 0 ? metrics.foldersTop : metrics.filesTop) + rowIndexToScrollTop(p.row, computeScaleMapping(rowCount, rowH), rowH)
    const bottom = top + rowH
    if (top < window.scrollY) window.scrollTo({ top })
    else if (bottom > window.scrollY + metrics.height) window.scrollTo({ top: bottom - metrics.height })
  }

  const openMenuForFocused = () => {
    if (focused === null) return
    const entry = entries[focused]
    const element = entry ? document.getElementById(domId(entry.name)) : null
    if (!entry || !element) return
    const box = element.getBoundingClientRect()
    onContextMenu(entry, new window.MouseEvent('contextmenu', { clientX: Math.round(box.left + box.width / 2), clientY: Math.round(box.top + box.height / 2) }) as unknown as ReactMouseEvent)
  }

  useImperativeHandle(ref, () => ({
    focusEntry(name) {
      const index = entries.findIndex((entry) => entry.name === name)
      if (index < 0) return false
      selection.only(name, index)
      viewport.current?.focus()
      scrollIntoView(index)
      return true
    },
    entriesInRect(rect) {
      const left = (viewport.current?.getBoundingClientRect().left ?? 0) + window.scrollX + 16
      const common = { left, columnPitch: cardW + card.gap, cellWidth: cardW, columns }
      const hits = [
        ...indicesInRect(rect, { ...common, top: (folderEl.current?.getBoundingClientRect().top ?? 0) + window.scrollY, rowHeight: folderRowH, cellHeight: card.folderH, startIndex: 0, count: folderCount }),
        ...indicesInRect(rect, { ...common, top: (fileEl.current?.getBoundingClientRect().top ?? 0) + window.scrollY, rowHeight: fileRowH, cellHeight: card.fileH, startIndex: folderCount, count: fileCount })
      ]
      return hits.map((index) => entries[index]).filter((entry): entry is Entry => Boolean(entry))
    }
  }), [entries, folderCount, fileCount, columns, cardW, card, folderRowH, fileRowH, metrics])

  const moveFocus = (delta: number, extend: boolean) => {
    const next = focused === null ? (delta < 0 ? total - 1 : 0) : Math.min(Math.max(focused + delta, 0), total - 1)
    selection.focus(next)
    const name = entries[next]?.name
    if (extend && name) selection.range(loadedNames, name)
    scrollIntoView(next)
  }
  const activation = useFileActivation((entry, index, event) => {
    viewport.current?.focus()
    if (event.shiftKey) selection.range(loadedNames, entry.name)
    else if (event.ctrlKey || event.metaKey) selection.toggle(entry.name, index)
    else selection.only(entry.name, index)
  }, onOpen)

  const keyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    activation.cancel()
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault()
      if (focused === null) moveFocus(0, event.shiftKey)
      else {
        const next = verticalTarget(focused, event.key === 'ArrowDown' ? 1 : -1, folderCount, total, columns)
        moveFocus(next - focused, event.shiftKey)
      }
      return
    }
    if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
      event.preventDefault()
      moveFocus(focused === null ? 0 : event.key === 'ArrowRight' ? 1 : -1, event.shiftKey)
      return
    }
    if (event.key === ' ') { event.preventDefault(); if (focused !== null && entries[focused]) selection.toggle(entries[focused].name, focused); return }
    if ((event.key === 'a' || event.key === 'A') && (event.ctrlKey || event.metaKey)) { event.preventDefault(); selection.all(loadedNames); return }
    if (event.key === 'Enter' && focused !== null && entries[focused]) { onOpen(entries[focused]); return }
    if (event.key === 'ContextMenu' || (event.key === 'F10' && event.shiftKey)) { event.preventDefault(); openMenuForFocused(); return }
    if (event.key === 'F2') { event.preventDefault(); onRename?.(); return }
    if (event.key === 'Delete') { event.preventDefault(); onDelete?.(); return }
    if (event.key === '/') { event.preventDefault(); onSearchFocus?.(); return }
    if (event.key === 'Escape' && names.size) { event.preventDefault(); selection.clear() }
  }

  const cardElement = (entry: Entry | undefined, index: number, isFolder: boolean, col: number) => {
    if (!entry) return <div key={`skeleton-${index}`} className={`sc-file-grid__card sc-file-grid__card--${isFolder ? 'folder' : 'file'} sc-file-grid__skeleton`} style={{ width: cardW }} aria-busy="true"><span className="sc-file-grid__skeleton-line" />{!isFolder ? <span className="sc-file-grid__skeleton-block" /> : null}</div>
    const selected = names.has(entry.name)
    const focusedCard = focusedName === entry.name
    const icon = entry.kind === 'dir' ? 'folder' : isVideoFile(entry.name) ? 'video' : entry.preview?.available ? 'image' : 'file'
    const cancelControlPointer = (event: PointerEvent) => {
      event.stopPropagation()
      activation.cancel()
    }
    return (
      <div id={domId(entry.name)} key={entry.path} className={`sc-file-grid__card sc-file-grid__card--${isFolder ? 'folder' : 'file'}${selected ? ' sc-file-grid__card--selected' : ''}${focusedCard ? ' sc-file-grid__card--focused' : ''}`} role="gridcell" aria-colindex={col + 1} aria-selected={selected} style={{ width: cardW }} {...activation.handlers(entry, index)} onContextMenu={(event) => { activation.cancel(); event.preventDefault(); event.stopPropagation(); onContextMenu(entry, event) }}>
        {isFolder ? (
          <>
            <span className="sc-file-grid__check sc-touch-target" onClick={(event) => { event.stopPropagation(); activation.cancel(); selection.toggle(entry.name, index) }} onPointerDown={cancelControlPointer} onPointerUp={(event) => event.stopPropagation()} onDoubleClick={(event) => event.stopPropagation()}><mdui-checkbox checked={selected} tabIndex={-1}><span className="sc-sr-only">{t('common.select', { name: entry.name })}</span></mdui-checkbox></span>
            <span className="sc-file-grid__type"><Icon name="folder" /></span>
            <span className="sc-file-grid__name"><bdi>{entry.name}</bdi></span>
            {entry.confusable ? <span className="sc-file-grid__badge" title={t('common.look_alike_characters')}><Icon name="warning" /></span> : null}
            <button type="button" className="sc-file-grid__kebab" tabIndex={-1} aria-expanded={menuFor === entry.name} aria-label={t('grid.more_actions', { name: entry.name })} onClick={(event) => { event.stopPropagation(); activation.cancel(); onContextMenu(entry, event) }} onPointerDown={cancelControlPointer} onPointerUp={(event) => event.stopPropagation()} onDoubleClick={(event) => event.stopPropagation()}><Icon name="more-vert" size={18} /></button>
          </>
        ) : (
          <>
            <div className="sc-file-grid__head">
              <span className="sc-file-grid__check sc-touch-target" onClick={(event) => { event.stopPropagation(); activation.cancel(); selection.toggle(entry.name, index) }} onPointerDown={cancelControlPointer} onPointerUp={(event) => event.stopPropagation()} onDoubleClick={(event) => event.stopPropagation()}><mdui-checkbox checked={selected} tabIndex={-1}><span className="sc-sr-only">{t('common.select', { name: entry.name })}</span></mdui-checkbox></span>
              <span className="sc-file-grid__name"><bdi>{entry.name}</bdi></span>
              {entry.confusable ? <span className="sc-file-grid__badge" title={t('common.look_alike_characters')}><Icon name="warning" /></span> : null}
              <button type="button" className="sc-file-grid__kebab" tabIndex={-1} aria-expanded={menuFor === entry.name} aria-label={t('grid.more_actions', { name: entry.name })} onClick={(event) => { event.stopPropagation(); activation.cancel(); onContextMenu(entry, event) }} onPointerDown={cancelControlPointer} onPointerUp={(event) => event.stopPropagation()} onDoubleClick={(event) => event.stopPropagation()}><Icon name="more-vert" size={18} /></button>
            </div>
            <div className="sc-file-grid__thumb"><Thumbnail entry={entry} dim={512} fallback={icon} iconSize={40} /></div>
            <span className="sc-file-grid__meta">{formatEntrySize(entry.size, encrypted)}</span>
          </>
        )}
      </div>
    )
  }

  const renderSection = (isFolder: boolean) => {
    const start = isFolder ? folderWin.start : fileWin.start
    const end = isFolder ? folderWin.end : fileWin.end
    const count = isFolder ? folderCount : fileCount
    const offset = isFolder ? 0 : folderCount
    return Array.from({ length: Math.max(0, end - start) }, (_, r) => {
      const row = start + r
      return <div key={`${isFolder ? 'd' : 'f'}-${row}`} className="sc-file-grid__row" role="row" aria-rowindex={(isFolder ? row : folderRows + row) + 1} style={{ height: isFolder ? card.folderH : card.fileH, gap: card.gap, paddingBottom: card.gap }}>{Array.from({ length: columns }, (_, col) => { const index = offset + row * columns + col; return index < offset + count ? cardElement(entries[index], index, isFolder, col) : null })}</div>
    })
  }

  const active = focusedName && document.getElementById(domId(focusedName)) ? domId(focusedName) : undefined
  return (
    <div ref={viewport} data-density={density} className={`sc-file-grid${compact ? ' sc-file-grid--reserve-bar' : ''}${names.size ? ' sc-file-grid--reserve-selection' : ''}`} style={{ touchAction: 'manipulation' }} role="grid" aria-multiselectable="true" aria-rowcount={folderRows + fileRows} aria-colcount={columns} aria-label={t('grid.file_grid')} aria-activedescendant={active} aria-busy={loadingMore} tabIndex={0} onKeyDown={keyDown} onPointerDown={(event) => { if (!(event.target as HTMLElement).closest('[aria-selected]')) activation.cancel() }} onContextMenu={activation.cancel}>
      {total === 0 && !loading ? <p className="sc-file-grid__empty">{t('common.folder_empty')}</p> : <>
        {folderCount > 0 ? <><p className="sc-file-grid__group" aria-hidden="true">{t('grid.folders')}</p><div ref={folderEl} className="sc-file-grid__section" role="rowgroup" aria-label={t('grid.folders')} style={{ height: folderWin.totalHeight }}><div className="sc-file-grid__window" style={{ transform: `translate3d(0,${folderWin.padTop}px,0)` }}>{renderSection(true)}</div></div></> : null}
        {fileCount > 0 ? <><p className="sc-file-grid__group" aria-hidden="true">{t('grid.files')}</p><div ref={fileEl} className="sc-file-grid__section" role="rowgroup" aria-label={t('grid.files')} style={{ height: fileWin.totalHeight }}><div className="sc-file-grid__window" style={{ transform: `translate3d(0,${fileWin.padTop}px,0)` }}>{renderSection(false)}</div></div></> : null}
      </>}
    </div>
  )
})

// web/src/lib/ui/FileGrid.svelte
<script lang="ts">
  // FileGrid.svelte — virtual-scrolled thumbnail/icon grid view.
  // lists `FileGrid` alongside `FileTable` in the
  // app-specific component inventory; §5 says the grid view "uses the same
  // technique with a fixed cell size" as the virtualized table. This reuses
  // `computeWindow` (built for 1D rows) by treating each *visual grid row* of
  // `columns` cells as one "row" of the windowing maths — `rowHeight` becomes
  // the cell's height, `itemCount` becomes the number of grid rows, and each
  // rendered grid row is expanded back into up to `columns` file cells.
  //
  // Same accessibility contract as FileTable: one tab stop (`tabindex=0` on
  // the grid container), `aria-activedescendant` tracks the "virtually
  // focused" cell, and per-cell tabindex is intentionally never given
  // (a 100k-entry directory cannot have 100k tab stops).
  import { t } from '../i18n'
  import type { Entry } from '../api/client'
  import type { BrowseState } from '../state/browse.svelte'
  import { uiState } from '../state/ui.svelte'
  import { formatBytes } from '../format/bytes'
  import {
    computeScaleMapping,
    computeWindow,
    documentScrollTop,
    effectiveViewportHeight,
    rowIndexToScrollTop
  } from '../virtual/windowing'
  import { Checkbox, Icon } from 'm3-svelte'
  import { icons, type IconName } from '../icons'

  interface Props {
    browse: BrowseState
    onopen: (entry: Entry) => void
    oncontextmenu: (entry: Entry, e: MouseEvent) => void
    onrename?: () => void
    ondelete?: () => void
    onsearchfocus?: () => void
  }

  let { browse, onopen, oncontextmenu, onrename, ondelete, onsearchfocus }: Props = $props()

  // 4px-grid cell sizes, keyed by the same density the toolbar's "density"
  // control already drives for FileTable's row height.
  const CELL = $derived(
    { compact: { w: 96, h: 112 }, comfortable: { w: 116, h: 136 }, spacious: { w: 140, h: 160 } }[browse.density]
  )
  const CELL_GAP = 8 // 8px
  const OVERSCAN = 3 // grid rows, not individual cells

  // Document-scroll migration: see the matching comment block in
  // FileTable.svelte for the full "why" (the short version: a browser only
  // collapses its chrome when the document scrolls, and this element used to
  // be its own `overflow: auto` box, which is exactly what prevented that).
  // `viewportW` stays a real `bind:clientWidth` -- this element still has a
  // genuine, bounded *width* (that never changed); only its height became
  // content-driven instead of viewport-bounded, which is why only the
  // height-derived numbers (`scrollTop`/`viewportH`) move to window/
  // visualViewport reads below.
  let viewportEl: HTMLDivElement | undefined = $state()
  let viewportW = $state(0)
  let viewportDocumentTop = $state(0)
  let scrollTop = $state(0)
  let viewportH = $state(0)

  function measure(): void {
    if (!viewportEl) return
    viewportDocumentTop = viewportEl.getBoundingClientRect().top + window.scrollY
    scrollTop = documentScrollTop(window.scrollY, viewportDocumentTop)
    viewportH = effectiveViewportHeight(window.visualViewport?.height, window.innerHeight)
  }

  $effect(() => {
    window.addEventListener('scroll', measure, { passive: true })
    window.addEventListener('resize', measure)
    window.visualViewport?.addEventListener('resize', measure)
    return () => {
      window.removeEventListener('scroll', measure)
      window.removeEventListener('resize', measure)
      window.visualViewport?.removeEventListener('resize', measure)
    }
  })

  $effect(() => {
    // Re-measure on mount and whenever the directory changes -- see
    // FileTable.svelte's identical effect for why (content above this
    // element can change height between folders without a scroll/resize
    // event of its own).
    browse.path
    measure()
  })

  const columns = $derived(Math.max(1, Math.floor((viewportW + CELL_GAP) / (CELL.w + CELL_GAP))))
  const cellRowHeight = $derived(CELL.h + CELL_GAP)
  const gridRowCount = $derived(browse.total > 0 ? Math.ceil(browse.total / columns) : 0)

  const win = $derived(
    computeWindow({
      scrollTop,
      viewportHeight: viewportH,
      rowHeight: cellRowHeight,
      itemCount: gridRowCount,
      overscan: OVERSCAN
    })
  )

  interface Cell {
    index: number
    entry: Entry | undefined
  }
  interface GridRow {
    key: string
    cells: Cell[]
  }
  const rows = $derived.by((): GridRow[] => {
    const out: GridRow[] = []
    for (let r = win.start; r < win.end; r++) {
      const cells: Cell[] = []
      const base = r * columns
      for (let c = 0; c < columns; c++) {
        const index = base + c
        if (index >= browse.total) break
        cells.push({ index, entry: browse.rowAt(index) })
      }
      out.push({ key: `sc-grid-row-${r}`, cells })
    }
    return out
  })

  function domId(name: string): string {
    return `sc-grid-cell-${encodeURIComponent(name).replace(/%/g, '_')}`
  }

  $effect(() => {
    // Same debounced-window contract as FileTable — only the visible grid
    // rows' worth of entries are requested, translated back into a flat
    // index range.
    browse.scheduleWindow(win.start * columns, Math.min(browse.total, win.end * columns))
  })

  function scrollRowIntoView(gridRow: number): void {
    if (!viewportEl) return
    // See FileTable.svelte's `scrollRowIntoView` for why this scrolls the
    // window (document coordinates) instead of `viewportEl.scrollTop` (this
    // element isn't a scroll container anymore).
    const mapping = computeScaleMapping(gridRowCount, cellRowHeight)
    const rowTop = rowIndexToScrollTop(gridRow, mapping, cellRowHeight)
    const rowBottom = rowIndexToScrollTop(gridRow + 1, mapping, cellRowHeight)
    if (rowTop < scrollTop) {
      window.scrollTo({ top: viewportDocumentTop + rowTop })
    } else if (rowBottom > scrollTop + viewportH) {
      window.scrollTo({ top: viewportDocumentTop + rowBottom - viewportH })
    }
  }

  function onCellClick(e: MouseEvent, entry: Entry): void {
    if (e.shiftKey) {
      browse.selectRangeTo(entry)
      return
    }
    if (e.ctrlKey || e.metaKey) {
      browse.toggle(entry)
      return
    }
    // See FileTable.svelte's `onRowClick` for why compact width branches
    // here: no modifier key exists on a tap, so a plain tap has to open
    // (nothing selected) or extend the selection (already in selection
    // mode) instead of always replacing it down to one item.
    if (uiState.compact) {
      if (browse.selection.size > 0) browse.toggle(entry)
      else onopen(entry)
      return
    }
    browse.selectOnly(entry)
  }

  // Same reasoning as FileRow.svelte's checkbox: a plain click/tap on the
  // cell (shift/ctrl aside) runs `selectOnly`, so without an independent
  // toggle target a touch user has no way to build a multi-selection at
  // all -- there is no modifier key to hold on a phone. FileGrid never had a
  // checkbox before (unlike FileRow); this is the same fix applied to the
  // view that was missing the affordance entirely, not just the wiring.
  function onCheckboxClick(e: MouseEvent, entry: Entry): void {
    e.stopPropagation()
    browse.toggle(entry)
  }

  function onKeydown(e: KeyboardEvent): void {
    if (browse.total === 0) return

    switch (e.key) {
      case 'ArrowDown':
      case 'ArrowUp': {
        e.preventDefault()
        browse.moveFocus(e.key === 'ArrowDown' ? columns : -columns, e.shiftKey)
        scrollRowIntoView(Math.floor((browse.focusedIndex ?? 0) / columns))
        break
      }
      case 'ArrowRight':
      case 'ArrowLeft': {
        e.preventDefault()
        browse.moveFocus(e.key === 'ArrowRight' ? 1 : -1, e.shiftKey)
        scrollRowIntoView(Math.floor((browse.focusedIndex ?? 0) / columns))
        break
      }
      case ' ': {
        e.preventDefault()
        if (browse.focusedIndex !== null) {
          const entry = browse.rowAt(browse.focusedIndex)
          if (entry) browse.toggle(entry)
        }
        break
      }
      case 'a':
      case 'A':
        if (e.ctrlKey || e.metaKey) {
          e.preventDefault()
          browse.selectAll()
        }
        break
      case 'Enter': {
        const entry = browse.focusedIndex !== null ? browse.rowAt(browse.focusedIndex) : undefined
        if (entry) onopen(entry)
        break
      }
      case 'F2':
        e.preventDefault()
        onrename?.()
        break
      case 'Delete':
        e.preventDefault()
        ondelete?.()
        break
      case '/':
        e.preventDefault()
        onsearchfocus?.()
        break
    }
  }

  const activeDescendant = $derived(
    browse.focusedName && rows.some((r) => r.cells.some((c) => c.entry?.name === browse.focusedName))
      ? domId(browse.focusedName)
      : undefined
  )

  function iconName(entry: Entry): IconName {
    return entry.kind === 'dir' ? 'folder' : entry.preview?.available ? 'image' : 'file'
  }
</script>

<div
  bind:this={viewportEl}
  bind:clientWidth={viewportW}
  class="sc-file-grid"
  class:sc-file-grid--reserve-bar={uiState.compact}
  data-density={browse.density}
  role="grid"
  aria-multiselectable="true"
  aria-rowcount={gridRowCount}
  aria-colcount={columns}
  aria-label={t('grid.file_grid')}
  aria-activedescendant={activeDescendant}
  aria-busy={browse.loadingWindow}
  tabindex="0"
  onkeydown={onKeydown}
>
  {#if browse.total === 0 && !browse.loading}
    <p class="sc-file-grid__empty">{t('common.folder_empty')}</p>
  {:else}
  <div class="sc-file-grid__spacer" style:height="{win.totalHeight}px">
    <div class="sc-file-grid__window" style:transform="translate3d(0,{win.padTop}px,0)">
      {#each rows as row (row.key)}
        <div class="sc-file-grid__row" role="row" style:height="{CELL.h}px" style:gap="{CELL_GAP}px">
          {#each row.cells as cell (cell.entry ? cell.entry.name : `sc-ph-${cell.index}`)}
            {#if cell.entry}
              {@const entry = cell.entry}
              <!-- svelte-ignore a11y_click_events_have_key_events, a11y_interactive_supports_focus -->
              <div
                id={domId(entry.name)}
                class="sc-file-grid__cell m3-layer"
                class:sc-file-grid__cell--selected={browse.selection.has(entry.name)}
                class:sc-file-grid__cell--focused={browse.focusedName === entry.name}
                role="gridcell"
                aria-selected={browse.selection.has(entry.name)}
                style:width="{CELL.w}px"
                onclick={(e) => onCellClick(e, entry)}
                ondblclick={() => onopen(entry)}
                oncontextmenu={(e) => {
                  e.preventDefault()
                  oncontextmenu(entry, e)
                }}
              >
                <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
                <span class="sc-file-grid__check sc-touch-target" onclick={(e) => onCheckboxClick(e, entry)}>
                  <!-- Inert input, click owned by the cell — see FileRow. -->
                  <Checkbox>
                    <input
                      type="checkbox"
                      checked={browse.selection.has(entry.name)}
                      tabindex="-1"
                      aria-label={t('common.select', { name: entry.name })}
                      onchange={() => {}}
                    />
                  </Checkbox>
                </span>
                <span class="sc-file-grid__icon"><Icon icon={icons[iconName(entry)]} size={32} /></span>
                <span class="sc-file-grid__name">{entry.name}</span>
                <span class="sc-file-grid__meta">{entry.kind === 'dir' ? '—' : formatBytes(entry.size)}</span>
                {#if entry.confusable}
                  <span class="sc-file-grid__badge" title={t('common.look_alike_characters')}><Icon icon={icons.warning} size={14} /></span>
                {/if}
              </div>
            {:else}
              <div class="sc-file-grid__cell sc-file-grid__cell--skeleton" style:width="{CELL.w}px" aria-busy="true">
                <span class="sc-file-grid__skeleton-icon"></span>
                <span class="sc-file-grid__skeleton-name"></span>
              </div>
            {/if}
          {/each}
        </div>
      {/each}
    </div>
  </div>
  {/if}
</div>

<style>
  .sc-file-grid {
    position: relative;
    flex: 1;
    min-width: 0;
    /* Document-scroll migration: see FileTable.svelte's `.sc-file-table`
       rule for the full reasoning -- this element is no longer its own
       scroll container (no `overflow: auto`), doesn't stretch to fill a
       now content-height ancestor (`align-self: flex-start`), and can't
       claim `contain: strict`'s `size` containment since it no longer has
       a definite size independent of its (virtualized) content. */
    align-self: flex-start;
    contain: content;
    background: var(--m3c-surface);
    container-type: inline-size;
    container-name: sc-file-grid;
  }
  .sc-file-grid:focus-visible {
    outline: 3px solid var(--m3c-secondary);
    outline-offset: -3px;
  }
  .sc-file-grid--reserve-bar {
    /* See FileTable.svelte's identical `.sc-file-table--reserve-bar` rule
       for the full reasoning: `NavigationBar` is `position: fixed` and this
       element's real height escapes past `.sc-app-shell__main`'s own box
       (whose `padding-bottom` reservation therefore never reaches here), so
       the bar-height reservation has to live directly on the element whose
       box actually reflects the full (virtualized) content height. */
    padding-bottom: calc(var(--sc-nav-bar-height) + env(safe-area-inset-bottom, 0px));
  }
  .sc-file-grid__window {
    will-change: transform;
    padding-inline: 16px;
  }
  .sc-file-grid__row {
    display: flex;
    align-items: flex-start;
    padding-block-end: 8px;
  }
  .sc-file-grid__cell {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 4px;
    padding: 8px;
    border-radius: var(--m3-shape-medium);
    cursor: pointer;
    color: var(--m3c-on-surface);
    text-align: center;
    position: relative;
  }
  .sc-file-grid__cell--selected {
    background: var(--m3c-secondary-container);
    color: var(--m3c-on-secondary-container);
  }
  /* Only while this grid owns focus — see FileTable.svelte's matching rule
     for why an activedescendant indicator must not draw on an unfocused grid. */
  .sc-file-grid:focus .sc-file-grid__cell--focused {
    outline: 3px solid var(--m3c-secondary);
    outline-offset: -3px;
  }
  .sc-file-grid__icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 64px;
    height: 64px;
    color: var(--m3c-primary);
  }
  .sc-file-grid__name {
    width: 100%;
    @apply --m3-body-medium;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    /*: truncate filenames from the front so the
       extension (the part that disambiguates) survives. */
    direction: rtl;
    text-align: center;
    overflow-wrap: anywhere;
  }
  .sc-file-grid__meta {
    @apply --m3-body-small;
    color: var(--m3c-on-surface-variant);
  }
  .sc-file-grid__cell--selected .sc-file-grid__meta {
    color: inherit;
  }
  .sc-file-grid__badge {
    position: absolute;
    top: 4px;
    right: 4px;
    display: inline-flex;
    color: var(--m3c-error);
  }
  .sc-file-grid__check {
    position: absolute;
    top: 4px;
    left: 4px;
    display: inline-flex;
    /* `.sc-touch-target` (app.css) expands the *hit area* to MD3's 48px
       minimum via an invisible `::before`, without growing the visible
       checkbox glyph -- same utility IconButton/Switch/Checkbox already use. */
  }
  .sc-file-grid__cell--skeleton {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    padding: 8px;
  }
  .sc-file-grid__skeleton-icon {
    width: 64px;
    height: 64px;
    border-radius: var(--m3-shape-medium);
    background: var(--m3c-surface-container-highest);
    animation: sc-file-grid-pulse 1.2s ease-in-out infinite;
  }
  .sc-file-grid__skeleton-name {
    width: 80%;
    height: 12px;
    border-radius: var(--m3-shape-extra-small);
    background: var(--m3c-surface-container-highest);
    animation: sc-file-grid-pulse 1.2s ease-in-out infinite;
  }
  @keyframes sc-file-grid-pulse {
    0%,
    100% {
      opacity: 0.5;
    }
    50% {
      opacity: 1;
    }
  }
  @media (prefers-reduced-motion: reduce) {
    .sc-file-grid__skeleton-icon,
    .sc-file-grid__skeleton-name {
      animation: none;
    }
  }
  .sc-file-grid__empty {
    /* See FileTable.svelte's `.sc-file-table__empty` for why this is a
       plain in-flow block now instead of `position: absolute; inset: 0`. */
    display: flex;
    align-items: center;
    justify-content: center;
    padding-block: 64px;
    color: var(--m3c-on-surface-variant);
  }
</style>
