// frontend/src/features/files/NewFolderDialog.tsx
import { useEffect, useState } from 'react'
import { Button } from '../../ui/Button'
import { TextField } from '../../ui/TextField'
import { BrowseDialog } from './browse-dialog'
import { useI18n } from '../../hooks/use-i18n'
export function NewFolderDialog({
  open,
  onClose,
  onCreate
}: {
  open: boolean
  onClose: () => void
  onCreate: (name: string) => void
}) {
  const { t } = useI18n()
  const [form, setForm] = useState({ name: '', submitted: false })
  useEffect(() => {
    if (open) setForm({ name: t('common.new_folder'), submitted: false })
  }, [open, t, setForm])
  const submit = () => {
    if (form.submitted) return
    const value = form.name.trim()
    if (!value) return
    setForm((state) => ({ ...state, submitted: true }))
    onCreate(value)
  }
  return (
    <BrowseDialog
      open={open}
      title={t('common.new_folder')}
      onClose={onClose}
      actions={
        <>
          <Button variant="text" onClick={onClose}>
            {t('common.cancel')}
          </Button>
          <Button onClick={submit}>{t('common.create')}</Button>
        </>
      }
    >
      <TextField
        value={form.name}
        label={t('new_folder.folder_name')}
        autoFocus
        onValueChange={(name) => setForm((state) => ({ ...state, name }))}
        onKeyDown={(event) => {
          if (event.key === 'Enter') {
            event.preventDefault()
            submit()
          }
        }}
      />
    </BrowseDialog>
  )
}

// web/src/lib/ui/NewFolderDialog.svelte
<script lang="ts">
  import { t } from '../i18n'
  import Button from './Button.svelte'
  import Dialog from './Dialog.svelte'
  import TextField from './TextField.svelte'

  interface Props {
    open: boolean
    onclose: () => void
    oncreate: (name: string) => void
  }
  let { open, onclose, oncreate }: Props = $props()
  // Re-seeded per open rather than once at construction: the seed is itself a
  // translated string, so a locale change between opens has to reach it.
  let name = $state(t('common.new_folder'))

  $effect(() => {
    if (open) name = t('common.new_folder')
  })

  function submit() {
    const trimmed = name.trim()
    if (trimmed) oncreate(trimmed)
  }
</script>

<Dialog {open} title={t('common.new_folder')} onclose={onclose}>
  <TextField
    bind:value={name}
    label={t('new_folder.folder_name')}
    autofocus
    onkeydown={(e) => {
      if (e.key === 'Enter') submit()
    }}
  />
  {#snippet actions()}
    <Button variant="text" onclick={onclose}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={submit}>{t('common.create')}</Button>
  {/snippet}
</Dialog>
