// web/src/lib/ui/NewFolderDialog.tsx
import { useEffect, useState } from 'react'
import { Button } from './Button'
import { TextField } from './TextField'
import { BrowseDialog } from './browse-dialog'
import { useI18n } from '../i18n/use-i18n'
export function NewFolderDialog({ open, onClose, onCreate }: { open: boolean; onClose: () => void; onCreate: (name: string) => void }) {
  const { t } = useI18n(); const [name, setName] = useState(''); const [submitted, setSubmitted] = useState(false)
  useEffect(() => { if (open) { setName(t('common.new_folder')); setSubmitted(false) } }, [open, t])
  const submit = () => { if (submitted) return; const value = name.trim(); if (!value) return; setSubmitted(true); onCreate(value) }
  return <BrowseDialog open={open} title={t('common.new_folder')} onClose={onClose} actions={<><Button variant="text" onClick={onClose}>{t('common.cancel')}</Button><Button onClick={submit}>{t('common.create')}</Button></>}><TextField value={name} label={t('new_folder.folder_name')} autoFocus onValueChange={setName} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); submit() } }} /></BrowseDialog>
}

// web/src/lib/ui/NewFolderDialog.svelte
<script lang="ts">
  import { t } from '../i18n'
  import Button from './Button.svelte'
  import Dialog from './Dialog.svelte'
  import TextField from './TextField.svelte'

  interface Props {
    open: boolean
    onclose: () => void
    oncreate: (name: string) => void
  }
  let { open, onclose, oncreate }: Props = $props()
  // Re-seeded per open rather than once at construction: the seed is itself a
  // translated string, so a locale change between opens has to reach it.
  let name = $state(t('common.new_folder'))

  $effect(() => {
    if (open) name = t('common.new_folder')
  })

  function submit() {
    const trimmed = name.trim()
    if (trimmed) oncreate(trimmed)
  }
</script>

<Dialog {open} title={t('common.new_folder')} onclose={onclose}>
  <TextField
    bind:value={name}
    label={t('new_folder.folder_name')}
    autofocus
    onkeydown={(e) => {
      if (e.key === 'Enter') submit()
    }}
  />
  {#snippet actions()}
    <Button variant="text" onclick={onclose}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={submit}>{t('common.create')}</Button>
  {/snippet}
</Dialog>
