// web/src/lib/ui/RenameDialog.svelte
<script lang="ts">
  import { t } from '../i18n'
  import Button from './Button.svelte'
  import Dialog from './Dialog.svelte'
  import TextField from './TextField.svelte'

  interface Props {
    open: boolean
    currentName: string
    onclose: () => void
    onrename: (name: string) => void
  }
  let { open, currentName, onclose, onrename }: Props = $props()
  // svelte-ignore state_referenced_locally -- intentional: this seeds the
  // editable field once; the $effect below re-seeds it every time the
  // dialog re-opens with a (possibly different) target.
  let name = $state(currentName)

  $effect(() => {
    if (open) name = currentName
  })

  function submit() {
    const trimmed = name.trim()
    if (trimmed && trimmed !== currentName) onrename(trimmed)
    else onclose()
  }
</script>

<Dialog {open} title={t('common.rename')} onclose={onclose}>
  <TextField
    bind:value={name}
    label={t('rename.new_name')}
    autofocus
    onkeydown={(e) => {
      if (e.key === 'Enter') submit()
    }}
  />
  {#snippet actions()}
    <Button variant="text" onclick={onclose}>{t('common.cancel')}</Button>
    <Button variant="filled" onclick={submit}>{t('common.ok')}</Button>
  {/snippet}
</Dialog>

// web/src/lib/ui/RenameDialog.tsx
import { useEffect, useState } from 'react'
import { Button } from './Button'
import { TextField } from './TextField'
import { BrowseDialog } from './browse-dialog'
import { useI18n } from '../i18n/use-i18n'
export function RenameDialog({ open, currentName, onClose, onRename }: { open: boolean; currentName: string; onClose: () => void; onRename: (name: string) => void }) {
  const { t } = useI18n(); const [name, setName] = useState(''); const [submitted, setSubmitted] = useState(false)
  useEffect(() => { if (open) { setName(currentName); setSubmitted(false) } }, [open, currentName])
  const submit = () => { if (submitted) return; setSubmitted(true); const value = name.trim(); if (value && value !== currentName) onRename(value); else onClose() }
  return <BrowseDialog open={open} title={t('common.rename')} onClose={onClose} actions={<><Button variant="text" onClick={onClose}>{t('common.cancel')}</Button><Button onClick={submit}>{t('common.ok')}</Button></>}><TextField value={name} label={t('rename.new_name')} autoFocus onValueChange={setName} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); submit() } }} /></BrowseDialog>
}
