// web/src/lib/ui/SearchPanel.svelte
<script lang="ts">
  // The search experience, once. The desktop top sheet and the phone route
  // both draw this; neither owns any of it.
  //
  // A search here runs to the end. The server streams every match as it finds
  // one, so the list grows while the walk is still going and there is nothing
  // to press for more. What that costs is ordering: matches arrive in the
  // order the tree gives them up, and the sort is applied once the stream
  // finishes, because re-sorting a hundred thousand rows on every arriving
  // batch would spend the whole search sorting.
  import { goto } from '$app/navigation'
  import { api } from '../api/client'
  import type { SearchDone, SearchHit } from '../api/client'
  import { EXTENSION_PRESETS, resolveExtensions } from '../search/filters'
  import { computeWindow } from '../virtual/windowing'
  import { formatBytes } from '../format/bytes'
  import { formatDateNs, t } from '../i18n'
  import { Icon } from 'm3-svelte'
  import { icons } from '../icons'
  import Button from './Button.svelte'
  import Chip from './Chip.svelte'
  import ProgressCircular from './ProgressCircular.svelte'
  import Select from './Select.svelte'
  import TextField from './TextField.svelte'

  interface Props {
    /** The folder the search started from. Ranks that subtree up; it never
     *  narrows the search, which always covers everything reachable. */
    scope?: string
    autofocus?: boolean
    /** A result was opened, so a surface drawn over something else can go
     *  away before the navigation lands. */
    onnavigated?: () => void
    /** Rendered at the end of the query row: the sheet puts its close button
     *  there, the page puts nothing. */
    trailing?: import('svelte').Snippet
  }

  let { scope = '', autofocus = false, onnavigated, trailing }: Props = $props()

  type Kind = 'any' | 'file' | 'dir'
  type SortKey = 'relevance' | 'name' | 'size' | 'date'

  let query = $state('')
  let kind = $state<Kind>('any')
  let presets = $state<readonly string[]>([])
  let extText = $state('')
  let sortKey = $state('relevance')

  /** `$state.raw`: the list is replaced wholesale on every flush, and a deep
   *  proxy over a hundred thousand hits costs on every read. */
  let hits = $state.raw<readonly SearchHit[]>([])
  let running = $state(false)
  /** A query has actually been submitted, so an empty list means "nothing
   *  matched" rather than "not asked yet". */
  let ran = $state(false)
  let failure = $state<string | null>(null)
  let elapsedMs = $state<number | null>(null)

  let cancel: (() => void) | null = null
  /** Hits arrive one frame at a time; rendering per hit would spend the
   *  search re-rendering, so they land here and go in as batches. */
  let arriving: SearchHit[] = []
  let flushTimer: ReturnType<typeof setTimeout> | null = null

  const FLUSH_MS = 100
  const ROW_PX = 48

  function flush(): void {
    if (flushTimer !== null) {
      clearTimeout(flushTimer)
      flushTimer = null
    }
    if (arriving.length === 0) return
    hits = [...hits, ...arriving]
    arriving = []
  }

  function scheduleFlush(): void {
    if (flushTimer !== null) return
    flushTimer = setTimeout(() => {
      flushTimer = null
      flush()
    }, FLUSH_MS)
  }

  /** The framework owns the `<input>`, so focus reaches it through the
   *  wrapper rather than a bound element, the same way TextField's own
   *  autofocus does. */
  export function focus(): void {
    fieldEl?.querySelector('input')?.focus()
  }

  function start(): void {
    cancel?.()
    cancel = null
    arriving = []
    hits = []
    failure = null
    elapsedMs = null
    scrollTop = 0
    listEl?.scrollTo({ top: 0 })

    const text = query.trim()
    if (text === '') {
      ran = false
      running = false
      return
    }

    ran = true
    running = true
    const exts = resolveExtensions(presets, extQuery)
    cancel = api.searchStream(
      { query: text, kind: kind === 'any' ? undefined : kind, exts, scope: scope || undefined },
      (hit: SearchHit) => {
        arriving.push(hit)
        scheduleFlush()
      },
      (done: SearchDone) => {
        flush()
        running = false
        cancel = null
        elapsedMs = done.elapsedMs ?? null
        failure = done.error ?? null
      }
    )
  }

  /** Stops the walk where it is. What arrived stays on screen and says it is
   *  partial, which is the honest reading of a search someone interrupted. */
  function stop(): void {
    if (!running) return
    cancel?.()
    cancel = null
    flush()
    running = false
    failure = 'stopped'
  }

  /** Back to an empty search, filters included: a leftover extension is the
   *  quiet reason a later query finds nothing. */
  function clear(): void {
    cancel?.()
    cancel = null
    arriving = []
    hits = []
    running = false
    ran = false
    failure = null
    query = ''
    kind = 'any'
    presets = []
    extText = ''
    extQuery = ''
    focus()
  }

  function togglePreset(id: string): void {
    presets = presets.includes(id) ? presets.filter((p) => p !== id) : [...presets, id]
  }

  function setKind(next: Kind): void {
    kind = next
    if (next === 'dir') {
      // A folder carries no extension, so the pair matches nothing and the
      // server refuses it. Dropping the type filter here is what the person
      // asking for folders meant.
      presets = []
      extText = ''
      extQuery = ''
    }
  }

  /** The typed extensions as last committed. A search here walks whole trees,
   *  so it runs when the box is left or Enter is pressed, not on the way to
   *  spelling "pdf". */
  let extQuery = $state('')
  function commitExts(): void {
    extQuery = extText
  }

  // A filter changed after a search ran, so the answer on screen is for the
  // old question. Asking again is what the person just requested.
  let lastFilters = $state('')
  $effect(() => {
    const now = `${kind}|${presets.join(',')}|${extQuery.trim().toLowerCase()}`
    if (now === lastFilters) return
    const first = lastFilters === ''
    lastFilters = now
    if (!first && ran) start()
  })

  $effect(() => () => {
    cancel?.()
    if (flushTimer !== null) clearTimeout(flushTimer)
  })

  function sorted(list: readonly SearchHit[], key: SortKey): readonly SearchHit[] {
    if (key === 'relevance') return list
    const out = [...list]
    switch (key) {
      case 'name':
        out.sort((a, b) => a.entry.name.localeCompare(b.entry.name))
        break
      case 'size':
        out.sort((a, b) => b.entry.size - a.entry.size)
        break
      case 'date':
        out.sort((a, b) => Number(BigInt(b.entry.mtime_ns || '0') - BigInt(a.entry.mtime_ns || '0')))
        break
    }
    return out
  }

  // Ordering waits for the end of the stream. The server hands over matches
  // scored and grouped by folder, so mid-search the arrival order is the only
  // stable one there is; sorting each batch would reshuffle the rows under a
  // reader on every flush.
  const view = $derived(running ? hits : sorted(hits, sortKey as SortKey))

  const dirCount = $derived(view.filter((h) => h.entry.kind === 'dir').length)

  /** What is narrowing the search right now, in the words the controls use. */
  const activeFilters = $derived.by(() => {
    const parts: string[] = []
    if (kind === 'file') parts.push(t('search.kind_file'))
    if (kind === 'dir') parts.push(t('search.kind_dir'))
    const exts = resolveExtensions(presets, extQuery)
    if (exts.length > 0) parts.push(exts.join(', '))
    return parts.join(' + ')
  })

  let fieldEl: HTMLDivElement | undefined = $state()
  let listEl: HTMLDivElement | undefined = $state()
  let scrollTop = $state(0)
  let viewportPx = $state(480)

  const window_ = $derived(
    computeWindow({ scrollTop, viewportHeight: viewportPx, rowHeight: ROW_PX, itemCount: view.length, overscan: 8 })
  )
  const rows = $derived(view.slice(window_.start, window_.end))

  $effect(() => {
    const el = listEl
    if (!el || typeof ResizeObserver === 'undefined') return
    const ro = new ResizeObserver(() => {
      viewportPx = el.clientHeight
    })
    ro.observe(el)
    viewportPx = el.clientHeight
    return () => ro.disconnect()
  })

  function onListScroll(): void {
    if (listEl) scrollTop = listEl.scrollTop
  }

  function onQueryKeydown(e: KeyboardEvent): void {
    if (e.key === 'Enter') {
      e.preventDefault()
      start()
    }
  }

  /** The folder a hit lives in, which is the part of a path a name does not
   *  already say. */
  function folderOf(path: string): string {
    const cut = path.lastIndexOf('/')
    return cut <= 0 ? '/' : path.slice(0, cut)
  }

  function open(hit: SearchHit): void {
    onnavigated?.()
    // A folder opens; a file opens the folder holding it, since there is
    // nowhere else to land.
    const target = hit.entry.kind === 'dir' ? hit.path : folderOf(hit.path)
    void goto(`/b${target}`)
  }

  const statusText = $derived.by(() => {
    if (running) return t('search.searching', { count: hits.length })
    if (!ran) return ''
    if (failure === 'stopped') return t('search.stopped', { count: view.length })
    if (failure === 'busy') return t('search.busy')
    if (failure === 'network') return t('search.connection_lost', { count: view.length })
    if (failure) return t('search.failed')
    if (elapsedMs !== null) return t('search.found_in', { count: view.length, ms: elapsedMs })
    return t('search.found', { count: view.length })
  })
</script>

<div class="sc-search">
  <div class="sc-search__query">
    <span class="sc-search__query-icon" aria-hidden="true"><Icon icon={icons.search} /></span>
    <div class="sc-search__field" bind:this={fieldEl}>
      <TextField
        bind:value={query}
        type="search"
        label={t('search.placeholder')}
        {autofocus}
        onkeydown={onQueryKeydown}
      />
    </div>
    <Button variant="filled" onclick={start}>{t('search.run')}</Button>
    {#if ran}
      <!-- Worded, not a second ✕: the field already carries the browser's
           own clear affordance and the sheet its close button, and three
           crosses in a row say nothing about which does what. -->
      <Button variant="text" onclick={clear}>{t('search.clear')}</Button>
    {/if}
    {@render trailing?.()}
  </div>

  <div class="sc-search__filters">
    <div class="sc-search__kinds" role="group" aria-label={t('search.kind')}>
      {#each [['any', t('search.kind_any')], ['file', t('search.kind_file')], ['dir', t('search.kind_dir')]] as const as [id, label] (id)}
        <Chip variant="filter" selected={kind === id} onclick={() => setKind(id as Kind)}>{label}</Chip>
      {/each}
    </div>

    <!-- Gone rather than greyed out while folders are the target: a folder
         has no extension, so every one of these would narrow the answer to
         nothing. -->
    {#if kind === 'dir'}
      <p class="sc-search__hint">{t('search.folders_have_no_extension')}</p>
    {:else}
      <div class="sc-search__presets" role="group" aria-label={t('search.file_types')}>
        {#each EXTENSION_PRESETS as preset (preset.id)}
          <Chip
            variant="filter"
            selected={presets.includes(preset.id)}
            onclick={() => togglePreset(preset.id)}
          >
            {t(preset.labelKey)}
          </Chip>
        {/each}
      </div>

      <div class="sc-search__exts" onfocusout={commitExts}>
        <!-- Committed on Enter or on leaving the box, not per keystroke:
             every commit starts a walk of every share, so "pdf" typed a
             letter at a time would start three of them. -->
        <TextField
          bind:value={extText}
          label={t('search.extensions')}
          placeholder="pdf, hwp, zip"
          onkeydown={(e) => {
            if (e.key === 'Enter') commitExts()
          }}
        />
      </div>
    {/if}
  </div>

  <div class="sc-search__status">
    <!-- The running count changes ten times a second, and a live region
         reading it announces nothing else for the length of the search. The
         count is shown; only the outcome is spoken. -->
    <span class="sc-search__count" aria-hidden={running}>
      {#if running}
        <ProgressCircular size={16} label={t('search.searching_label')} />
      {/if}
      {statusText}
    </span>
    <span class="sc-search__spoken" role="status" aria-live="polite">
      {running ? '' : statusText}
    </span>
    <span class="sc-search__status-actions">
      {#if running}
        <Button variant="text" onclick={stop}>{t('search.stop')}</Button>
      {/if}
      {#if ran && view.length > 0}
        <div class="sc-search__sort">
          <Select
            bind:value={sortKey}
            label={t('search.sort')}
            options={[
              { value: 'relevance', text: t('search.sort_relevance') },
              { value: 'name', text: t('search.sort_name') },
              { value: 'size', text: t('search.sort_size') },
              { value: 'date', text: t('search.sort_date') }
            ]}
          />
        </div>
      {/if}
    </span>
  </div>

  <div class="sc-search__results" bind:this={listEl} onscroll={onListScroll} tabindex="-1">
    {#if !ran}
      <p class="sc-search__note">{t('search.type_and_press_enter')}</p>
    {:else if view.length === 0 && !running}
      <p class="sc-search__note">
        {t('search.no_results')}
        <!-- Naming the filter that is on: an extension left over from the
             previous query is the reason a search finds nothing while
             looking like it searched for everything. -->
        {#if activeFilters !== ''}
          <span class="sc-search__hint">{t('search.filtered_by', { filters: activeFilters })}</span>
        {/if}
      </p>
    {:else}
      <div class="sc-search__spacer" style="height: {window_.totalHeight}px">
        <ul class="sc-search__rows" style="transform: translate3d(0, {window_.padTop}px, 0)">
          {#each rows as hit (hit.path)}
            <li>
              <button class="sc-search__row" type="button" onclick={() => open(hit)}>
                <Icon icon={icons[hit.entry.kind === 'dir' ? 'folder' : 'file']} size={20} />
                <span class="sc-search__name">{hit.entry.name}</span>
                <span class="sc-search__folder">{folderOf(hit.path)}</span>
                <span class="sc-search__size">
                  {hit.entry.kind === 'dir' ? '' : formatBytes(hit.entry.size)}
                </span>
                <span class="sc-search__date">{formatDateNs(hit.entry.mtime_ns)}</span>
              </button>
            </li>
          {/each}
        </ul>
      </div>
    {/if}
  </div>

  {#if ran && view.length > 0}
    <p class="sc-search__summary">
      {t('search.summary', { files: view.length - dirCount, folders: dirCount })}
    </p>
  {/if}
</div>

<style>
  .sc-search {
    display: flex;
    flex-direction: column;
    gap: 12px;
    min-height: 0;
    height: 100%;
  }

  .sc-search__query {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .sc-search__query-icon {
    display: flex;
    color: var(--m3c-on-surface-variant, currentColor);
  }

  .sc-search__field {
    flex: 1 1 auto;
    min-width: 0;
  }

  .sc-search__filters {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 8px;
  }

  .sc-search__kinds,
  .sc-search__presets {
    display: flex;
    flex-wrap: wrap;
    gap: 4px;
  }

  .sc-search__exts {
    /* Sized to the list it holds rather than the row it sits in: stretched
       across the remaining width it read as the main input. */
    flex: 0 1 240px;
    min-width: 160px;
  }

  .sc-search__status {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
    min-height: 40px;
  }

  /* Off-screen but readable: the outcome is announced once, while the
     running count stays visual only. */
  .sc-search__spoken {
    position: absolute;
    width: 4px;
    height: 4px;
    margin: -4px;
    padding: 0;
    overflow: hidden;
    clip-path: inset(50%);
    white-space: nowrap;
  }

  .sc-search__hint {
    margin: 0;
    color: var(--m3c-on-surface-variant, inherit);
    font: var(--m3-font-body-small);
  }

  .sc-search__count {
    display: flex;
    align-items: center;
    gap: 8px;
    font: var(--m3-font-body-medium);
    color: var(--m3c-on-surface-variant, inherit);
  }

  .sc-search__status-actions {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .sc-search__sort {
    min-width: 160px;
  }

  .sc-search__results {
    flex: 1 1 auto;
    min-height: 240px;
    overflow: auto;
    border-radius: 12px;
    background: var(--m3c-surface-container-low, transparent);
  }

  .sc-search__spacer {
    position: relative;
    width: 100%;
  }

  .sc-search__rows {
    position: absolute;
    inset-inline: 0;
    top: 0;
    margin: 0;
    padding: 0;
    list-style: none;
    will-change: transform;
  }

  .sc-search__row {
    display: grid;
    grid-template-columns: 20px minmax(0, 2fr) minmax(0, 3fr) 96px auto;
    align-items: center;
    gap: 12px;
    width: 100%;
    height: 48px;
    padding-inline: 12px;
    border: none;
    background: none;
    color: inherit;
    font: var(--m3-font-body-medium);
    text-align: start;
    cursor: pointer;
  }

  .sc-search__row:hover,
  .sc-search__row:focus-visible {
    background: var(--m3c-surface-container-high, rgb(0 0 0 / 6%));
  }

  .sc-search__name,
  .sc-search__folder {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .sc-search__folder,
  .sc-search__size,
  .sc-search__date {
    color: var(--m3c-on-surface-variant, inherit);
    font: var(--m3-font-body-small);
    /* A wrapped date would push the row past the fixed height the virtual
       list measures every row by, and the window maths would drift. */
    white-space: nowrap;
    overflow: hidden;
  }

  .sc-search__size {
    text-align: end;
    white-space: nowrap;
  }

  .sc-search__note,
  .sc-search__summary {
    margin: 0;
    padding: 16px;
    color: var(--m3c-on-surface-variant, inherit);
    font: var(--m3-font-body-medium);
  }

  .sc-search__summary {
    padding-block: 0;
    padding-inline: 4px;
    font: var(--m3-font-body-small);
  }

  @media (max-width: 840px) {
    .sc-search__row {
      grid-template-columns: 20px minmax(0, 1fr) 80px;
    }

    .sc-search__folder,
    .sc-search__date {
      display: none;
    }
  }
</style>

// web/src/lib/ui/SearchPanel.tsx
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react'
import type { FormEvent, KeyboardEvent, ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import type { SearchDone, SearchHit, SearchProgress } from '../api/client'
import { api } from '../api/client'
import { parentOf } from '../api/path-utils'
import { formatBytes } from '../format/bytes'
import { formatDateNs, formatNumber } from '../i18n'
import { useI18n } from '../i18n/use-i18n'
import { EXTENSION_PRESETS, parseExtensions, resolveExtensions } from '../search/filters'
import { search, type SearchSnapshot, type SearchSortKey } from '../store/search.store'
import { computeWindow } from '../virtual/windowing'
import { Button } from './Button'
import { TextField } from './TextField'
import { Icon } from './Icon'

export interface SearchPanelHandle {
  focus: () => void
}

export interface SearchPanelProps {
  /** The folder search started from. It ranks that subtree but never narrows the search. */
  scope?: string
  autofocus?: boolean
  /** Called immediately before navigating to a result. */
  onnavigated?: () => void
  /** Content rendered at the end of the query row, such as a sheet close button. */
  trailing?: ReactNode
}

type Kind = 'any' | 'file' | 'dir'
type SortKey = SearchSortKey
type SearchFailure = string | null

const FLUSH_MS = 100
const ROW_PX = 60
const SORT_KEYS: readonly [SortKey, string][] = [
  ['relevance', /* i18n */ 'search.sort_relevance'],
  ['name', /* i18n */ 'search.sort_name'],
  ['size', /* i18n */ 'search.sort_size'],
  ['date', /* i18n */ 'search.sort_date']
]

function restoredSnapshot(scope: string): SearchSnapshot | null {
  const snapshot = search.getState().snapshot
  return snapshot?.scope === scope ? snapshot : null
}

function folderOf(path: string): string {
  return parentOf(path)
}

function sortHits(list: readonly SearchHit[], key: SortKey): readonly SearchHit[] {
  if (key === 'relevance') return list
  const result = [...list]
  if (key === 'name') {
    result.sort((a, b) => a.entry.name.localeCompare(b.entry.name))
  } else if (key === 'size') {
    result.sort((a, b) => b.entry.size - a.entry.size)
  } else {
    result.sort((a, b) => {
      const left = BigInt(b.entry.mtime_ns || '0')
      const right = BigInt(a.entry.mtime_ns || '0')
      return left === right ? 0 : left > right ? 1 : -1
    })
  }
  return result
}

export const SearchPanel = forwardRef<SearchPanelHandle, SearchPanelProps>(function SearchPanel({
  scope = '',
  autofocus = false,
  onnavigated,
  trailing
}, ref) {
  const { t } = useI18n()
  const navigate = useNavigate()
  const restored = useMemo(() => restoredSnapshot(scope), [scope])
  const [query, setQuery] = useState(restored?.query ?? '')
  const [kind, setKindState] = useState<Kind>(restored?.kind ?? 'any')
  const [presets, setPresets] = useState<readonly string[]>(restored ? [...restored.presets] : [])
  const [extText, setExtText] = useState(restored?.extText ?? '')
  const [extQuery, setExtQuery] = useState(restored?.extQuery ?? '')
  const [sortKey, setSortKey] = useState<SortKey>(restored?.sortKey ?? 'relevance')
  const [hits, setHits] = useState<readonly SearchHit[]>(restored?.hits ?? [])
  const [running, setRunning] = useState(restored?.running ?? false)
  const [ran, setRan] = useState(restored?.ran ?? false)
  const [failure, setFailure] = useState<SearchFailure>(restored?.running ? 'stopped' : restored?.failure ?? null)
  const [truncated, setTruncated] = useState(restored?.truncated ?? false)
  const [elapsedMs, setElapsedMs] = useState<number | null>(restored?.elapsedMs ?? null)
  const [scanned, setScanned] = useState<SearchProgress | null>(restored?.scanned ?? null)
  const [filtersOpen, setFiltersOpen] = useState(false)
  const [sortOpen, setSortOpen] = useState(false)
  const [scrollTop, setScrollTop] = useState(restored?.scrollTop ?? 0)

  const fieldContainer = useRef<HTMLDivElement>(null)
  const resultsContainer = useRef<HTMLDivElement>(null)
  const cancelRef = useRef<(() => void) | null>(null)
  const arrivingRef = useRef<SearchHit[]>([])
  const flushTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const generationRef = useRef(0)
  const restoredScrollTopRef = useRef(restored?.scrollTop ?? 0)
  const lastFiltersRef = useRef(`${kind}|${presets.join(',')}|${extQuery.trim().toLowerCase()}`)
  const latestRef = useRef({
    scope,
    query,
    kind,
    presets,
    extText,
    extQuery,
    sortKey,
    hits,
    running,
    ran,
    failure,
    truncated,
    elapsedMs,
    scanned,
    scrollTop
  })
  latestRef.current = {
    scope,
    query,
    kind,
    presets,
    extText,
    extQuery,
    sortKey,
    hits,
    running,
    ran,
    failure,
    truncated,
    elapsedMs,
    scanned,
    scrollTop
  }

  useImperativeHandle(ref, () => ({
    focus: () => {
      const input = fieldContainer.current?.querySelector<HTMLElement>('input')
      input?.focus()
    }
  }), [])

  const flush = (): void => {
    if (flushTimerRef.current !== null) {
      clearTimeout(flushTimerRef.current)
      flushTimerRef.current = null
    }
    const arriving = arrivingRef.current.splice(0)
    if (arriving.length > 0) {
      const next = [...latestRef.current.hits, ...arriving]
      latestRef.current.hits = next
      setHits(next)
    }
  }

  const scheduleFlush = (): void => {
    if (flushTimerRef.current !== null) return
    flushTimerRef.current = setTimeout(() => {
      flushTimerRef.current = null
      flush()
    }, FLUSH_MS)
  }

  const cancelStream = (): void => {
    cancelRef.current?.()
    cancelRef.current = null
  }

  const start = (): void => {
    generationRef.current += 1
    const generation = generationRef.current
    cancelStream()
    if (flushTimerRef.current !== null) {
      clearTimeout(flushTimerRef.current)
      flushTimerRef.current = null
    }
    arrivingRef.current = []
    latestRef.current.hits = []
    setHits([])
    setFailure(null)
    setTruncated(false)
    setElapsedMs(null)
    setScanned(null)
    restoredScrollTopRef.current = 0
    setScrollTop(0)
    if (query.trim() === '') {
      setRan(false)
      setRunning(false)
      return
    }

    setRan(true)
    setRunning(true)
    const stopStream = api.searchStream(
      {
        query: query.trim(),
        kind: kind === 'any' ? undefined : kind,
        exts: resolveExtensions(presets, extQuery),
        scope: scope || undefined
      },
      (hit) => {
        if (generation !== generationRef.current) return
        arrivingRef.current.push(hit)
        scheduleFlush()
      },
      (done: SearchDone) => {
        if (generation !== generationRef.current) return
        flush()
        setRunning(false)
        cancelRef.current = null
        setElapsedMs(done.elapsedMs ?? null)
        setFailure(done.error ?? null)
        setTruncated(done.truncated === true)
      },
      (progress: SearchProgress) => {
        if (generation !== generationRef.current) return
        setScanned(progress)
      }
    )
    if (generation === generationRef.current) cancelRef.current = stopStream
    else stopStream()
  }

  const stop = (): void => {
    if (!running) return
    generationRef.current += 1
    cancelStream()
    flush()
    setRunning(false)
    setFailure('stopped')
    setTruncated(false)
  }

  const clear = (): void => {
    generationRef.current += 1
    cancelStream()
    if (flushTimerRef.current !== null) {
      clearTimeout(flushTimerRef.current)
      flushTimerRef.current = null
    }
    arrivingRef.current = []
    latestRef.current.hits = []
    setHits([])
    setRunning(false)
    setRan(false)
    setFailure(null)
    setTruncated(false)
    setElapsedMs(null)
    setScanned(null)
    setQuery('')
    setKindState('any')
    setPresets([])
    setExtText('')
    setExtQuery('')
    restoredScrollTopRef.current = 0
    setScrollTop(0)
    queueMicrotask(() => fieldContainer.current?.querySelector<HTMLElement>('input')?.focus())
  }

  useEffect(() => {
    const next = `${kind}|${presets.join(',')}|${extQuery.trim().toLowerCase()}`
    const previous = lastFiltersRef.current
    lastFiltersRef.current = next
    if (previous !== next && ran) start()
  }, [kind, presets, extQuery, ran])


  const chooseKind = (next: Kind): void => {
    setKindState(next)
    if (next === 'dir') {
      setPresets([])
      setExtText('')
      setExtQuery('')
    }
  }

  const commitExtensions = (): void => setExtQuery(extText)

  const view = running ? hits : sortHits(hits, sortKey)
  const dirCount = view.filter((hit) => hit.entry.kind === 'dir').length
  const fileCount = view.length - dirCount
  const activeFilters = [
    ...presets.flatMap((id) => {
      const preset = EXTENSION_PRESETS.find((candidate) => candidate.id === id)
      return preset ? [t(preset.labelKey)] : []
    }),
    ...parseExtensions(extQuery)
  ].join(', ')
  const sortLabel = t(SORT_KEYS.find(([key]) => key === sortKey)?.[1] ?? 'search.sort_relevance')

  const statusText = running
    ? `${t('search.searching', { count: hits.length })}${scanned ? `, ${t('search.scanning', { dirs: formatNumber(scanned.dirs) })}` : ''}`
    : !ran
      ? ''
      : truncated
        ? t('search.incomplete', { count: view.length })
        : failure === 'stopped'
          ? t('search.stopped', { count: view.length })
          : failure === 'busy'
            ? t('search.busy')
            : failure === 'network'
              ? t('search.connection_lost', { count: view.length })
              : failure
                ? t('search.failed')
                : elapsedMs !== null
                  ? t('search.found_in', { count: view.length, ms: elapsedMs })
                  : t('search.found', { count: view.length })

  const viewportHeight = resultsContainer.current?.clientHeight ?? 480
  const windowed = computeWindow({
    scrollTop,
    viewportHeight,
    rowHeight: ROW_PX,
    itemCount: view.length,
    overscan: 8
  })
  const rows = view.slice(windowed.start, windowed.end)

  const snapshot = (overrides: Partial<SearchSnapshot> = {}): SearchSnapshot => ({
    scope,
    query,
    kind,
    presets,
    extText,
    extQuery,
    sortKey,
    hits,
    running,
    ran,
    failure,
    truncated,
    elapsedMs,
    scanned,
    scrollTop,
    ...overrides
  })

  useEffect(() => {
    search.saveSnapshot(snapshot())
  }, [scope, query, kind, presets, extText, extQuery, sortKey, hits, running, ran, failure, truncated, elapsedMs, scanned, scrollTop])

  useEffect(() => {
    const restoredScrollTop = restoredScrollTopRef.current
    if (restoredScrollTop <= 0 || view.length === 0 || !resultsContainer.current) return
    const frame = requestAnimationFrame(() => {
      if (!resultsContainer.current || restoredScrollTopRef.current !== restoredScrollTop) return
      resultsContainer.current.scrollTop = restoredScrollTop
      restoredScrollTopRef.current = 0
      setScrollTop(restoredScrollTop)
    })
    return () => cancelAnimationFrame(frame)
  }, [view.length])

  useEffect(() => {
    return () => {
      generationRef.current += 1
      cancelStream()
      flush()
      const current = latestRef.current
      search.saveSnapshot({
        scope: current.scope,
        query: current.query,
        kind: current.kind,
        presets: current.presets,
        extText: current.extText,
        extQuery: current.extQuery,
        sortKey: current.sortKey,
        hits: latestRef.current.hits,
        running: false,
        ran: current.ran,
        failure: current.running ? 'stopped' : current.failure,
        truncated: current.truncated,
        elapsedMs: current.elapsedMs,
        scanned: current.scanned,
        scrollTop: current.scrollTop
      })
      if (flushTimerRef.current !== null) clearTimeout(flushTimerRef.current)
      flushTimerRef.current = null
    }
  }, [])

  const onSubmit = (event: FormEvent): void => {
    event.preventDefault()
    start()
  }

  const onQueryKeyDown = (event: KeyboardEvent<HTMLElement>): void => {
    if (event.key === 'Enter') {
      event.preventDefault()
      start()
    }
  }

  const openResult = (hit: SearchHit): void => {
    search.saveSnapshot(snapshot())
    onnavigated?.()
    void navigate(`/b${folderOf(hit.path)}?focus=${encodeURIComponent(hit.entry.name)}`)
  }

  return (
    <div className="sc-search">
      <form className="sc-search__query" onSubmit={onSubmit}>
        <span className="sc-search__query-icon" aria-hidden="true"><Icon name="search" /></span>
        <div className="sc-search__field" ref={fieldContainer}>
          <TextField
            value={query}
            type="search"
            label={t('search.placeholder')}
            autoFocus={autofocus}
            onValueChange={setQuery}
            onKeyDown={onQueryKeyDown}
          />
        </div>
        <Button type="submit" variant="filled">{t('search.run')}</Button>
        {ran ? <Button variant="text" onClick={clear}>{t('search.clear')}</Button> : null}
        {trailing}
      </form>

      <div className="sc-search__scope" aria-describedby="sc-search-scope-note">
        <span className="sc-search__scope-label">{t('search.scope_all_accessible')}</span>
        <span id="sc-search-scope-note">{scope ? t('search.scope_current_prioritized', { folder: scope }) : t('search.scope_explanation')}</span>
      </div>

      <div className="sc-search__filters">
        <span className="sc-search__label" id="sc-search-kind">{t('search.kind_label')}</span>
        <div className="sc-search__kind" role="group" aria-labelledby="sc-search-kind">
          <button type="button" className={kind === 'any' ? 'sc-search__filter-button sc-search__filter-button--selected' : 'sc-search__filter-button'} aria-pressed={kind === 'any'} onClick={() => chooseKind('any')}>{t('search.kind_any')}</button>
          <button type="button" className={kind === 'file' ? 'sc-search__filter-button sc-search__filter-button--selected' : 'sc-search__filter-button'} aria-pressed={kind === 'file'} onClick={() => chooseKind('file')}>{t('search.kind_file')}</button>
          <button type="button" className={kind === 'dir' ? 'sc-search__filter-button sc-search__filter-button--selected' : 'sc-search__filter-button'} aria-pressed={kind === 'dir'} onClick={() => chooseKind('dir')}>{t('search.kind_dir')}</button>
        </div>
        {kind !== 'dir' ? (
          <>
            <button type="button" className="sc-search__filter-menu-trigger" aria-expanded={filtersOpen} onClick={() => setFiltersOpen((open) => !open)}>
              <Icon name="filter_list" />{t('search.file_type')}
            </button>
            {presets.map((id) => {
              const preset = EXTENSION_PRESETS.find((candidate) => candidate.id === id)
              if (!preset) return null
              return <button key={id} type="button" className="sc-search__chip" aria-label={t('search.remove_filter', { label: t(preset.labelKey) })} onClick={() => setPresets((current) => current.filter((value) => value !== id))}>{t(preset.labelKey)} <span aria-hidden="true">×</span></button>
            })}
            <div className="sc-search__exts" onBlur={(event) => { if (!event.currentTarget.contains(event.relatedTarget)) commitExtensions() }}>
              <TextField value={extText} label={t('search.extensions')} placeholder={t('search.extensions')} onValueChange={setExtText} onKeyDown={(event) => { if (event.key === 'Enter') commitExtensions() }} />
            </div>
            {filtersOpen ? (
              <div className="sc-search__menu" role="menu">
                {EXTENSION_PRESETS.map((preset) => {
                  const selected = presets.includes(preset.id)
                  return <button key={preset.id} type="button" role="menuitemcheckbox" aria-checked={selected} aria-label={selected ? t('search.filter_selected', { label: t(preset.labelKey) }) : undefined} onClick={() => setPresets((current) => selected ? current.filter((id) => id !== preset.id) : [...current, preset.id])}>{selected ? '✓ ' : ''}{t(preset.labelKey)}</button>
                })}
              </div>
            ) : null}
          </>
        ) : null}
      </div>

      <div className="sc-search__status">
        <span className="sc-search__count" aria-hidden={running}>{running ? <span className="sc-search__progress" role="img" aria-label={t('search.searching_label')}><mdui-circular-progress /></span> : null}{statusText}</span>
        <span className="sc-search__spoken" role="status" aria-live="polite">{running ? '' : statusText}</span>
        <span className="sc-search__status-actions">
          {!running && fileCount > 0 && dirCount > 0 ? <span className="sc-search__breakdown">{t('search.summary', { files: fileCount, folders: dirCount })}</span> : null}
          {running ? <Button variant="text" onClick={stop}>{t('search.stop')}</Button> : null}
          {ran && view.length > 0 ? (
            <span className="sc-search__sort-wrap">
              <button type="button" className="sc-search__sort-trigger" aria-expanded={sortOpen} aria-label={t('search.sort_by', { key: sortLabel })} onClick={() => setSortOpen((open) => !open)}><Icon name="sort" />{sortLabel}</button>
              {sortOpen ? <div className="sc-search__menu sc-search__menu--end" role="menu">{SORT_KEYS.map(([key, labelKey]) => <button key={key} type="button" role="menuitemradio" aria-checked={sortKey === key} onClick={() => { setSortKey(key); setSortOpen(false) }}>{sortKey === key ? '✓ ' : ''}{t(labelKey)}</button>)}</div> : null}
            </span>
          ) : null}
        </span>
      </div>

      <div className="sc-search__results" ref={resultsContainer} onScroll={(event) => setScrollTop(event.currentTarget.scrollTop)} tabIndex={-1}>
        {!ran ? <p className="sc-search__note">{t('search.type_and_press_enter')}</p> : view.length === 0 && !running ? <p className="sc-search__note">{t('search.no_results')} {activeFilters ? <span className="sc-search__hint">{t('search.filtered_by', { filters: activeFilters })}</span> : null}</p> : (
          <div className="sc-search__spacer" style={{ height: windowed.totalHeight }}>
            <ul className="sc-search__rows" style={{ transform: `translate3d(0, ${windowed.padTop}px, 0)` }}>
              {rows.map((hit) => (
                <li key={hit.path}>
                  <button type="button" className="sc-search__row" onClick={() => openResult(hit)}>
                    <Icon name={hit.entry.kind === 'dir' ? 'folder' : 'draft'} />
                    <span className="sc-search__text"><span className="sc-search__name">{hit.entry.name}</span><span className="sc-search__folder">{folderOf(hit.path)}</span></span>
                    <span className="sc-search__cell">{hit.entry.kind !== 'dir' ? <span className="sc-search__size">{formatBytes(hit.entry.size)}</span> : null}<span className="sc-search__date">{formatDateNs(hit.entry.mtime_ns)}</span></span>
                  </button>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  )
})
