// frontend/src/ui/Select.tsx
import { useEffect, useRef } from 'react'

export interface SelectOption {
  value: string
  text?: string
  label?: string
  disabled?: boolean
}

export interface SelectProps {
  value?: string
  label?: string
  options: SelectOption[]
  testid?: string
  id?: string
  name?: string
  disabled?: boolean
  required?: boolean
  ariaLabel?: string
  ariaDescribedby?: string
  onValueChange?: (value: string) => void
  onChange?: (value: string) => void
}

interface SelectElement extends HTMLElement {
  value: string
  updateComplete?: Promise<unknown>
}

export function Select({
  value = '',
  label,
  options,
  testid,
  id,
  name,
  disabled = false,
  required = false,
  ariaLabel,
  ariaDescribedby,
  onValueChange,
  onChange
}: SelectProps) {
  const ref = useRef<SelectElement | null>(null)

  useEffect(() => {
    const element = ref.current
    if (element && element.value !== value) {
      element.value = value
    }
  }, [value])

  useEffect(() => {
    const element = ref.current
    if (!element) return
    const handleChange = () => {
      const next = element.value
      onValueChange?.(next)
      onChange?.(next)
    }
    element.addEventListener('change', handleChange)
    return () => element.removeEventListener('change', handleChange)
  }, [onValueChange, onChange])

  return (
    <div className="sc-select">
      <mdui-select
        ref={ref}
        variant="outlined"
        value={value}
        label={label}
        id={id}
        name={name}
        disabled={disabled}
        required={required}
        data-testid={testid}
        aria-label={ariaLabel ?? label}
        aria-describedby={ariaDescribedby}
        style={{ width: '100%' }}
        onKeyDown={(event) => {
          // The open list closes on Escape by itself; marking the key handled keeps an enclosing dialog open.
          const dropdown = ref.current?.shadowRoot?.querySelector<HTMLElement & { open?: boolean }>('mdui-dropdown')
          if (event.key === 'Escape' && dropdown?.open) event.preventDefault()
        }}
      >
        {options.map((option) => (
          <mdui-menu-item key={option.value} value={option.value} disabled={option.disabled}>
            {option.text ?? option.label ?? option.value}
          </mdui-menu-item>
        ))}
      </mdui-select>
    </div>
  )
}

// web/src/lib/ui/Select.tsx
import type { ChangeEvent } from 'react'

export interface SelectOption {
  value: string
  text?: string
  label?: string
  disabled?: boolean
}

export interface SelectProps {
  value?: string
  label: string
  options: SelectOption[]
  testid?: string
  id?: string
  name?: string
  disabled?: boolean
  required?: boolean
  ariaDescribedby?: string
  onValueChange?: (value: string) => void
  onChange?: (value: string) => void
}

export function Select({
  value = '',
  label,
  options,
  testid,
  id,
  name,
  disabled = false,
  required = false,
  ariaDescribedby,
  onValueChange,
  onChange
}: SelectProps) {
  const handleChange = (event: ChangeEvent<HTMLSelectElement>) => {
    onValueChange?.(event.currentTarget.value)
    onChange?.(event.currentTarget.value)
  }
  return (
    <label className="sc-select">
      <span className="sc-select__label">{label}</span>
      <select
        value={value}
        id={id}
        name={name}
        disabled={disabled}
        required={required}
        data-testid={testid}
        aria-describedby={ariaDescribedby}
        onChange={handleChange}
      >
        {options.map((option) => (
          <option key={option.value} value={option.value} disabled={option.disabled}>
            {option.text ?? option.label ?? option.value}
          </option>
        ))}
      </select>
    </label>
  )
}
