// web/src/lib/ui/ProgressCircular.svelte
<script lang="ts">
  // Adapter over m3-svelte's two circular progress components. The framework
  // splits what this used to be one component for: `CircularProgress` is
  // determinate and *requires* a percentage, `LoadingIndicator` is the
  // indeterminate one. `value === null` (the default, and what every current
  // call site uses) picks the latter.
  import { CircularProgress, LoadingIndicator } from 'm3-svelte'
  import { t } from '../i18n'

  interface Props {
    /** 0..1, or null for indeterminate. */
    value?: number | null
    size?: number
    label?: string
  }

  // No default *value* for `label`: one evaluated at construction would keep
  // whichever locale was live then. Resolved reactively instead.
  let { value = null, size = 24, label }: Props = $props()
  const resolved = $derived(label ?? t('progress.loading'))
  const fraction = $derived(
    typeof value === 'number' && Number.isFinite(value) ? Math.min(Math.max(value, 0), 1) : 0
  )
  const indeterminate = $derived(
    value === null || typeof value !== 'number' || !Number.isFinite(value)
  )
  const percent = $derived(Math.round(fraction * 100))
</script>

{#if indeterminate}
  <LoadingIndicator {size} aria-label={resolved} />
{:else}
  <CircularProgress percent={percent} {size} aria-label={resolved} />
{/if}

// frontend/src/ui/ProgressCircular.tsx
import 'mdui/components/circular-progress.js'
import { useEffect, useRef } from 'react'
import { useI18n } from '../hooks/use-i18n'

interface ProgressElement extends HTMLElement {
  updateComplete?: Promise<unknown>
}

function syncProgressLabel(element: ProgressElement | null, label: string): void {
  if (!element) return
  const apply = () => {
    const progress = element.shadowRoot?.querySelector<HTMLElement>('svg, [role="progressbar"]')
    if (progress) progress.setAttribute('aria-label', label)
  }
  if (element.updateComplete) void element.updateComplete.then(apply)
  else queueMicrotask(apply)
}
export interface ProgressCircularProps {
  value?: number | null
  size?: number
  label?: string
}

export function ProgressCircular({ value = null, size = 24, label }: ProgressCircularProps) {
  const { t } = useI18n()
  const indeterminate = value === null || typeof value !== 'number' || !Number.isFinite(value)
  const percent = Math.round(Math.min(Math.max(value ?? 0, 0), 1) * 100)
  const resolved = label ?? t('progress.loading')
  const ref = useRef<ProgressElement | null>(null)
  useEffect(() => {
    syncProgressLabel(ref.current, resolved)
  }, [resolved])
  return (
    <mdui-circular-progress
      ref={ref}
      value={indeterminate ? undefined : percent / 100}
      max={1}
      style={{ width: size, height: size }}
      aria-label={resolved}
    />
  )
}
